### ISSUE TITLE
build.bat fails on a clean system

### ISSUE THREAD

**Issue by mikkelbu** [elastic/windows-installers#1]
I just tried to download the code and execute build.bat, but the script failed in a couple of places and I had to make a few changes in order to make it produce elasticsearch.msi.

More concretely, I had the following problems:
* Two csprojs (Elastic.Installer.Domain.csproj, Elastic.Installer.UI.csproj) refer to “Microsoft.Deployment.WindowsInstaller” without specifying a hint path, i.e. “..\..\packages\WixSharp.bin\lib\Microsoft.Deployment.WindowsInstaller.dll”. So I added hintpaths mimicking the correct usage in `Elastic.Installer.Msi.csproj`.
* WiX binaries could not be found. The script then failed with:

> System.Exception: WiX binaries cannot be found. Wix# is capable of automatically finding WiX tools only if WiX Toolset installed. In all other cases you need to set the environment variable WIXSHARP_WIXDIR or WixSharp.Compiler.WixLocation to the valid path to the WiX binaries.
>
> WiX binaries can be brought to the build environment by either installing WiX Toolset, downloading Wix# suite or by adding WixSharp.wix.bin NuGet package to your project.
>
>    at WixSharp.Compiler.get_WixLocation()
>    at WixSharp.Compiler.get_WixSdkLocation()
>    at WixSharp.Compiler.PackageManagedAsm(String asm, String nativeDll, String[] refAssemblies, String outDir, String configFilePath, Nullable`1 platform, Boolean embeddedUI, String batchFile)
>    at WixSharp.Compiler.ProcessCustomActions(Project wProject, XElement product)
>    at WixSharp.Compiler.GenerateWixProj(Project project)
>    at WixSharp.Compiler.BuildWxs(Project project, String path, OutputType type)
>    at Elastic.Installer.Msi.Program.Main(String[] args) in sourcefolder\windows-installers-master\src\Elastic.Installer.Msi\Program.cs:line 133

I had to add a nuget dependency to “WixSharp.wix.bin” and I also set the environment variable WIXSHARP_WIXDIR to "sourcefolder\windows-installers-master\packages\WixSharp.wix.bin\tools\bin". 

Would you accept a pull request with the above changes? I will probably set `Compiler.WixLocation` just before the call to `Compiler.BuildWxs` in `Elastic.Installer.Msi\Program.cs` instead of using the environment variable.

**Comment by gmarz** [comment]
Ah, the readme forgets to mention that the [WiX Toolset SDK](http://wixtoolset.org/releases/) is a required prerequisite.  The `WIX` environment variable is set upon installing the SDK, which is all that should be necessary.  Would you mind installing WiX first, then doing another clean checkout and build to see if that works?

Your approach is also nice in that the build script will bootstrap WiX.  If you're willing to open a PR I'd be happy to review.  I'll update the readme in the mean time.  Thanks for raising this!

**Comment by Mpdreamz** [comment]
Death to SDK's! PR very much welcomed!

**Comment by mikkelbu** [comment]
I must admit that I'm not sure the right way to add the dependency to "WixSharp.wix.bin" (and I have never used Paket before, so I'm googling a lot ;)).

If I make a fresh clone and then execute 
`.\.paket\paket.bootstrapper.exe`
followed by
`.\.paket\paket.exe add nuget WixSharp.wix.bin`
Then I get a lot of changes (and 2 added files), since Paket updates csproj's etc. as part of the update. And almost all of the changes are not related to the newly added package (and there are many changes within the "Paket-part" of the csprojs).

> Source\AddPackage\windows-installers $ git status
> On branch master
> Your branch is up-to-date with 'origin/master'.
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
> 
>         modified:   paket.dependencies
>         modified:   paket.lock
>         modified:   src/Elastic.Installer.Domain/Elastic.Installer.Domain.csproj
>         modified:   src/Elastic.Installer.Msi/Elastic.Installer.Msi.csproj
>         modified:   src/Elastic.Installer.UI/Elastic.Installer.UI.csproj
>         modified:   src/Elasticsearch/Elastic.Installer.Elasticsearch.DevHost/Elastic.Installer.Elasticsearch.DevHost.csproj
>         modified:   src/Elasticsearch/Elastic.Installer.Elasticsearch.Process/Elastic.Installer.Elasticsearch.Process.csproj
>         modified:   src/Tests/Elastic.Installer.Domain.Tests/Elastic.Installer.Domain.Tests.csproj
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 
>         src/Elastic.Installer.UI/Resources/Entypo-license.txt
>         src/Elastic.Installer.UI/Resources/Entypo.ttf
> 

I get the same changes if I have a fresh clone and then execute
`.\.paket\paket.bootstrapper.exe`
followed by
`.\.paket\paket.exe install`
So it seems that the changes are due to the fact that the csprojs are not up-2-date with paket.dependencies / paket.lock.

Will it be ok, if I break my pull request into two commits. The first commit after executing `paket.exe install` and then the second commit with my changes (i.e. adding the new package, setting `Compiler.WixLocation` etc.).

**Comment by gmarz** [comment]
> Will it be ok, if I break my pull request into two commits. The first commit after executing paket.exe install and then the second commit with my changes (i.e. adding the new package, setting Compiler.WixLocation etc.).

That's fine, but it's also okay if you do it all in a single commit.  Looking forward to the PR :)
