### ISSUE TITLE
Reinstalling without x-pack causes unhandled exception in 6.0-beta2

### ISSUE THREAD

**Issue by roncohen** [elastic/windows-installers#100]
I installed 6.0.0-beta2 with x-pack and Elasticsearch started with no issues.
I then uninstalled using "Add/remove applications" and re-installed without x-pack.

After that, Elasticsearch wouldn't start.  There’s a .NET stacktrace in the eventlog which seems related:
<img width="1151" alt="screenshot 2017-09-12 17 38 37" src="https://user-images.githubusercontent.com/744/30335508-de7f8f18-97e2-11e7-8d42-0ef72e99d01a.png">

Included the one above as well, but doesn't look like it's much use:
<img width="733" alt="screenshot 2017-09-12 17 51 19" src="https://user-images.githubusercontent.com/744/30335587-157f9c56-97e3-11e7-9af3-007b6bcd58ba.png">

**Comment by russcam** [comment]
Thanks for opening @roncohen. Do you also have the elasticsearch.log file?

**Comment by roncohen** [comment]
@russcam I found nothing in the logs directory (in fact, the directory didn't exist)

**Comment by russcam** [comment]
@roncohen I'm looking to close this issue as I think it's not going to be possible to reproduce it.

The installer is undergoing a lot of development at the moment for 6.0 GA; once we're in a good place, would you mind retrying with a newer installer?

**Comment by russcam** [comment]
Closing this issue as I suspect it's related to #127. Will track there
