### ISSUE TITLE
Error during ElasticSearch installation v5.6.0

### ISSUE THREAD

**Issue by sachin27sharma** [elastic/windows-installers#106]
[elasticsearch.txt](https://github.com/elastic/windows-installers/files/1310637/elasticsearch.txt)

**Comment by russcam** [comment]
It looks like the account that you are using to start Elasticsearch does not have sufficient privileges to access the location `C:\ProgramData\Elastic\Elasticsearch\data`. 

Can you start Elasticsearch with an Administrator account?

**Comment by sachin27sharma** [comment]
I did tried installing to another folder but its still failing. There isn't any clear reason as to why installation is failing. I do have restricted dev access but am installing with elevated permission with admin access.

**Comment by russcam** [comment]
> I did tried installing to another folder but its still failing.

Is the installation failing _or_ is installation succeeding but Elasticsearch throwing an exception when starting? Do you have the log for the MSI installation too?

**Comment by russcam** [comment]
any update on this @sachin27sharma?
