### ISSUE TITLE
How to resolve 'CustomAction AddUPDDriverAndPrinter returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)'

### ISSUE THREAD

**Issue by vatk** [elastic/windows-installers#110]
CPLog: DisableWow64FsRedirection: Wow64DisableWow64FsRedirection returned 1056: An instance of the service is already running. 
CPLog: RevertWow64FsRedirection: Wow64RevertWow64FsRedirection returned 2: The system cannot find the file specified. 
CPLog: CopyHPCloudPrintPortFiles:Copying Port monitor File returned with :false
CPLog: CopyHPCloudPrintPortFiles:CopyFile returned 2: The system cannot find the file specified. 
CPLog: AddUPDDriverAndPrinter returned 2: The system cannot find the file specified. 
CustomAction AddUPDDriverAndPrinter returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 14:18:54: InstallExecute. Return value 3.

**Comment by russcam** [comment]
@vatk Please provide the entire log file. On first glance, this doesn't _look_ like an MSI log from the Elasticsearch installer.

**Comment by vatk** [comment]
[SetupMSI.log](https://github.com/elastic/windows-installers/files/1328347/SetupMSI.log)

**Comment by vatk** [comment]
please check and let me know

**Comment by russcam** [comment]
From SetupMSI.log:

> C:\Users\administrator.EE\AppData\Local\Downloaded Installations\{92D0DA60-93D5-4935-8696-0C0FECDECE76}\HP ePrint Enterprise Edition.msi

This isn't the log file for the Elasticsearch Windows Installer. If you're installing using the UI, a link to the log file will be presented on the final view, if the installation fails:

![failed_install_highlight](https://user-images.githubusercontent.com/208231/30794318-d21b3d3a-a20a-11e7-9633-c607a75ffb25.png)

**Comment by vatk** [comment]
Thanks russcam, Now i resolve this issue
Thanks Again
