### ISSUE TITLE
After migrating Project from visual studio 2010 to Visual studio 2015 why few of C++ projects is not migrating.

### ISSUE THREAD

**Issue by vatk** [elastic/windows-installers#111]
![untitled](https://user-images.githubusercontent.com/32122120/30802210-5f047b2e-a203-11e7-9cb6-4fee00a4fb5b.png)

**Comment by russcam** [comment]
@vatk This isn't related to the [Elastic Windows Installers](https://github.com/elastic/windows-installers). I'm not sure where you should be filing this issue, perhaps the ["Report a Problem"](https://msdn.microsoft.com/en-us/library/mt632287.aspx) funcitonality inside Visual Studio would be a good option.

I'm closing this issue.
