### ISSUE TITLE
Urgent - Getting Warning C4800 'BOOL': forcing value to bool 'true' or 'false' (performance warning)

### ISSUE THREAD

**Issue by vatk** [elastic/windows-installers#112]
Here i am getting the warning
bool ret =CopyFile(commandLineLoclamon.c_str(),portMonitorFile.c_str(),false);

**Comment by russcam** [comment]
@vatk I'm not sure what this relates to, but it doesn't look to be related to the [Elastic Windows Installers.](https://github.com/elastic/windows-installers) 

I'm closing this issue.
