### ISSUE TITLE
Error to install ElasticSearch 5.6.1 on Win7 64bits

### ISSUE THREAD

**Issue by lrslima** [elastic/windows-installers#113]
I was following the [tutorial](https://www.elastic.co/guide/en/elasticsearch/reference/current/windows.html) trying to install the elasticSearch but I got an error during the setup.

Error log: https://www.dropbox.com/s/069c7vf4za0jou7/MSIc46b5.LOG?dl=0

**Comment by russcam** [comment]
@lrslima There was an issue starting the Windows Service as part of the installation.

Please try it again as it may be an intermittent issue. If it reoccurs, please try installing not as a Windows Service and starting `elasticsearch.exe` manually and let me know if that works. 

Thanks!

**Comment by lrslima** [comment]
Thanks @russcam 

It worked!

**Comment by russcam** [comment]
@lrslima did it work, 

1. starting as a Windows Service?
2. or did you need to install *not starting* the Windows Service as part of the installation?

**Comment by lrslima** [comment]
@russcam 

Option 2, but I don't know why.
