### ISSUE TITLE
[DOCS]: Quiet installation instructions appear in git readme, but not official docs

### ISSUE THREAD

**Issue by seang-es** [elastic/windows-installers#119]
Specifically this section: https://github.com/elastic/windows-installers/#installing-from-the-command-line

Does not appear in https://www.elastic.co/guide/en/elasticsearch/reference/5.6/zip-windows.html

**Comment by russcam** [comment]
@seang-es Were you looking for

https://www.elastic.co/guide/en/elasticsearch/reference/5.6/windows.html#install-msi-command-line

**Comment by russcam** [comment]
@seang-es are you happy for me to close this? I believe you've linked to the zip archive instructions page rather than the msi instructions

**Comment by russcam** [comment]
closing this as the quiet install instructions are in the docs.
