### ISSUE TITLE
Error Occured during installlation of Elasticsearch version 5.6.3.

### ISSUE THREAD

**Issue by pmitra01** [elastic/windows-installers#124]

**Comment by russcam** [comment]
@pmitra01 Do you have [the MSI log and Elasticsearch log (if applicable)](https://github.com/elastic/windows-installers#reporting-problems)?

**Comment by pmitra01** [comment]
I fixed the issue. Thanks!

**Comment by russcam** [comment]
What was the issue, would you mind sharing how you solved it? May help others in the future with a similar problem. Thanks!

**Comment by pmitra01** [comment]
Hi, sure! It had to do with the settings file, where I had to change the
port number.
After that, it was all good.
Thanks for the follow up!

**Comment by pmitra01** [comment]
I realise I have you a very brief response. I am currently traveling and
without my laptop, so unable to tell you which configuration settings file
it was. But hopefully it might point you in the correct direction.
If you need, I shall elaborate when I manage to access my laptop in a day
or two.
