### ISSUE TITLE
Specify a license file to apply when starting Elasticsearch as part of installation

### ISSUE THREAD

**Issue by russcam** [elastic/windows-installers#126]
From conversation on  #99, provide the ability to upload a license file when choosing the install Elasticsearch as a service and start as part of installation.

**Comment by russcam** [comment]
If the license is one that allows X-Pack Security to be enabled, then the ability to also specify certs to use for the transport and http should also be provided. If no transport cert is provided, a self signed one should be generated (as it's required).

**Comment by ygel** [comment]
I noted this to be looked at.
