### ISSUE TITLE
WaitForStart should be configurable

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/windows-installers#127]
https://github.com/elastic/windows-installers/blob/b6efe197cb50ab308250edb3eca426560315f620/src/ProcessHosts/Elastic.ProcessHosts/Process/ObservableProcess.cs#L20

**Comment by russcam** [comment]
@Mpdreamz I think this can be closed now?

**Comment by Mpdreamz** [comment]
yep!

**Comment by Mpdreamz** [comment]
For reference `WaitForStarted` is now only a soft wait to get a confirmed started state after the installation finishes. This allows the installer to display a open in browser display after the installation finishes which aides new users. If we don't start before this timeout the installation will succeed but the link won't appear.
