### ISSUE TITLE
Don't delete data, config and log directories on uninstall

### ISSUE THREAD

**Issue by russcam** [elastic/windows-installers#132]

**Comment by bis42** [comment]
I had this problem when trying to upgrade from elastic5. I selected some plugings requireing JAVA_HOME to be set correctly, which was not the case on my machine (automated upgrades did delete older jre, but did not update JAVA_HOME). The error from a failed plugin installation resulted in an uninstall and deleted the existing data, config and log directories unintentionally. 
This was a small test site and I had backups, but this behaviour could cause serious data loss in big production sites.
