### ISSUE TITLE
Installed version INSTALLDIR determined from process Environment Variable

### ISSUE THREAD

**Issue by russcam** [elastic/windows-installers#138]
The currently installed version `INSTALLDIR` should not use the intaller process's `ES_HOME` environment but should use the `ES_HOME` environment variable of the `elasticsearch.exe` process, if running. This is because the installer process' environment variable value is inherited from its parent process, which may contain a different value to the current state of the `elasticsearch.exe` process.

the .NET APIs do not expose an implementation to read the environment variables of another process, but [it is possible using Windows APIs](https://blog.gapotchenko.com/eazfuscator.net/reading-environment-variables)

**Comment by russcam** [comment]
Similarly, the currently installed `CONFIGDIRECTORY` should also inspect the value from the `elasticsearch.exe` process, if running.

**Comment by codebrain** [comment]
@russcam - I remember a large number of changes going in (version specific install dirs, using wix actions, #141 ). Can we safely close this issue out now?
