### ISSUE TITLE
Detecting type of license when upgrading from 5.x -> 6.0

### ISSUE THREAD

**Issue by russcam** [elastic/windows-installers#139]
When upgrading from 5.x -> 6.0, the installer should detect the type of license currently installed so that the correct type of license is applied when upgrading.

With the current implementation, when upgrading to 6.0 from 5.6.4 with X-Pack installed

1. the UI defaults to a Basic license
2. `ElasticsearchSetBootstrapPasswordAction` determines that no `BOOTSTRAPASSWORD` property has been passed, so a 20 character random password is generated and added to the keystore
3. `ElasticsearchConfigurationAction` sets `xpack.license.self_generated.type: basic` in elasticsearch.yml
4. The license applied from 5.6.4 is carried over to 6.0

The end result can mean that a user is unable to authenticate with Elasticsearch 6.0 if 5.6.4 was installed with a trial license.

**Comment by ygel** [comment]
We're on 7.x closing in on 8.x, licensing changed as well.
