### ISSUE TITLE
Error Occurred during Upgrade Installation  from ES 5.5.1 to 5.6.3 thru Window MSI

### ISSUE THREAD

**Issue by sandeep-developer** [elastic/windows-installers#147]
Error Occurred during Upgrade Installation  from ES 5.5.1 to 5.6.3 thru Window MSI and on 5.5.1 SearchGuard enabled

**Comment by russcam** [comment]
[Please can you attach the installation log.](https://github.com/elastic/windows-installers#reporting-problems) Without this, it's impossible to diagnose what the issue might be. Thanks

**Comment by russcam** [comment]
Closing this as no additional details attached. Please feel free to attach further details and reopen @sandeep-developer 👍
