### ISSUE TITLE
An error occured during installation!

### ISSUE THREAD

**Issue by Kierian** [elastic/windows-installers#149]
Error Occurred during installation from ES 5.6.3 thru Window MSI 

help plz..
[error.txt](https://github.com/elastic/windows-installers/files/1550027/error.txt)

**Comment by russcam** [comment]
The error is installing Elasticsearch as a Windows Service:

> Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallServiceTask: Installing Elasticsearch service
> Service Configuration:
> - Name = Elasticsearch
> - DisplayName = Elasticsearch
> - StartMode = Automatic
> - ServiceAccount = User
> - UserName = elastic
> - Password = True
> - EventLogSource = Elasticsearch
> - HomeDirectory = E:\Program Files\Elastic\Elasticsearch\
> - ConfigDirectory = E:\Program Files\Elastic\Elasticsearch\config
> - ExeLocation = E:\Program Files\Elastic\Elasticsearch\bin\elasticsearch.exe
> 
> [0] installing installing
> System.InvalidOperationException: The installation failed, and the rollback has been performed. ---> System.ComponentModel.Win32Exception: 계정 이름과 보안 식별자 사이에 매핑이 이루어지지 않았습니다
>    at System.ServiceProcess.ServiceProcessInstaller.GetAccountSid(String accountName)
>    at System.ServiceProcess.ServiceProcessInstaller.Install(IDictionary stateSaver)
>    at System.Configuration.Install.Installer.Install(IDictionary stateSaver)
>    at Elastic.Installer.Domain.Configuration.Service.ServiceInstallationManager.Install(IDictionary stateSaver)
>    at System.Configuration.Install.Installer.Install(IDictionary stateSaver)
>    at System.Configuration.Install.TransactedInstaller.Install(IDictionary savedState)
>    --- End of inner exception stack trace ---
>    at System.Configuration.Install.TransactedInstaller.Install(IDictionary savedState)
>    at Elastic.Installer.Domain.Configuration.Service.ServiceInstallationManager.RuntimeInstall(ServiceConfiguration configuration)
>    at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallServiceTask.ExecuteTask()
>    at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
> CustomAction ElasticsearchServiceInstallAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

The `elastic` user account under which to install and run the service does not map to a known security identifier on the system. Does the `elastic` account exist?

**Comment by Kierian** [comment]
Your advice is perfect.
