### ISSUE TITLE
### Failed Installations

### ISSUE THREAD

**Issue by AhluwaliaPranjal** [elastic/windows-installers#157]
### Environment
Windows
NO
INDIA

### 3. Steps to reproduce the behaviour

Fresh install
1.NO
2.YES
3.Double click MSi file

**Comment by AhluwaliaPranjal** [comment]
[MSI1bdfc.LOG](https://github.com/elastic/windows-installers/files/1643494/MSI1bdfc.LOG)

**Comment by russcam** [comment]
@AhluwaliaPranjal, The log indicates
```
MSI (s) (A0:B4) [21:19:21:676]: Product: Elasticsearch 6.1.1 -- Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.
```

This is the same issue as #155. I'm going to close this issue to collect all details on that issue. If you'd like to try the details contained in that issue and report back there, that would really help.

Thanks for reporting 👍
