### ISSUE TITLE
An Error occurred during installation Elasticsearch 6.1.3

### ISSUE THREAD

**Issue by bintysyl** [elastic/windows-installers#165]
Environment
Windows 7 Laptop
Java 64 bit version 9.0.4

Expected Behaviour
To be able to install Elasticsearch

Actual Behaviour
Getting error 'Error occurred during installation'

Steps to reproduce the behaviour
Download .msi package
Use default directoires > Next > Do not install as a service > Next > Next > tick X-Pack > Next > Install >
[MSIe4ee0.LOG](https://github.com/elastic/windows-installers/files/1703338/MSIe4ee0.LOG)

Says it is installing then gives the error ' Error occurred during installation.'
I have also pointed my Java_home to the new version of Java that I had installed in this process.

This is a fresh install
I have installed newest version of Java 9 64 bit.

**Comment by russcam** [comment]
@bintysyl Thanks for reporting. Looking at the log, the error is related to access denied exception when installing the X-Pack plugin:

> Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask: Installing Elasticsearch plugins
> [0] installing x-pack installing x-pack
> System.ComponentModel.Win32Exception (0x80004005): Accès refusé
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.InvokeProcess(Process process, DataReceivedEventHandler processOnOutputDataReceived)
>    at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
>    at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
>    at Elastic.InstallerHosts.Tasks.InstallationTaskBase.Execute()
>    at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
> CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
> Action ended 15:00:09: InstallFinalize. Return value 3.

Would you be able to try the installation again, using latest Java 8 64 bit?

**Comment by Mpdreamz** [comment]
Closing this as we have not enough information to reproduce. Feel free to reopen.
