### ISSUE TITLE
An error occured during installation

### ISSUE THREAD

**Issue by jacquesjacques** [elastic/windows-installers#170]
[MSIc8e4a.LOG](https://github.com/elastic/windows-installers/files/1772784/MSIc8e4a.LOG)

### Environment
processor    intel i5
ram             8gb
os              windows 7
### Steps to reproduce the behaviour

1. fresh install
2.installer    elasticsearch-5.5.0.msi
3.

**Comment by razzul** [comment]
Incorrect **JAVA_HOME**. 
remove /bin from **JAVA_HOME** 
Should be: `C:\ProgramData\Java\jdk1.8.0_131`

**Comment by russcam** [comment]
@jacquesjacques The operation timed out waiting for the service to start as part of the installation:

> [0] waiting to start waiting to start
> [0] waiting to start waiting to start
> [0] waiting to start waiting to start
> System.ServiceProcess.TimeoutException: Timeout has expired and the operation has not been completed in 00:01:00.
>    at Elastic.Installer.Domain.Configuration.Service.ServiceStateProvider.StartAndWaitForRunning(TimeSpan timeToWait, Int32 totalTicks)
>    at Elastic.InstallerHosts.Elasticsearch.Tasks.StartServiceTask.ExecuteTask()
>    at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
> CustomAction ElasticsearchServiceStartAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

Since this is the same issue as #135, I'm closing in favour of tracking on that issue. Thanks for raising :+1:

**Comment by nakulkundra** [comment]
Check if you are running it as an administrator, and secondly if nothing works, dont install it as service and try to install it standalone , so that you can start it as and when required. it should work .
