### ISSUE TITLE
Issue while installation

### ISSUE THREAD

**Issue by apocalypse27** [elastic/windows-installers#176]
I have WIndows & PC with 4GB RAM and trying to install Elasticsearch in a drive with 100GB free space. I am getting the following error while installing. I previously tried to install deselecting to install it as a service, it got installed correctly, but did not start.

System.ServiceProcess.TimeoutException: Timeout has expired and the operation has not been completed in 00:01:00.
   at Elastic.Installer.Domain.Configuration.Service.ServiceStateProvider.StartAndWaitForRunning(TimeSpan timeToWait, Int32 totalTicks)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.StartServiceTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchServiceStartAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 17:38:31: InstallFinalize. Return value 3.
MSI (s) (64:74) [17:38:32:173]: User policy value 'DisableRollback' is 0
MSI (s) (64:74) [17:38:32:192]: Machine policy value 'DisableRollback' is 0
MSI (s) (64:74) [17:38:33:261]: Executing op: Header(Signature=1397708873,Version=500,Timestamp=1283886195,LangId=1033,Platform=589824,ScriptType=2,ScriptMajorVersion=21,ScriptMinorVersion=4,ScriptAttributes=1)
MSI (s) (64:74) [17:38:33:261]: Executing op: DialogInfo(Type=0,Argument=1033)
MSI (s) (64:74) [17:38:33:263]: Executing op: DialogInfo(Type=1,Argument=Elasticsearch 5.5.3)
MSI (s) (64:74) [17:38:33:385]: Executing op: RollbackInfo(,RollbackAction=Rollback,RollbackDescription=Rolling back action:,RollbackTemplate=[1],CleanupAction=RollbackCleanup,CleanupDescription=Removing backup files,CleanupTemplate=File: [1])
MSI (s) (64:74) [17:38:34:220]: Executing op: ActionStart(Name=ElasticsearchServiceStartAction,,)
MSI (s) (64:74) [17:38:34:225]: Executing op: ProductInfo(ProductKey={1F75DCE6-5C9E-43C4-AD23-72D94BFEC22D},ProductName=Elasticsearch 5.5.3,PackageName=elasticsearch-5.5.3.msi,Language=1033,Version=84213763,Assignment=1,ObsoleteArg=0,ProductIcon=app_icon.ico,,PackageCode={3D8E0C72-3737-4663-9EF0-148051B781C6},,,InstanceType=0,LUASetting=0,RemoteURTInstalls=0,ProductDeploymentFlags=3)
MSI (s) (64:74) [17:38:34:300]: Executing op: ActionStart(Name=ElasticsearchRollbackServiceStartAction,,)
MSI (s) (64:74) [17:38:34:372]: Executing op: CustomActionRollback(Action=ElasticsearchRollbackServiceStartAction,ActionType=11521,Source=BinaryData,Target=**********,CustomActionData=**********)
MSI (s) (64:04) [17:38:34:502]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI8659.tmp, Entrypoint: ElasticsearchRollbackServiceStart
SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSI8659.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Rollback.ElasticsearchRollbackServiceStartAction.ElasticsearchRollbackServiceStart
Trying to execute StopServiceTask seeing service: True
Elastic.InstallerHosts.Elasticsearch.Tasks.StopServiceTask: Stopping existing Elasticsearch service
[0] stopped stopped
MSI (s) (64:74) [17:39:33:571]: Executing op: ActionStart(Name=ElasticsearchServiceInstallAction,,)
MSI (s) (64:74) [17:39:33:580]: Executing op: ActionStart(Name=ElasticsearchRollbackInstallServiceAction,,)
MSI (s) (64:74) [17:39:33:585]: Executing op: CustomActionRollback(Action=ElasticsearchRollbackInstallServiceAction,ActionType=11521,Source=BinaryData,Target=**********,CustomActionData=**********)

**Comment by Mpdreamz** [comment]
Closing this as we do not have enough information and we believe `6.2.3` should have this fixed. Feel free to reopen.
