### ISSUE TITLE
"An error ocurred during installation v.6.2.3"

### ISSUE THREAD

**Issue by anapbrandao** [elastic/windows-installers#177]
error during installation on 10 with java 8.1.0_161 already installed 
The installation log file is too long, i can´t paste in here.
[MSId1585.LOG](https://github.com/elastic/windows-installers/files/1895240/MSId1585.LOG)

![image](https://user-images.githubusercontent.com/37863641/38566790-f0413472-3cba-11e8-9d24-6dce98d3e413.png)
![image](https://user-images.githubusercontent.com/37863641/38566798-f630811c-3cba-11e8-8e93-6fe8a2806e62.png)

**Comment by russcam** [comment]
@anapbrandao can you run the following in C:\dev\tools\elasticsearch-6.2.3\bin
```bat
elasticsearch --java-home
```
and report what it returns?

**Comment by kuruzuke** [comment]
i have the same error and also run the script that you gave.

**Comment by russcam** [comment]
what was the output from running  `elasticsearch --java-home` @kuruzuke ?

**Comment by codebrain** [comment]
Closing as OP has not responded,
