### ISSUE TITLE
MSI installer 6.3.0 - reset Notice page does not reset all elements

### ISSUE THREAD

**Issue by pheyos** [elastic/windows-installers#182]
**Found in version**
6.3.0-SNAPSHOT

**Steps to reproduce**
- Start the MSI installer with an older version already installed on the system
- Remember the state of the Notice page [1]
- Uncheck the `Start the service [...]` checkbox
 - Click the `Reset this step to its original state` button

**Expected result**
- The Notice page is reset to the original state [1]

**Actual result**
- The original state is not restored completely, see [2]

**Additional information**
- Original state [1]:
  ![msi_upgrade_original](https://user-images.githubusercontent.com/1945390/38942905-5a384584-4330-11e8-9669-6eee819422b0.png)
- State after reset [2]:
  ![msi_upgrade_reset](https://user-images.githubusercontent.com/1945390/38942921-64c4a11e-4330-11e8-9773-4259d7e1e920.png)

**Comment by Mpdreamz** [comment]
fixed in #183
