### ISSUE TITLE
An error occured during installation

### ISSUE THREAD

**Issue by sratha** [elastic/windows-installers#188]
### Environment
Running behind a corporate proxy

### Expected Behaviour
it should install elastic serach. I have java 1.8 in path var.
### Actual Behaviour
it's not installating
### Steps to reproduce the

 behaviour
[MSI9adae.LOG](https://github.com/elastic/windows-installers/files/1947273/MSI9adae.LOG)

1.fresh install
2.
3.

**Comment by russcam** [comment]
@sratha It looks like you didn't specify the details for the corporate proxy on the Plugins screen:

<img width="675" alt="screenshot 2018-05-02 11 12 27" src="https://user-images.githubusercontent.com/208231/39500719-de27337c-4df9-11e8-9d7d-ddf479bc5f8a.png">

then enter the details for the proxy to allow plugins to be downloaded from artifacts.elastic.co

<img width="675" alt="screenshot 2018-05-02 11 12 34" src="https://user-images.githubusercontent.com/208231/39500723-e62f108a-4df9-11e8-8209-a314a2388fa8.png">

**Comment by codebrain** [comment]
Closing as OP has not responded.
