### ISSUE TITLE
MSI - minimum master node field sometimes doesn't update value

### ISSUE THREAD

**Issue by pheyos** [elastic/windows-installers#192]
**Found in version**
- 6.3.0-bc2

**Steps to reproduce**
- In the Configuration page click the `+` button (one or multiple times) for the field `Minimum  master nodes`
- Set the focus into the field
- Press and release the CTRL key once
- Change the value using the `+` and `-` buttons

**Expected result**
- The value changes correctly

**Actual result**
- The displayed value doesn’t change any more, except when internally reaching the value `0` in which case the field is empty again. So in the background the value seems to be counted correctly.

**Additional information**
- Example scenario: Select the field value and CTRL+C / CTRL+V it
- When using the (mouse) context menu copy / paste options, it works

**Comment by russcam** [comment]
Is this the same as #83?

**Comment by codebrain** [comment]
Displays similar behious to #83, tempted to track both of these in the same fix.

**Comment by codebrain** [comment]
There seem to be a number of open issues against this particular library:
https://github.com/MahApps/MahApps.Metro/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+NumericUpDown

Suggest we maybe consider using a different library here? @russcam ?

**Comment by codebrain** [comment]
Actually, we ought to consider upgrading as we are using version `1.1.2` and the latest is `1.6.4`
https://www.nuget.org/packages/MahApps.Metro/

**Comment by codebrain** [comment]
This bug is fixed with upgrade to `1.6.4` but license dialog is then broken, along with window controls.

Attempted to upgrade to `1.2.0` through to `1.6.4` and all versions in this range affect the license dialog.

Suggest either a change to the UI to not rely on the `StringFormat` property on the `NumericUpDown` control or an upgrade to `1.6.4` and a revision of the rest of the UI.

@russcam @Mpdreamz - thoughts?

**Comment by codebrain** [comment]
Added `enhancement` label as to fix this problem we need to update a UI dependancy to the latest version and this breaks other features of the UI.
