### ISSUE TITLE
MSI - defer user setup with auto start service

### ISSUE THREAD

**Issue by pheyos** [elastic/windows-installers#193]
**Found in version**
- 6.3.0-bc2

**Steps to reproduce**
- Leave the Service page with standard values (install as a service with local system account, start after installation)
- In the X-Pack page select the Trial license
- Check the box `Defer setting up users until later`

**Expected result**
- Open to discussion, see `Actual result` below.

**Actual result**
- The explanation text says:
```Elasticsearch built-in users need to be setup manually. Either you are not installing as a service that gets started after installation, or you've opted to start Elasticsearch manually when needed.```
But both conditions are false in this scenario.
- From my point of view this should either result in a validation error or the explanation text should be changed.

**Additional information**
- When changing back to the Service page, un-checking and re-checking the `start after installation` field, the X-Pack page is changed and requires now the user passwords (showing a validation error, because they are empty). This seems to be correct behaviour.

**Comment by russcam** [comment]
I think the description just needs to be better here

**Comment by codebrain** [comment]
I think the second part of the text: `Either you are not installing as a service that gets started after installation, or you've opted to start Elasticsearch manually when needed.` is redundant - the user knows what they have done.

Will remove this text and elaborate on how to setup users manually.
