### ISSUE TITLE
MSI - Configure ML node role

### ISSUE THREAD

**Issue by pheyos** [elastic/windows-installers#194]
During the installation process it is currently possible to define a single node role or a set of node roles (`master`, `data`, `ingest` and implicitly `coordinating only` by deselecting all others).

There is another node role which is currently not covered by this configuration: `ML`. By default all nodes are ML nodes (with non-basic X-Pack license), so this doesn't block ML usage, but this means the `coordinating only` setup is actually `coordinating + ML`.

It would be good to have the option of defining a `Machine Learning only` node and a real `coordinating only` node.

This might be tricky, because it has interdependencies with the X-Pack license configuration.

**Comment by russcam** [comment]
> This might be tricky, because it has interdependencies with the X-Pack license configuration.

We discussed previously about including the ML node role and this was one of the reasons that we decided not to expose it in the UI at the time.

**Comment by ygel** [comment]
I noted this to be looked at.
