### ISSUE TITLE
installation failed with message

### ISSUE THREAD

**Issue by panirajn** [elastic/windows-installers#211]
An error occurred during installation !
ElasticSearch 6.3.1

### Steps to reproduce the behaviour

1.
2.
3.

**Comment by ashokchakravarti** [comment]
Steps
Run MSI installer
select the option to manually start ElasticSearch
Uncheck all plugins ( do not install any plugins)
Start installation
![elasticsearchissue](https://user-images.githubusercontent.com/31315096/43139903-37a3b250-8f53-11e8-8872-e9b23af0515c.jpg)

Attach are the installation logs.
[InstallationLogs.txt](https://github.com/elastic/windows-installers/files/2223776/InstallationLogs.txt)

Thanks

**Comment by russcam** [comment]
Thanks for opening

> Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Install.ElasticsearchBootstrapPasswordAction.ElasticsearchBootstrapPassword
> System.ComponentModel.Win32Exception (0x80004005): Access is denied
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetBootstrapPasswordTask.ExecuteTask()
>    at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)

Looks to be an issue with setting the bootstrap password. Will need to investigate

**Comment by ashokchakravarti** [comment]
Hi Martin,

It's Windows 7 Enterprise.
It works for me when I download the tar file.

Thanks
Ashok Chakravarti
________________________________

**Comment by xpsserver** [comment]
I just experienced the same issue and i can't seem to resolve it. 

Log file attached
[Installation Log Files.txt](https://github.com/elastic/windows-installers/files/2233831/Installation.Log.Files.txt)

**Comment by russcam** [comment]
@xpsserver Yours is not the same issue or version;

> Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetupXPackPasswordsTask: Setting up X-Pack passwords
[0] Checking Elasticsearch is up and running Checking Elasticsearch is up and running
[0] Checking Elasticsearch is up and running Checking Elasticsearch is up and running
[0] Elasticsearch is up and running Elasticsearch is up and running
[0] Changing password for 'elastic' Changing password for 'elastic'
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetupXPackPasswordsTask.SetPassword(HttpClient client, String elasticUserPassword, String user, String password)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetupXPackPasswordsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchSetupXPackPasswordsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 18:52:49: InstallFinalize. Return value 3.

You're also using 6.3.2 installer. Could you please open a new issue with the details requested for a new issue (you'll see them when entering a new issue)

**Comment by russcam** [comment]
@ashokchakravarti Could you check that the user running the installation has an environment variable named `%TMP%` set i.e. what does the following return in command prompt?

```bat
echo %TMP%
```

**Comment by codebrain** [comment]
Closing due to no response.

**Comment by mfazul** [comment]
I am also facing same issue and echo %TMP% is set as C:\Users\CSS117~1.CSS\AppData\Local\Temp

**Comment by mfazul** [comment]
Please provide the solution.

**Comment by mfazul** [comment]
Invoking remote custom action. DLL: C:\Windows\Installer\MSIEDC4.tmp, Entrypoint: ElasticsearchBootstrapPassword
SFXCA: Extracting custom action to temporary directory: C:\Windows\Installer\MSIEDC4.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Install.ElasticsearchBootstrapPasswordAction.ElasticsearchBootstrapPassword
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetBootstrapPasswordTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchBootstrapPasswordAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
