### ISSUE TITLE
Installation issue 6.3.2

### ISSUE THREAD

**Issue by svangeti** [elastic/windows-installers#215]
### SI (s) (04:F8) [18:34:15:333]: Note: 1: 2205 2:  3: Error 
MSI (s) (04:F8) [18:34:15:334]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1920 
MSI (c) (90:A0) [18:34:15:338]: EEUI - Invalid return value 1 for message type 16777221.
MSI (c) (90:A0) [18:34:15:338]: EEUI - Embedded UI Handler returned ERROR_INSTALL_FAILURE
Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.
MSI (s) (04:F8) [18:34:15:339]: Note: 1: 2205 2:  3: Error 
MSI (s) (04:F8) [18:34:15:339]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (s) (04:F8) [18:34:15:339]: Product: Elasticsearch 6.3.2 -- Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.

Action ended 18:34:15: InstallFinalize. Return value 3.

### Steps to reproduce the behaviour

1. Fresh Install
2. Run msi with plugins
3.

![image](https://user-images.githubusercontent.com/22736425/43169856-9ffbb934-8f70-11e8-8f2c-e47f4ef8f8b7.png)

**Comment by russcam** [comment]
> Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start. Verify that you have sufficient privileges to start system services.

This is usually indicative of an Environmental issue. Could you please attach the complete MSI log, and details of your environment.

**Comment by russcam** [comment]
@KnightCoder the error in your case is different:

> [0] Changing password for 'elastic' Changing password for 'elastic'
> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
>    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
>    at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetupXPackPasswordsTask.SetPassword(HttpClient client, String elasticUserPassword, String user, String password)
>    at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetupXPackPasswordsTask.ExecuteTask()
>    at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)

Could you please open a separate issue and include all of the details requested in the input, including attaching the complete MSI log. Thanks!

**Comment by KnightCoder** [comment]
UPDATE: 
I tried installing ElasticSearch v6.3.2, only this time I selected "Defer setting up users until later" and so did not set users passwords and it worked for me. I was able to successfully complete the installation.

**Comment by svangeti** [comment]
I re-installed same and this time it worked.
