### ISSUE TITLE
installer for ODBC driver

### ISSUE THREAD

**Issue by bpintea** [elastic/windows-installers#218]
The ODBC driver is comprised of a set of shared libraries (the driver itself and dependencies) that require installation on the target system.
It also requires a few bits of configuration asked from the user.

[This document](https://docs.google.com/document/d/1t9ImrgaXV6Ysl7j8eBYyoVzjHpTBLJHmyJ0lB4qB9Nw) covers a first set of requirements.
This issue would serve as a meta, tracking the requirements to be split from that doc.

**Comment by bpintea** [comment]
Updated the document with a link to an installer command-line example application and an API higher level proposition.

**Comment by sophiec20** [comment]
Closing as being tracked elsewhere.
