### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by Bilalzeaiter** [elastic/windows-installers#223]
### Expected Behaviour
Elastic Search
### Steps to reproduce the behaviour
just install elastic search

fresh install

Dear all,
during the installation an Error is occured. This is a bad start, because I would like to understand elastic search without having trouble installing it. could you please help me

![image](https://user-images.githubusercontent.com/42094116/43677578-4da14892-9804-11e8-9d0e-d29bbe2d9dc1.png)

**Comment by srinivasulurao** [comment]
This is the error which i was getting while installing the elastic search.

**Comment by russcam** [comment]
@Bilalzeaiter please can you follow the instructions provided in the text input when opening an issue about failed installation e.g. details about the environment and the MSI install log. Thanks!

**Comment by russcam** [comment]
Thanks for reporting back @Bilalzeaiter. Closing this issue
