### ISSUE TITLE
6.4 elasticsearch install on windows 10 failed

### ISSUE THREAD

**Issue by azizemna** [elastic/windows-installers#227]
[elasticsearch.log](https://github.com/elastic/windows-installers/files/2351539/elasticsearch.log)
[InstallLOg.txt](https://github.com/elastic/windows-installers/files/2351540/InstallLOg.txt)

### Environment
Windows 10 x64
i tried to install Elasticsearch 6.4 with Windows MSI Installer
No proxy
From Tunisia

### Steps to reproduce the behaviour

fresh install
1.
2.
3.

**Comment by codebrain** [comment]
The `InstallLog.txt` indicates an attempted install of `6.4.0` but the `elasticsearch.log` indicates a `6.3.0` version.

Is this an upgrade or a fresh install?

**Comment by azizemna** [comment]
I have installed before 6.3 but I uninstalled it to install 6.4

**Comment by codebrain** [comment]
I am seeing a few problems here in the logs:

Line 3319: `could not find java; set JAVA_HOME or ensure java is in PATH `

Line 3344: `Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.`

Please ensure that you have the correct version of Java installed and that is in your environment variables path. Please also ensure you have the correct system rights to start Windows Services.

**Comment by azizemna** [comment]
Thank you very much. It worked for me
