### ISSUE TITLE
Environment variables "ES_HOME" and "ES_CONF_PATH" remain even after uninstall via msi

### ISSUE THREAD

**Issue by kunisen** [elastic/windows-installers#234]
### Environment
ES 6.2

### Expected Behaviour
Environment variables "ES_HOME" and "ES_CONF_PATH" gone after uninstall via msi

### Actual Behaviour
The above-mentioned environment variables remain.

### Steps to reproduce the behaviour
1. Fresh install via msi
2. Uninstall via msi

**Comment by kunisen** [comment]
Thanks for the quick pointers! Let me check it again if I did anything wrong in my steps! @russcam

**Comment by russcam** [comment]
I'm going to close this @kunisen as I can't reproduce it, and the MSI has the necessary entries in the Environment table to cleanup the relevant environment variables upon uninstall.
