### ISSUE TITLE
6.4.2 Can't find java from JAVA_HOME on Windows 10 

### ISSUE THREAD

**Issue by garymazz** [elastic/windows-installers#235]
Just tried 6.4.2 installer. It fails finding java from the environment variable. I have tried java 10.0.2 and 1.8.0_181 with same result.

Installer Log File:
[MSI7cf16.zip](https://github.com/elastic/windows-installers/files/2484800/MSI7cf16.zip)

Base Installation directory:
L:\Elastic\Elasticsearch

Config1:
JAVA_HOME=L:\Java\jdk-10.0.2
JRE_HOME=L:\Java\jre10.0.2

Config2:
JAVA_HOME=L:\Java\jdk1.8.0_181
JRE_HOME=L:\Java\jdk1.8.0_181\jre

Logged Error:
```
Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask: Installing Elasticsearch plugins
[0] installing ingest-attachment installing ingest-attachment
could not find java; set JAVA_HOME or ensure java is in PATH 
[0] installing ingest-attachment installing ingest-attachment
System.Exception: Execution failed (L:\Elastic\Elasticsearch\6.4.2\bin\elasticsearch-plugin.bat install ingest-attachment --batch). ExitCode: 1 ErrorCheck: True ErrorOut:could not find java; set JAVA_HOME or ensure java is in PATH 

   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.Installer.Domain.Configuration.Plugin.ElasticsearchPluginStateProvider.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 14:02:53: InstallFinalize. Return value 3.
```

**Comment by russcam** [comment]
@garymazz is `JAVA_HOME` set as

1. a process environment variable?
2. a user environment variable?
3. a system environment variable?

Looking at the MSI log, the initial check for Java in the installer passes on line 1116:

> ElasticsearchInstallationModel
> - IsValid = True
> - ValidationFailures = 
> - FirstInvalidStepValidationFailures = 
> - MsiLogFileLocation = C:\Users\user\AppData\Local\Temp\MSI7cf16.LOG
> - JavaInstalled = True
> - JavaMisconfigured = False
> - ConfigDirectoryIsSpecifiedAndSubPathOfEsHome = False
> - Using32BitJava = False
> - BadElasticsearchYamlFile = False
> NoticeModel
> - IsValid = True

The installation of plugins happens in a custom action, in a separate process, that runs with a different context to the initial check. Would you be able to set `JAVA_HOME` as a system envionment variable with the following PowerShell

```powershell
[Environment]::SetEnvironmentVariable("JAVA_HOME", "L:\Java\jdk1.8.0_181", "Machine")
``` 

Then try launching the installer again? I have another thought if this doesn't work, but let's rule this one out first.

**Comment by sourabhXIII** [comment]
Facing the same issue.
Got the .zip file for version 7.1.0. But .\bin\elasticsearch.bat throws
`"could not find java in JAVA_HOME or bundled at C:\Users\xxxxxx\Downloads\elasticsearch-7.1.0\jdk"`
