### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by eviluess** [elastic/windows-installers#237]
### Steps to reproduce the behaviour

1.
2.
3.

[MSI7412f.LOG](https://github.com/elastic/windows-installers/files/2509359/MSI7412f.LOG)

![image](https://user-images.githubusercontent.com/11187987/47412928-8a02a080-d79f-11e8-83a5-78f23f6ad1c3.png)

Note:
The Elasticsearch log file cannot be opened.
Only the installation log file is available for uploading.

**Comment by Mpdreamz** [comment]
It seems a timeout happened while installing the `ingest-attachment` plugin

```
[0] installing ingest-attachment installing ingest-attachment
Exception in thread "main" java.net.ConnectException: Connection timed out: connect
```
Possibly the machine can not reach the public URL for elasticsearch plugins? Please try installing without plugins and installing the plugins manually afterwards.

**Comment by Mpdreamz** [comment]
Forgot to thank you for the detailed response, thank you! 😄

**Comment by eviluess** [comment]
> It seems a timeout happened while installing the `ingest-attachment` plugin
> 
> ```
> [0] installing ingest-attachment installing ingest-attachment
> Exception in thread "main" java.net.ConnectException: Connection timed out: connect
> ```
> Possibly the machine can not reach the public URL for elasticsearch plugins? Please try installing without plugins and installing the plugins manually afterwards.

Thanks for your reply.

I tried to install the kuromoji (Japanese Parser) only and it still failed.
The log is attached below:
[MSI46309.LOG](https://github.com/elastic/windows-installers/files/2510287/MSI46309.LOG)

Note:
I watched the installation progress and I indeed saw it completed installing the kuromoji plug-in.
But it told me the installation is failed finally.
