### ISSUE TITLE
Unable to install/start elasticsearch service version 6.4.2 using msi installer

### ISSUE THREAD

**Issue by kaurranjeet12** [elastic/windows-installers#238]
### Environment
local machine
windows 10 
JAVA_HOME = "C:\Program Files (x86)\Java\jre1.8.0_191"
.Net Framework = 4.6.2

### Expected Behaviour
Installation should install the service and start the service automatically.

### Actual Behaviour
msi installer says installation completed but when I am trying to run the service from windows services it throws error that it cannot start the service. 

**Event Viewer shows following two errors:**

Application: elasticsearch.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.

Faulting application name: elasticsearch.exe, version: 6.4.2.0, time stamp: 0x5bab9b87
Faulting module name: KERNELBASE.dll, version: 10.0.14393.1770, time stamp: 0x59bf2ba6
Exception code: 0xe0434352
Fault offset: 0x0000000000033c58
Faulting process id: 0x4ff0
Faulting application start time: 0x01d46fdcdf17e000
Faulting application path: C:\Program Files\Elastic\Elasticsearch\6.4.2\bin\elasticsearch.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: d35dcdad-46af-43c7-8035-14c7cc113c25
Faulting package full name: 
Faulting package-relative application ID: 

### Steps to reproduce the behaviour

1. Its a fresh install.

**Comment by russcam** [comment]
Please can you share

1. the MSI install log.
2. any Elasticsearch logs from the configured Elasticsearch logs directory

**Comment by kaurranjeet12** [comment]
[MSIf2002.LOG](https://github.com/elastic/windows-installers/files/2530257/MSIf2002.LOG)

Hi susscam,

Thank you for replying back. I have attched the installation logs. Could not find elastic search log as it deletes the logs after unsuccessful installation.
I am also attaching the screenshot of the error its displaying at the end.

Thanks,
Ranjeet
![eserror](https://user-images.githubusercontent.com/10466212/47728949-8eeea680-dc1c-11e8-9d04-9c4260550214.png)

**Comment by russcam** [comment]
Looking at the error log, the `.\LocalSystem` account on your machine does not have sufficient privileges to start system services:


> MSI (s) (BC:5C) [08:08:57:311]: Executing op: ServiceInstall(Name=Elasticsearch,DisplayName=Elasticsearch,ImagePath="C:\Program Files\Elastic\Elasticsearch\6.4.2\bin\elasticsearch.exe",ServiceType=16,StartType=2,ErrorControl=32769,,Dependencies=[~],,StartName=**.\LocalSystem**,Password=**********,Description=You know, for Search.,,)
> MSI (s) (BC:5C) [08:08:57:311]: Executing op: ActionStart(Name=StartServices,Description=Starting Elasticsearch service,Template=Starting Elasticsearch service)
> MSI (s) (BC:5C) [08:08:57:311]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=1300000)
> MSI (s) (BC:5C) [08:08:57:311]: Executing op: ServiceControl(,Name=Elasticsearch,Action=1,Wait=1,)
> MSI (s) (BC:5C) [08:13:03:072]: Note: 1: 2205 2:  3: Error 
> MSI (s) (BC:5C) [08:13:03:072]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1920 
> MSI (c) (94:0C) [08:13:03:072]: EEUI - Invalid return value 1 for message type 16777221.
> MSI (c) (94:0C) [08:13:03:072]: EEUI - Embedded UI Handler returned ERROR_INSTALL_FAILURE
> Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.
> MSI (s) (BC:5C) [08:13:03:072]: Note: 1: 2205 2:  3: Error 
> MSI (s) (BC:5C) [08:13:03:072]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
> **MSI (s) (BC:5C) [08:13:03:072]: Product: Elasticsearch 6.4.2 -- Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.**

If you're using an organisation computer, it may be possible that there is group policy in place to prevent that account from starting services.

Please try using another account that has privileges to install and start services. Alternatively, try not installing as a service, and running elasticsearch.exe manually from the command line.
