### ISSUE TITLE
Logs directory should be created at ES_HOME for gc.log

### ISSUE THREAD

**Issue by henurah** [elastic/windows-installers#242]
### Environment
Windows Server 2016 GCP environment 
Oracle JDK 11
Do not install as a service (everything else kept at default)
Trial X-pack License
Elasticsearch 6.4.3

### Expected Behaviour
When starting Elasticsearch from the command line after a successful MSI install, ES should start.

### Actual Behaviour
When starting Elasticsearch from the command line after an MSI install, ES errors out saying invalid -Xlog option (no gc.log file can be created although this is relatively easily remedied by creating a logs directory in %ES_HOME%)

### Steps to reproduce the behaviour
1.  Fresh install using MSI via Powershell in adminstrative mode
2. Start Elasticsearch from Powershell command line

![image](https://user-images.githubusercontent.com/1744259/48403299-73869f80-e6e2-11e8-8b31-736c1fd1c464.png)

**Comment by henurah** [comment]
Looks like it's already been seen by others:  https://github.com/elastic/windows-installers/issues/228

Didn't see an open ticket, but feel free to close this if it's been resolved.

**Comment by sophiec20** [comment]
Passing on outcome of previous trouble shooting. 

> The gc log location is an argument to the JVM at startup and the log file location is not known at that point as the java code reads it from elasticsearch.yml some time later. But for an installer like MSI the log file location is set at install time so in theory you can rewrite the gc log argument to be the correct directory rather than the hard coded default.

**Comment by Mpdreamz** [comment]
Fixed by: https://github.com/elastic/windows-installers/pull/260
