### ISSUE TITLE
404 error on linked documentation page for setting up users manually

### ISSUE THREAD

**Issue by henurah** [elastic/windows-installers#243]
### Environment
Windows Server 2016 GCP environment 
Oracle JDK 11
Do not install as a service (everything else kept at default)
Trial X-pack License
Elasticsearch 6.4.3

### Expected Behaviour
When going through the MSI installation wizard, links should take you to current documentation.

### Actual Behaviour
When going through the MSI installation wizard, the link for setting up users manually on the X-pack tab when you select the Trial option from the drop-down takes you to a 404 web page.

### Steps to reproduce the behaviour

1.  Fresh install and upgrade too I'm guessing
2. Progress through the MSI wizard installation until the last X-pack tab and select the Trial option from the drop-down box to see the link.

![image](https://user-images.githubusercontent.com/1744259/48403720-5e5e4080-e6e3-11e8-9f05-d2c2b180b499.png)

**Comment by russcam** [comment]
Thanks for reporting @henurah, this is a bug. 

The correct link for 6.4 should be https://www.elastic.co/guide/en/elastic-stack-overview/6.4/built-in-users.html#set-built-in-user-passwords
