### ISSUE TITLE
Elasticsearch 6.6.0: EEUI - Call to InitializeEmbeddedUI on a UI DLL failed

### ISSUE THREAD

**Issue by mobamoba** [elastic/windows-installers#251]
### Environment

No

U.S.
### Expected Behaviour
Installation should work
### Actual Behaviour
Installation doesn't do anything
### Steps to reproduce the behaviour
Run msi

1.Upgrade
2.
3.

In the MSI log file, here's where the installer fails:

MSI (c) (E0:04) [08:42:00:035]: EEUI - Call to InitializeEmbeddedUI on a UI DLL failed

Nothing happens after that. Thanks.

**Comment by codebrain** [comment]
Would it be possible for you to upload your MSI installation log file?

https://www.elastic.co/guide/en/elasticsearch/reference/current/windows.html#install-msi-command-line

**Comment by mobamoba** [comment]
Sure here you go:

`=== Verbose logging started: 2/5/2019  8:41:56  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\WINDOWS\system32\msiexec.exe ===
MSI (c) (E0:94) [08:41:56:123]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (E0:94) [08:41:56:123]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (E0:04) [08:41:56:138]: Resetting cached policy values
MSI (c) (E0:04) [08:41:56:138]: Machine policy value 'Debug' is 0
MSI (c) (E0:04) [08:41:56:138]: ******* RunEngine:
           ******* Product: elasticsearch-6.6.0.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (E0:04) [08:41:56:140]: Machine policy value 'DisableUserInstalls' is 0
MSI (c) (E0:04) [08:41:56:148]: SOFTWARE RESTRICTION POLICY: Verifying package --> 'D:\Download\elasticsearch-6.6.0.msi' against software restriction policy
MSI (c) (E0:04) [08:41:56:149]: SOFTWARE RESTRICTION POLICY: D:\Download\elasticsearch-6.6.0.msi has a digital signature
MSI (c) (E0:04) [08:41:56:571]: SOFTWARE RESTRICTION POLICY: D:\Download\elasticsearch-6.6.0.msi is permitted to run at the 'unrestricted' authorization level.
MSI (c) (E0:04) [08:41:56:609]: Cloaking enabled.
MSI (c) (E0:04) [08:41:56:609]: Attempting to enable all disabled privileges before calling Install on Server
MSI (c) (E0:04) [08:41:56:612]: End dialog not enabled
MSI (c) (E0:04) [08:41:56:612]: Original package ==> D:\Download\elasticsearch-6.6.0.msi
MSI (c) (E0:04) [08:41:56:612]: Package we're running from ==> D:\Download\elasticsearch-6.6.0.msi
MSI (c) (E0:04) [08:41:56:614]: APPCOMPAT: Compatibility mode property overrides found.
MSI (c) (E0:04) [08:41:56:614]: APPCOMPAT: looking for appcompat database entry with ProductCode '{7590B87F-1147-4C0B-B565-7DAFC518AE7B}'.
MSI (c) (E0:04) [08:41:56:614]: APPCOMPAT: no matching ProductCode found in database.
MSI (c) (E0:04) [08:41:56:636]: MSCOREE not loaded loading copy from system32
MSI (c) (E0:04) [08:41:56:639]: Machine policy value 'TransformsSecure' is 0
MSI (c) (E0:04) [08:41:56:640]: User policy value 'TransformsAtSource' is 0
MSI (c) (E0:04) [08:41:56:640]: Machine policy value 'DisablePatch' is 0
MSI (c) (E0:04) [08:41:56:640]: Machine policy value 'AllowLockdownPatch' is 0
MSI (c) (E0:04) [08:41:56:640]: Machine policy value 'DisableLUAPatching' is 0
MSI (c) (E0:04) [08:41:56:640]: Machine policy value 'DisableFlyWeightPatching' is 0
MSI (c) (E0:04) [08:41:56:640]: APPCOMPAT: looking for appcompat database entry with ProductCode '{7590B87F-1147-4C0B-B565-7DAFC518AE7B}'.
MSI (c) (E0:04) [08:41:56:641]: APPCOMPAT: no matching ProductCode found in database.
MSI (c) (E0:04) [08:41:56:641]: Transforms are not secure.
MSI (c) (E0:04) [08:41:56:641]: Note: 1: 2205 2:  3: Control 
MSI (c) (E0:04) [08:41:56:641]: PROPERTY CHANGE: Adding MsiLogFileLocation property. Its value is 'D:\Download\elasticsearch.log'.
MSI (c) (E0:04) [08:41:56:641]: Command Line: CURRENTDIRECTORY=D:\Download CLIENTUILEVEL=0 CLIENTPROCESSID=14304 
MSI (c) (E0:04) [08:41:56:641]: PROPERTY CHANGE: Adding PackageCode property. Its value is '{BA164EEA-4827-4407-A8B1-AD343063644D}'.
MSI (c) (E0:04) [08:41:56:641]: Product Code passed to Engine.Initialize:           ''
MSI (c) (E0:04) [08:41:56:641]: Product Code from property table before transforms: '{7590B87F-1147-4C0B-B565-7DAFC518AE7B}'
MSI (c) (E0:04) [08:41:56:641]: Product Code from property table after transforms:  '{7590B87F-1147-4C0B-B565-7DAFC518AE7B}'
MSI (c) (E0:04) [08:41:56:641]: Product not registered: beginning first-time install
MSI (c) (E0:04) [08:41:56:641]: PROPERTY CHANGE: Adding ProductState property. Its value is '-1'.
MSI (c) (E0:04) [08:41:56:641]: Entering CMsiConfigurationManager::SetLastUsedSource.
MSI (c) (E0:04) [08:41:56:641]: User policy value 'SearchOrder' is 'nmu'
MSI (c) (E0:04) [08:41:56:641]: Adding new sources is allowed.
MSI (c) (E0:04) [08:41:56:641]: PROPERTY CHANGE: Adding PackagecodeChanging property. Its value is '1'.
MSI (c) (E0:04) [08:41:56:641]: Package name extracted from package path: 'elasticsearch-6.6.0.msi'
MSI (c) (E0:04) [08:41:56:641]: Package to be registered: 'elasticsearch-6.6.0.msi'
MSI (c) (E0:04) [08:41:56:641]: Note: 1: 2205 2:  3: Error 
MSI (c) (E0:04) [08:41:56:642]: Note: 1: 2262 2: AdminProperties 3: -2147287038 
MSI (c) (E0:04) [08:41:56:642]: Machine policy value 'DisableMsi' is 0
MSI (c) (E0:04) [08:41:56:642]: Machine policy value 'AlwaysInstallElevated' is 0
MSI (c) (E0:04) [08:41:56:642]: User policy value 'AlwaysInstallElevated' is 0
MSI (c) (E0:04) [08:41:56:642]: Product installation will be elevated because user is admin and product is being installed per-machine.
MSI (c) (E0:04) [08:41:56:642]: Running product '{7590B87F-1147-4C0B-B565-7DAFC518AE7B}' with elevated privileges: Product is assigned.
MSI (c) (E0:04) [08:41:56:642]: PROPERTY CHANGE: Adding CURRENTDIRECTORY property. Its value is 'D:\Download'.
MSI (c) (E0:04) [08:41:56:642]: PROPERTY CHANGE: Adding CLIENTUILEVEL property. Its value is '0'.
MSI (c) (E0:04) [08:41:56:642]: PROPERTY CHANGE: Adding CLIENTPROCESSID property. Its value is '14304'.
MSI (c) (E0:04) [08:41:56:642]: PROPERTY CHANGE: Adding MsiSystemRebootPending property. Its value is '1'.
MSI (c) (E0:04) [08:41:56:642]: TRANSFORMS property is now: 
MSI (c) (E0:04) [08:41:56:642]: PROPERTY CHANGE: Adding VersionDatabase property. Its value is '200'.
MSI (c) (E0:04) [08:41:56:643]: SHELL32::SHGetFolderPath returned: C:\Users\USERNAME\AppData\Roaming
MSI (c) (E0:04) [08:41:56:643]: SHELL32::SHGetFolderPath returned: C:\Users\USERNAME\Favorites
MSI (c) (E0:04) [08:41:56:643]: SHELL32::SHGetFolderPath returned: C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Network Shortcuts
MSI (c) (E0:04) [08:41:56:643]: SHELL32::SHGetFolderPath returned: C:\Users\USERNAME\Documents
MSI (c) (E0:04) [08:41:56:644]: SHELL32::SHGetFolderPath returned: C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Printer Shortcuts
MSI (c) (E0:04) [08:41:56:644]: SHELL32::SHGetFolderPath returned: C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Recent
MSI (c) (E0:04) [08:41:56:644]: SHELL32::SHGetFolderPath returned: C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\SendTo
MSI (c) (E0:04) [08:41:56:644]: SHELL32::SHGetFolderPath returned: C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Templates
MSI (c) (E0:04) [08:41:56:656]: SHELL32::SHGetFolderPath returned: C:\ProgramData
MSI (c) (E0:04) [08:41:56:656]: SHELL32::SHGetFolderPath returned: C:\Users\USERNAME\AppData\Local
MSI (c) (E0:04) [08:41:56:656]: SHELL32::SHGetFolderPath returned: C:\Users\USERNAME\Pictures
MSI (c) (E0:04) [08:41:56:656]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools
MSI (c) (E0:04) [08:41:56:656]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup
MSI (c) (E0:04) [08:41:56:656]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Start Menu\Programs
MSI (c) (E0:04) [08:41:56:657]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Start Menu
MSI (c) (E0:04) [08:41:56:657]: SHELL32::SHGetFolderPath returned: C:\Users\Public\Desktop
MSI (c) (E0:04) [08:41:56:657]: SHELL32::SHGetFolderPath returned: C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Administrative Tools
MSI (c) (E0:04) [08:41:56:657]: SHELL32::SHGetFolderPath returned: C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
MSI (c) (E0:04) [08:41:56:657]: SHELL32::SHGetFolderPath returned: C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
MSI (c) (E0:04) [08:41:56:657]: SHELL32::SHGetFolderPath returned: C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu
MSI (c) (E0:04) [08:41:56:658]: SHELL32::SHGetFolderPath returned: C:\Users\USERNAME\Desktop
MSI (c) (E0:04) [08:41:56:658]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Templates
MSI (c) (E0:04) [08:41:56:658]: SHELL32::SHGetFolderPath returned: C:\WINDOWS\Fonts
MSI (c) (E0:04) [08:41:56:659]: Note: 1: 2898 2: MS Sans Serif 3: MS Sans Serif 4: 0 5: 46 
MSI (c) (E0:04) [08:41:56:676]: MSI_LUA: Setting MsiRunningElevated property to 1 because the install is already running elevated.
MSI (c) (E0:04) [08:41:56:676]: PROPERTY CHANGE: Adding MsiRunningElevated property. Its value is '1'.
MSI (c) (E0:04) [08:41:56:676]: PROPERTY CHANGE: Adding Privileged property. Its value is '1'.
MSI (c) (E0:04) [08:41:56:676]: Note: 1: 1402 2: HKEY_CURRENT_USER\Software\Microsoft\MS Setup (ACME)\User Info 3: 2 
MSI (c) (E0:04) [08:41:56:676]: PROPERTY CHANGE: Adding USERNAME property. Its value is 'Windows User'.
MSI (c) (E0:04) [08:41:56:676]: Note: 1: 1402 2: HKEY_CURRENT_USER\Software\Microsoft\MS Setup (ACME)\User Info 3: 2 
MSI (c) (E0:04) [08:41:56:676]: PROPERTY CHANGE: Adding DATABASE property. Its value is 'D:\Download\elasticsearch-6.6.0.msi'.
MSI (c) (E0:04) [08:41:56:676]: PROPERTY CHANGE: Adding OriginalDatabase property. Its value is 'D:\Download\elasticsearch-6.6.0.msi'.
MSI (c) (E0:04) [08:41:56:676]: Machine policy value 'MsiDisableEmbeddedUI' is 0
MSI (c) (E0:04) [08:41:56:676]: EEUI - Running MsiEmbeddedUI code
MSI (c) (E0:34) [08:41:56:736]: Cloaking enabled.
MSI (c) (E0:34) [08:41:56:736]: Attempting to enable all disabled privileges before calling Install on Server
MSI (c) (E0:34) [08:41:56:736]: Connected to service for CA interface.
SFXCA: Extracting embedded UI to temporary directory: C:\Users\USERNAME\AppData\Local\Temp\MSI28153
SFXCA: Binding to CLR version v4.0.30319
MSI (c) (E0:04) [08:42:00:035]: EEUI - Call to InitializeEmbeddedUI on a UI DLL failed
`

**Comment by Mpdreamz** [comment]
@mobamoba what Windows version are you trying to install on?

**Comment by mobamoba** [comment]
Windows 10

**Comment by schubboy** [comment]
Happened to me as well.  Cannot install from the MSI on windows 10.  Interested to see what the response here is.

**Comment by ygel** [comment]
Closing due to old version and lack of activity.
