### ISSUE TITLE
Failed Installation of Elasticsearch 6.6 using Microsoft Installer Package

### ISSUE THREAD

**Issue by kramann** [elastic/windows-installers#252]
### Environment
Windows 10 Pro (version 1803), Surface Pro 4, 8GB RAM, 250GB hard disk, only about half used.
Oracle Java version 8, update 202.
[Elastic Install Fail Log.txt](https://github.com/elastic/windows-installers/files/2839438/Elastic.Install.Fail.Log.txt)

This was not running behind a corporate proxy.

I am based in the United States.

### Expected Behaviour
Installation should have completed successfully.

### Actual Behaviour
Install reported that it failed.

### Steps to reproduce the behaviour
Run the Microsoft installer.

This was a fresh install.

Installation log file attached.

**Comment by Mpdreamz** [comment]
The plugin command hit this bug:

https://github.com/elastic/elasticsearch/pull/38624

If `JAVA_HOME` is not set but `java.exe` is found on the path it will this bug. 

Thank you for reporting this @kramann closing this since this should be fixed when it gets fixed in Elasticsearch itself.

**Comment by Mpdreamz** [comment]
```

[0] installing ingest-attachment installing ingest-attachment
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\6.6.0\bin\elasticsearch-plugin.bat install ingest-attachment --batch). ExitCode: 255 ErrorCheck: True ErrorOut:\Common was unexpected at this time.
```

Relevant failure from installation log.
