### ISSUE TITLE
Support comma separated values and special values for network host

### ISSUE THREAD

**Issue by ivan-sam** [elastic/windows-installers#266]
### Environment
Windows Server 2012R2, Elasticsearch Windows Installer 6.6.1

### Expected Behaviour
Elasticsearch Windows Installer supports valid configuration setting values (supported by Elasticsearch) or reports a validation issue.

### Actual Behaviour
Installation fails. There's an error in Windows Application Event Log:
```
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetupXPackPasswordsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
```
Please note, that checking **Defer setting up users until later** allows to complete installation successfully, entered value for **Network host** is saved to elastic config.

An idea: as Windows Installer installs Elasticsearch **locally**, any value for **Network host** that is failed to be parsed may be handled the following way:
1. entered value for the field is preserved **as is** in config file (current behavior)
2. an attempt to fire X-Pack password set request should use localhost (and provided port) when entered value for **Network host** cannot be parsed as URI.

### Steps to reproduce the behaviour

Fresh install scenario

1. Launch Elasticsearch windows installer
2. Click **Next** on a first screen (**Locations**)
3. Click **Next** on a second screen (**Service**)
4. On a **Configuration** screen enter the value `_site_, _local_` for the **Network host**
5. Click **Next**
6. Click **Next** on a **Plugins**
7. Choose **Trial** license and fill in passwords for built-in users.
8. Proceed with installation.

![msi-2](https://user-images.githubusercontent.com/4918115/53423440-a62e7c80-39e1-11e9-8a3a-51c36cf3d45b.png)

**Comment by Mpdreamz** [comment]
fixed by #270 by @ivan-sam
