### ISSUE TITLE
Minimum master nodes setting value is not written to elasticsearch.yml

### ISSUE THREAD

**Issue by ivan-sam** [elastic/windows-installers#268]
### Environment
Windows Server 2012R2, Elasticsearch Windows Installer 6.6.1

### Expected Behaviour
Configured value of minimum master nodes is written to elasticsearch.yml on successful clean install

### Actual Behaviour
discovery.zen.minimum_master_nodes is not present in elasticsearch.yml on successful clean install

### Steps to reproduce the behaviour

Clean install
1. Launch installer.
2. On a **Configuration** page increase number of minimum master nodes to value **2**
3. Finish installation and open elasticsearch.yml

**Comment by Mpdreamz** [comment]
fixed in #269 by @ivan-sam 💯
