### ISSUE TITLE
Windows 10 6.4.0 MSI Install failure

### ISSUE THREAD

**Issue by kxc25612** [elastic/windows-installers#274]
5 Failed Installations

Windows 10 x64 Environment

[MSI57391.LOG](https://github.com/elastic/windows-installers/files/2971635/MSI57391.LOG)

**Comment by Mpdreamz** [comment]
> MSI (s) (D0:F8) [09:46:44:294]: Product: Elasticsearch 6.4.0 -- Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.

If you're using an organisation computer, it may be possible that there is group policy in place to prevent that account from starting services.

Please try using another account that has privileges to install and start services. Alternatively, try not installing as a service, and running elasticsearch.exe manually from the command line.
