### ISSUE TITLE
Windows 10 6.6.2 MSI Install failure

### ISSUE THREAD

**Issue by IamIC** [elastic/windows-installers#275]
Installation fails, even after uninstalling the current version. Log attached.
[elastic.log](https://github.com/elastic/windows-installers/files/2980608/elastic.log)

**Comment by draffy92** [comment]
I got the same problem even from .msi and CMD.

**Comment by Mpdreamz** [comment]
`System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\6.6.2\bin\elasticsearch-plugin.bat install ingest-attachment --batch). ExitCode: 255 ErrorCheck: True ErrorOut:\Common was unexpected at this time.`


This is currently a bug in  Elasticsearch itself see:

https://github.com/elastic/elasticsearch/pull/38624
https://github.com/elastic/elasticsearch/pull/33405

And for our own housekeeping: duplicate of: https://github.com/elastic/windows-installers/issues/252
