### ISSUE TITLE
ES MSI Enable security settings, license installation and TLS

### ISSUE THREAD

**Issue by jstrassb** [elastic/windows-installers#277]
Scenario:

Uninstalled previous Elasticsearch version and installed new `6.x` using the MSI installer.
Enable security on trial license did not work and so installation was done unsecured with a single node cluster.
Later two additional nodes were added to the unsecured cluster without a problem.

Once a production license was installed and security enabled the Elasticsearch services did not start up as encrypted communication between the nodes was not enabled and the bootstrap check failed accordingly (<https://www.elastic.co/guide/en/elasticsearch/reference/6.6/bootstrap-checks-xpack.html#bootstrap-checks-tls>).
After configuring TLS between the Elasticsearch nodes the cluster was working as expected.

It would also be nice to have [Specify a license file to apply when starting Elasticsearch as part of installation](https://github.com/elastic/windows-installers/issues/126) to be implemented so that a new node can be added to an existing cluster.
Having an option to specify the certificates used for encrypted TLS/SSL communication or create them during installation would be appreciated.

I also wonder if the security configuration during the setup phase did fail due to a previous Elasticsearch instance that had been installed on this system before.

**Comment by ygel** [comment]
I noted this to be looked at.
