### ISSUE TITLE
An error occured during installation! (elasticsearch 5.5.0)

### ISSUE THREAD

**Issue by sikhaarun** [elastic/windows-installers#279]
An error occured during installation elasticsearch-5.5.0.msi . Tried to Run with elevated permissions also . resulting same error

![image](https://user-images.githubusercontent.com/48405092/55130654-a08f9800-5141-11e9-829d-f53646cae4d1.png)

Log file  : 

[MSIa7fb0.LOG](https://github.com/elastic/windows-installers/files/3016230/MSIa7fb0.LOG)

**Comment by russcam** [comment]
The error in the log is

> Trying to execute StopServiceTask seeing service: True
> Elastic.InstallerHosts.Elasticsearch.Tasks.StopServiceTask: Stopping existing Elasticsearch service
> System.InvalidOperationException: Cannot stop Elasticsearch service on computer '.'. ---> System.ComponentModel.Win32Exception: The service cannot accept control messages at this time
>    --- End of inner exception stack trace ---
>    at System.ServiceProcess.ServiceController.Stop()
>    at Elastic.Installer.Domain.Configuration.Service.ServiceStateProvider.StopIfRunning(TimeSpan timeToWait)
>    at Elastic.InstallerHosts.Elasticsearch.Tasks.StopServiceTask.ExecuteTask()
>    at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
> CustomAction ElasticsearchServiceStopAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
> Action ended 10:19:30: InstallFinalize. Return value 3.

The installation process was unable to stop the currently running elasticsearch windows service on the machine.

The running elasticsearch windows service that you have, is it from a previous MSI installation, or zip installation, (or custom)? Please stop and remove that Windows service attempt the install again.

I would strongly recommend using a newer Elasticsearch 5.x installer than 5.5.0, [such as 5.6.16](https://www.elastic.co/downloads/past-releases/elasticsearch-5-6-16) or the latest 6.x, [6.7.0](https://www.elastic.co/downloads/past-releases/elasticsearch-6-7-0).

**Comment by sikhaarun** [comment]
Yes .I've stopped and deleted running elasticsearch service .Now its Installed Successfully . 

Thank you so much

**Comment by russcam** [comment]
Great! I'm going to close this issue as it's resolved.
