### ISSUE TITLE
Windows MSI 6.7.1 Installation Fail

### ISSUE THREAD

**Issue by GrandMastaC** [elastic/windows-installers#282]
So I keep getting the installation fail. I suspect it was from my initial download of the non-MSI zip file but I thought I had deleted and uninstalled all related files and operations but I can't seem to find the problem.  Much appreciated in any help here.

[Log File.txt](https://github.com/elastic/windows-installers/files/3046066/Log.File.txt)

### Steps to reproduce the behaviour

1.
2.
3.

**Comment by russcam** [comment]
This is the same issue as #283. Closing this in favour of continuing discussion there.
