### ISSUE TITLE
An error occurred during installation using msi in windows 10

### ISSUE THREAD

**Issue by fereshtehrabet** [elastic/windows-installers#289]
### Environment
windows 10

### Steps to reproduce the behaviour
I was just using MSI installer. please see the attachment
[MSIfc6d7.LOG](https://github.com/elastic/windows-installers/files/3086024/MSIfc6d7.LOG)

1. N/A

**Comment by liacosgrove** [comment]
One thing I see in the log is that it seems the ElasticsearchBootstrapPasswordAction method wasn't able to be called (MSI error 1626) due to being unable to find Java.  Do you have Java installed?  If so, do you have a JAVA_HOME environment variable set to the right path?

**Comment by fereshtehrabet** [comment]
Thanks for your help, I had it installed but JAVA_HOME variable was missing.

**Comment by liacosgrove** [comment]
Glad it was of use :)
