### ISSUE TITLE
Build failing 

### ISSUE THREAD

**Issue by larsbj** [elastic/windows-installers#29]
Hi,

using 64bit Windows 10 Pro version 1607. 

I did a clone today, cd'ed to windows-installers folder and ran build. It seems the tests fail for some reason?

`C:\src>cd elastic\windows-installers

C:\src\elastic\windows-installers>build
Checking Paket version (downloading latest stable)...
Version 4.8.6 not found in cache.
Starting download from https://github.com/fsprojects/Paket/releases/download/4.8.6/paket.exe
Done.
Paket version 4.8.6
Downloading FAKE 4.61.2 (build)
Downloading FSharp.Configuration 1.2 (build)
Downloading FSharp.Data 2.3.3 (build)
Downloading FSharp.Text.RegexProvider 1.0 (build)
Downloading System.Management.Automation 6.1.7601.17515 (build)
Downloading xunit.runner.console 2.2 (build)
Downloading Zlib.Portable 1.11 (build)
Downloading HtmlTextBlock 1.0.1
Downloading FluentValidation 5.5
Downloading Microsoft.CSharp 4.3
Downloading Costura.Fody 1.3.3
Downloading ilmerge 2.14.1208
Downloading MahApps.Metro.Resources 0.4
Downloading MahApps.Metro 1.0.1-ALPHA027
Downloading Fody 1.29.4
Downloading Microsoft.NETCore.Platforms 1.1
Downloading Microsoft.NETCore.Targets 1.1
Downloading Microsoft.Win32.Primitives 4.3
Downloading NETStandard.Library 1.6.1
Downloading Newtonsoft.Json 10.0.2
Downloading NuGet.CommandLine 4.1
Downloading reactiveui 6.3.1
Downloading reactiveui-core 6.3.1
Downloading reactiveui-events 6.3.1
Downloading runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1
Downloading runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1
Downloading runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1
Downloading runtime.native.System 4.3
Downloading runtime.native.System.IO.Compression 4.3
Downloading runtime.native.System.Net.Http 4.3
Downloading runtime.native.System.Security.Cryptography.Apple 4.3
Downloading runtime.native.System.Security.Cryptography.OpenSsl 4.3.1
Downloading runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1
Downloading runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1
Downloading runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple 4.3
Downloading runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1
Downloading runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1
Downloading runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1
Downloading runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1
Downloading runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.1
Downloading Rx-Core 2.2.5
Downloading Rx-Interfaces 2.2.5
Downloading Rx-Linq 2.2.5
Downloading Rx-Main 2.2.5
Downloading Rx-PlatformServices 2.2.5
Downloading Rx-Xaml 2.2.5
Downloading semver 2.0.4
Downloading SharpYaml 1.6.1
Downloading Splat 1.6
Downloading System.AppContext 4.3
Downloading System.Buffers 4.3
Downloading System.Collections 4.3
Downloading System.Collections.Concurrent 4.3
Downloading System.Collections.NonGeneric 4.3
Downloading System.Collections.Specialized 4.3
Downloading System.ComponentModel 4.3
Downloading System.ComponentModel.Primitives 4.3
Downloading System.ComponentModel.TypeConverter 4.3
Downloading System.Console 4.3
Downloading System.Diagnostics.Debug 4.3
Downloading System.Diagnostics.DiagnosticSource 4.3.1
Downloading System.Diagnostics.Tools 4.3
Downloading System.Diagnostics.Tracing 4.3
Downloading System.Dynamic.Runtime 4.3
Downloading System.Globalization 4.3
Downloading System.Globalization.Calendars 4.3
Downloading System.Globalization.Extensions 4.3
Downloading System.IO 4.3
Downloading System.IO.Abstractions 2.0.0.144
Downloading System.IO.Abstractions.TestingHelpers 2.0.0.143
Downloading System.IO.Compression 4.3
Downloading System.IO.Compression.ZipFile 4.3
Downloading System.IO.FileSystem 4.3
Downloading System.IO.FileSystem.Primitives 4.3
Downloading System.Linq 4.3
Downloading System.Linq.Expressions 4.3
Downloading System.Net.Http 4.3.2
Downloading System.Net.Primitives 4.3
Downloading System.Net.Sockets 4.3
Downloading System.ObjectModel 4.3
Downloading System.Reflection 4.3
Downloading System.Reflection.Emit 4.3
Downloading System.Reflection.Emit.ILGeneration 4.3
Downloading System.Reflection.Emit.Lightweight 4.3
Downloading System.Reflection.Extensions 4.3
Downloading System.Reflection.Primitives 4.3
Downloading System.Reflection.TypeExtensions 4.3
Downloading System.Resources.ResourceManager 4.3
Downloading System.Runtime 4.3
Downloading System.Runtime.Extensions 4.3
Downloading System.Runtime.Handles 4.3
Downloading System.Runtime.InteropServices 4.3
Downloading System.Runtime.InteropServices.RuntimeInformation 4.3
Downloading System.Runtime.Numerics 4.3
Downloading System.Runtime.Serialization.Formatters 4.3
Downloading System.Runtime.Serialization.Primitives 4.3
Downloading System.Security.Cryptography.Algorithms 4.3
Downloading System.Security.Cryptography.Cng 4.3
Downloading System.Security.Cryptography.Csp 4.3
Downloading System.Security.Cryptography.Encoding 4.3
Downloading System.Security.Cryptography.OpenSsl 4.3
Downloading System.Security.Cryptography.Primitives 4.3
Downloading System.Security.Cryptography.X509Certificates 4.3
Downloading System.Text.Encoding 4.3
Downloading System.Text.Encoding.Extensions 4.3
Downloading System.Text.RegularExpressions 4.3
Downloading System.Threading 4.3
Downloading System.Threading.Tasks 4.3
Downloading System.Threading.Tasks.Extensions 4.3
Downloading System.Threading.Timer 4.3
Downloading System.Xml.ReaderWriter 4.3
Downloading System.Xml.XDocument 4.3
Downloading System.Xml.XmlDocument 4.3
Downloading Topshelf 3.1.4
Downloading WindowsAPICodePack-Core 1.1.1
Downloading WindowsAPICodePack-Shell 1.1.1
Downloading WixSharp.bin 1.4.4.1
Downloading WixSharp.wix.bin 3.10.3
Downloading YamlDotNet 3.8
Downloading FluentAssertions 4.19.2 (tests)
Downloading xunit.extensibility.execution 2.2 (tests)
Downloading xunit.extensibility.core 2.2 (tests)
Downloading xunit.core 2.2 (tests)
Downloading xunit.abstractions 2.0.1 (tests)
Downloading xunit.assert 2.2 (tests)
Downloading xunit 2.2 (tests)
2 minutes, 16 seconds - ready.
Loading download feed data from https://www.elastic.co/downloads/past-releases/feed
Extracted elasticsearch version 5.4.0 from 'Elasticsearch 5.4.0'
Loading download feed data from https://www.elastic.co/downloads/past-releases/feed
Extracted kibana version 5.4.0 from 'Kibana 5.4.0'

---------------------------------------------------------------------
buildinstallers
---------------------------------------------------------------------

---------------------------------------------------------------------
Products:

Elasticsearch 5.4.0
Kibana 5.4.0
---------------------------------------------------------------------
Building project with version: LocalBuild
Shortened DependencyGraph for Target BuildInstallers:
<== BuildInstallers
   <== BuildServices
      <== UnitTest
         <== PruneFiles
            <== PatchGuids
               <== UnzipProducts
                  <== DownloadProducts
                     <== Clean

The running order is:
  - Clean
  - DownloadProducts
  - UnzipProducts
  - PatchGuids
  - PruneFiles
  - UnitTest
  - BuildServices
  - BuildInstallers
Running build with 1 worker
Starting Target: Clean
Creating C:\src\elastic\windows-installers\src\Installer\Elastic.Installer.Msi\bin\Release\
Creating C:\src\elastic\windows-installers\build\out\
Creating C:\src\elastic\windows-installers\build\results\
Creating C:\src\elastic\windows-installers\build\out\elasticsearch
Creating C:\src\elastic\windows-installers\src\ProcessHosts\Elastic.ProcessHosts.Elasticsearch\bin\AnyCPU\Release\
Creating C:\src\elastic\windows-installers\build\out\kibana
Creating C:\src\elastic\windows-installers\src\ProcessHosts\Elastic.ProcessHosts.Kibana\bin\AnyCPU\Release\
Finished Target: Clean
Starting Target: DownloadProducts (==> Clean)
Creating C:\src\elastic\windows-installers\build\in\
Downloading elasticsearch 5.4.0
Done downloading elasticsearch 5.4.0
C:\src\elastic\windows-installers\build\in\ already exists.
Downloading kibana 5.4.0
Done downloading kibana 5.4.0
Finished Target: DownloadProducts
Starting Target: UnzipProducts (==> DownloadProducts)
C:\src\elastic\windows-installers\build\in\ already exists.
C:\src\elastic\windows-installers\build\in\ already exists.
Unzipping elasticsearch 5.4.0
C:\src\elastic\windows-installers\build\in\ already exists.
C:\src\elastic\windows-installers\build\in\ already exists.
C:\src\elastic\windows-installers\build\in\ already exists.
Unzipping kibana 5.4.0
C:\src\elastic\windows-installers\build\in\ already exists.
Finished Target: UnzipProducts
Starting Target: PatchGuids (==> UnzipProducts)
Making sure guids exist for
 Elasticsearch 5.4.0
Kibana 5.4.0
found 19 elasticsearch known versions
found 13 kibana known versions
Finished Target: PatchGuids
Starting Target: PruneFiles (==> PatchGuids)
Finished Target: PruneFiles
Starting Target: UnitTest (==> PruneFiles)
Building project: C:\src\elastic\windows-installers\src\Tests\Elastic.Domain.Tests\Elastic.Domain.Tests.csproj
  C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe  C:\src\elastic\windows-installers\src\Tests\Elastic.Domain.Tests\Elastic.Domain.Tests.csproj /t:Build /m      /p:RestorePackages="False" /p:OutputPath="C:\src\elastic\windows-installers\src\Tests\Elastic.Domain.Tests\bin\Release" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\src\elastic\windows-installers\packages\build\FAKE\tools\FakeLib.dll"
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 01/06/2017 10:11:29.
     1>Project "C:\src\elastic\windows-installers\src\Tests\Elastic.Domain.Tests\Elastic.Domain.Tests.csproj" on node 1
        (Build target(s)).
     1>PrepareForBuild:
         Creating directory "C:\src\elastic\windows-installers\src\Tests\Elastic.Domain.Tests\bin\Release\".
         Creating directory "obj\Release\".
     1>Project "C:\src\elastic\windows-installers\src\Tests\Elastic.Domain.Tests\Elastic.Domain.Tests.csproj" (1) is bu
       ilding "C:\src\elastic\windows-installers\src\Elastic.Configuration\Elastic.Configuration.csproj" (2) on node 1
       (default targets).
     2>PrepareForBuild:
         Creating directory "obj\Release\".
       GenerateTargetFrameworkMonikerAttribute:
       Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect t
       o the input files.
       CoreCompile:
         C:\Program Files (x86)\MSBuild\14.0\bin\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:AnyCPU /error
         report:prompt /warn:4 /define:TRACE /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Mi
         crosoft\Framework\.NETFramework\v4.5\mscorlib.dll" /reference:C:\src\elastic\windows-installers\packages\Sharp
         Yaml\lib\net45\SharpYaml.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETF
         ramework\v4.5\System.Configuration.Install.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Micros
         oft\Framework\.NETFramework\v4.5\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Micr
         osoft\Framework\.NETFramework\v4.5\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Mi
         crosoft\Framework\.NETFramework\v4.5\System.dll" /reference:C:\src\elastic\windows-installers\packages\System.
         IO.Abstractions\lib\net40\System.IO.Abstractions.dll /reference:"C:\Program Files (x86)\Reference Assemblies\M
         icrosoft\Framework\.NETFramework\v4.5\System.ServiceProcess.dll" /reference:"C:\Program Files (x86)\Reference
         Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll" /debug:pdbonly /filealign:512 /optimize+ /ou
         t:obj\Release\Elastic.Configuration.dll /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Too
         ls\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" /subsystemversion:6.00 /target:library /u
         tf8output EnvironmentBased\ElasticsearchEnvironmentStateProvider.cs EnvironmentBased\Java\JavaConfiguration.cs
          EnvironmentBased\Java\JavaEnvironmentStateProvider.cs EnvironmentBased\KibanaEnvironmentStateProvider.cs Exte
         nsions\ExceptionEventLogExtensions.cs FileBased\JvmOpts\LocalJvmOptionsConfiguration.cs FileBased\Yaml\Elastic
         searchYamlConfiguration.cs FileBased\Yaml\ElasticsearchYamlSettings.cs FileBased\Yaml\IYamlSettings.cs FileBas
         ed\Yaml\KibanaYamlConfiguration.cs FileBased\Yaml\KibanaYamlSettings.cs FileBased\Yaml\YamlSettingsBase.cs Pro
         perties\AssemblyInfo.cs "C:\Users\lbj\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cs"
         Using shared compilation with compiler from directory: C:\Program Files (x86)\MSBuild\14.0\bin
     1>Project "C:\src\elastic\windows-installers\src\Tests\Elastic.Domain.Tests\Elastic.Domain.Tests.csproj" (1) is bu
       ilding "C:\src\elastic\windows-installers\src\InstallerHosts\Elastic.InstallerHosts\Elastic.InstallerHosts.cspro
       j" (3) on node 2 (default targets).
     3>PrepareForBuild:
         Creating directory "obj\Release\".
     3>Project "C:\src\elastic\windows-installers\src\InstallerHosts\Elastic.InstallerHosts\Elastic.InstallerHosts.cspr
       oj" (3) is building "C:\src\elastic\windows-installers\src\Installer\Elastic.Installer.Domain\Elastic.Installer.
       Domain.csproj" (4) on node 2 (default targets).
     4>PrepareForBuild:
         Creating directory "obj\Release\".
     1>Project "C:\src\elastic\windows-installers\src\Tests\Elastic.Domain.Tests\Elastic.Domain.Tests.csproj" (1) is bu
       ilding "C:\src\elastic\windows-installers\src\ProcessHosts\Elastic.ProcessHosts\Elastic.ProcessHosts.csproj" (5)
        on node 2 (default targets).
     5>PrepareForBuild:
         Creating directory "obj\Release\".
     2>FileBased\Yaml\ElasticsearchYamlSettings.cs(61,60): error CS1525: Invalid expression term 'int' [C:\src\elastic\
       windows-installers\src\Elastic.Configuration\Elastic.Configuration.csproj]
     2>FileBased\Yaml\ElasticsearchYamlSettings.cs(61,64): error CS1003: Syntax error, ',' expected [C:\src\elastic\win
       dows-installers\src\Elastic.Configuration\Elastic.Configuration.csproj]
     2>FileBased\Yaml\ElasticsearchYamlSettings.cs(67,76): error CS1525: Invalid expression term 'int' [C:\src\elastic\
       windows-installers\src\Elastic.Configuration\Elastic.Configuration.csproj]
     2>FileBased\Yaml\ElasticsearchYamlSettings.cs(67,80): error CS1003: Syntax error, ',' expected [C:\src\elastic\win
       dows-installers\src\Elastic.Configuration\Elastic.Configuration.csproj]
     2>Done Building Project "C:\src\elastic\windows-installers\src\Elastic.Configuration\Elastic.Configuration.csproj"
        (default targets) -- FAILED.
     5>Done Building Project "C:\src\elastic\windows-installers\src\ProcessHosts\Elastic.ProcessHosts\Elastic.ProcessHo
       sts.csproj" (default targets) -- FAILED.
     4>Done Building Project "C:\src\elastic\windows-installers\src\Installer\Elastic.Installer.Domain\Elastic.Installe
       r.Domain.csproj" (default targets) -- FAILED.
     3>Done Building Project "C:\src\elastic\windows-installers\src\InstallerHosts\Elastic.InstallerHosts\Elastic.Insta
       llerHosts.csproj" (default targets) -- FAILED.
     1>Done Building Project "C:\src\elastic\windows-installers\src\Tests\Elastic.Domain.Tests\Elastic.Domain.Tests.csp
       roj" (Build target(s)) -- FAILED.

Build FAILED.

       "C:\src\elastic\windows-installers\src\Tests\Elastic.Domain.Tests\Elastic.Domain.Tests.csproj" (Build target) (1
       ) ->
       "C:\src\elastic\windows-installers\src\Elastic.Configuration\Elastic.Configuration.csproj" (default target) (2)
       ->
       (CoreCompile target) ->
         FileBased\Yaml\ElasticsearchYamlSettings.cs(61,60): error CS1525: Invalid expression term 'int' [C:\src\elasti
       c\windows-installers\src\Elastic.Configuration\Elastic.Configuration.csproj]
         FileBased\Yaml\ElasticsearchYamlSettings.cs(61,64): error CS1003: Syntax error, ',' expected [C:\src\elastic\w
       indows-installers\src\Elastic.Configuration\Elastic.Configuration.csproj]
         FileBased\Yaml\ElasticsearchYamlSettings.cs(67,76): error CS1525: Invalid expression term 'int' [C:\src\elasti
       c\windows-installers\src\Elastic.Configuration\Elastic.Configuration.csproj]
         FileBased\Yaml\ElasticsearchYamlSettings.cs(67,80): error CS1003: Syntax error, ',' expected [C:\src\elastic\w
       indows-installers\src\Elastic.Configuration\Elastic.Configuration.csproj]

    0 Warning(s)
    4 Error(s)

Time Elapsed 00:00:00.82
Running build failed.
Error:
Building C:\src\elastic\windows-installers\src\Tests\Elastic.Domain.Tests\Elastic.Domain.Tests.csproj failed with exitcode 1.

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target             Duration
------             --------
Clean              00:00:00.0120493
DownloadProducts   00:00:23.8314239
UnzipProducts      00:00:28.2802480
PatchGuids         00:00:00.0614195
PruneFiles         00:00:00.0080441
UnitTest           Failure
Total:             00:00:53.6621467
---------------------------------------------------------------------
Status:            Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) Building C:\src\elastic\windows-installers\src\Tests\Elastic.Domain.Tests\Elastic.Domain.Tests.csproj failed with exitcode 1.
  2) CS1525: FileBased\Yaml\ElasticsearchYamlSettings.cs(61,60): Invalid expression term 'int'
  3) CS1003: FileBased\Yaml\ElasticsearchYamlSettings.cs(61,64): Syntax error, ',' expected
  4) CS1525: FileBased\Yaml\ElasticsearchYamlSettings.cs(67,76): Invalid expression term 'int'
  5) CS1003: FileBased\Yaml\ElasticsearchYamlSettings.cs(67,80): Syntax error, ',' expected
---------------------------------------------------------------------
Dynamic assemblies were generated during evaluation of script (tmpB4BA).
Can not save cache.
`

**Comment by larsbj** [comment]
I have Visual Studio 2015 installed on this machine, could that affect the build? (I see the installer is based on .NET)

**Comment by russcam** [comment]
Hey @larsbj, you'll need a version of MsBuild and the C# compiler that understands out variables and other [C# 7 features](https://blogs.msdn.microsoft.com/dotnet/2016/08/24/whats-new-in-csharp-7-0/).

Perhaps the easiest way of getting this is to install Visual Studio 2017.

**Comment by larsbj** [comment]
Thank you for your quick reply! I will close this issue and try on another machine here later with VS2017.
