### ISSUE TITLE
Could not find a valid Java installation

### ISSUE THREAD

**Issue by curdincaspar** [elastic/windows-installers#290]
### Environment

No proxy and located in Switzerland.

### Expected Behaviour

As the new 7.0 version bundles the jdk the installation should continue without an existing Java installation.

### Actual Behaviour

The installation starts and shows a pre-requisite error:
![image](https://user-images.githubusercontent.com/8039040/56361630-26a27a00-61e8-11e9-8520-fa2e156540c0.png)

### Steps to reproduce the behaviour

1. Have a system with no Java
2. Start the installer
3. See the error

**Comment by ygel** [comment]
Please try v7.2.0 and if it fails for you as well, attach MSI log, we'll diagnose.

**Comment by CaringDev** [comment]
works in 7.2.0 (on behalf of @curdincaspar)

**Comment by debadair** [comment]
I encountered this problem with 7.2.0. Installing OpenJDK separately and re-running the installer resolved the problem. 

![image](https://user-images.githubusercontent.com/362578/61748636-9aa76d80-ad55-11e9-8648-ec71ce457e07.png)

**Comment by russcam** [comment]
The installer currently expects `JAVA_HOME` environment variable to be set, or to find a Java installation based on finding it in the registry. 

This should be updated to use the bundled JDK installation _if_ `JAVA_HOME` is not set.
