### ISSUE TITLE
Problem installing ELasticsearch on Windows 7!

### ISSUE THREAD

**Issue by Mhamed1** [elastic/windows-installers#295]
Hello 
So I have tried to install Elasticsearch 5.6.15 but i receive this message ever tyime: 
"An error occured during installation!". 
Note that i've used the .msi file provided on the elastic website, that i shut down the firewall and that the TLS 1.2 is now activated on my OS. 
Also the same message have been displayed when i tried to install the 7.0.0 and 7.0.1 versions. 
I will attach the installation log file. 

Thanks for responding.
[Installation log file.txt](https://github.com/elastic/windows-installers/files/3137566/Installation.log.file.txt)

**Comment by russcam** [comment]
The issue is that the Administrateur account name is invalid or does not exist, or the password for the account is incorrect

```
- ServiceAccount = User
- UserName = Administrateur
- Password = True

[0] installing installing
System.InvalidOperationException: L'installation a échoué et la restauration a eu lieu. ---> System.ComponentModel.Win32Exception: Le nom de compte n’est pas valide ou n’existe pas, ou le mot de passe n’est pas valide pour le nom de compte spécifié
   à System.ServiceProcess.ServiceInstaller.Install(IDictionary stateSaver)
   à System.Configuration.Install.Installer.Install(IDictionary stateSaver)
   à Elastic.Installer.Domain.Configuration.Service.ServiceInstallationManager.Install(IDictionary stateSaver)
   à System.Configuration.Install.Installer.Install(IDictionary stateSaver)
   à System.Configuration.Install.TransactedInstaller.Install(IDictionary savedState)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Configuration.Install.TransactedInstaller.Install(IDictionary savedState)
   à Elastic.Installer.Domain.Configuration.Service.ServiceInstallationManager.RuntimeInstall(ServiceConfiguration configuration)
   à Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallServiceTask.ExecuteTask()
   à Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
```

Can you try another account with which to run the Windows Service?

**Comment by Mhamed1** [comment]
Thanks for your fast answer ! 
[log file Elasticsearch 7.0.0_.txt](https://github.com/elastic/windows-installers/files/3137729/log.file.Elasticsearch.7.0.0_.txt)

So I tried the same thing with the 7.0.0 version with another account (admin) and I went with the use local system option, also I did tick LOCK JVM MEMORY. 
The problem persists, knowing that the installation screen mentions all the steps untill "Starting Elasticsearch Service", when the message :" Rollbackdirectory" appears and apparently it starts to delete the files it has copied. 
I will attach the new log file !

**Comment by AhmedAbdelrehim** [comment]
I have the same exact issue, the log file is not clear as to why installation is failing. Any help?
[MSIf4cbc.LOG](https://github.com/elastic/windows-installers/files/3183576/MSIf4cbc.LOG)

**Comment by AhmedAbdelrehim** [comment]
> I have the same exact issue, the log file is not clear as to why installation is failing. Any help?
> [MSIf4cbc.LOG](https://github.com/elastic/windows-installers/files/3183576/MSIf4cbc.LOG)

got admin rights and it worked like magic. try that out

**Comment by Mhamed1** [comment]
Hey ! Sorry I was not online.
Do you mean using an admin account ? Well I've done that and still.
Did you try anything else ?

Le mer. 15 mai 2019 à 20:53, AhmedAbdelrehim <notifications@github.com> a
écrit :

**Comment by AhmedAbdelrehim** [comment]
Yes, I grant my user admin privileges and it worked

**Comment by ygel** [comment]
Also:

```Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Install.ElasticsearchBootstrapPasswordAction.ElasticsearchBootstrapPassword
"could not find java in JAVA_HOME or bundled at C:\Program Files\Elastic\Elasticsearch\7.0.0\jdk"
```
 Please try a more recent version.
