### ISSUE TITLE
Cannot connect to localhost:9200

### ISSUE THREAD

**Issue by Mhamed1** [elastic/windows-installers#296]
Hello

So I downloaded the .zip file of Elasticsearch 7.0.1 and installed it ! 
(I followed this tutorial: https://www.youtube.com/watch?v=YE7AzSCC3E0&t=298s) 
The current problem is that I can't connect to the localhost! 
I will attach the log file below!
THANKS in advance! 
[elasticsearch.log](https://github.com/elastic/windows-installers/files/3137935/elasticsearch.log)

**Comment by russcam** [comment]
Hi @Mhamed1 , 

We reserve GitHub Issues for bug reports and feature requests.

In order for your question to get the attention it deserves, the best place to ask it would be the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence it is more likely to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.

The issue looks similar to: https://discuss.elastic.co/t/failed-to-start-machine-learning-on-elasticsearch-7-0-0/178216

I'm closing this issue.

Thanks!

**Comment by Mhamed1** [comment]
I see! Thanks this was very helpful!
