### ISSUE TITLE
Installation failed through MSI

### ISSUE THREAD

**Issue by s-lamani** [elastic/windows-installers#299]
### Environment
Windows 10 Pro 64 bit

### Expected Behaviour
![ELK](https://user-images.githubusercontent.com/24887547/58077521-54555700-7bca-11e9-9ab6-eb91663b7440.JPG)

### Steps to reproduce the behaviour

1.Run MSI elasticsearch-7.0.1
2.
3.

[MSIec29.LOG](https://github.com/elastic/windows-installers/files/3201310/MSIec29.LOG)

**Comment by s-lamani** [comment]
Hi,
Waiting for reply.

**Comment by ygel** [comment]
Duplicate of #305
