### ISSUE TITLE
ElasticSearch 7.1.0 MSI installation failed

### ISSUE THREAD

**Issue by Shamikar** [elastic/windows-installers#300]
Below is the screen shot and error produced while installing ES using msi on windows 10 desktop:

![image](https://user-images.githubusercontent.com/22054186/58124395-2416b400-7bdc-11e9-91d4-7f7cfaf074be.png)

### Environment
windows 10 
No proxy
EAST, USA

### LOGFILE
=== Verbose logging started: 5/21/2019  14:59:38  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\Windows\System32\msiexec.exe ===
MSI (c) (E0:A8) [14:59:38:323]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (E0:A8) [14:59:38:323]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (E0:44) [14:59:38:365]: Resetting cached policy values
MSI (c) (E0:44) [14:59:38:365]: Machine policy value 'Debug' is 0
MSI (c) (E0:44) [14:59:38:365]: ******* RunEngine:
           ******* Product: C:\Users\bomber\Downloads\elasticsearch-7.1.0.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (E0:44) [14:59:38:367]: Machine policy value 'DisableUserInstalls' is 0
MSI (c) (E0:44) [14:59:38:545]: SOFTWARE RESTRICTION POLICY: Verifying package --> 'C:\Users\bomber\Downloads\elasticsearch-7.1.0.msi' against software restriction policy
MSI (c) (E0:44) [14:59:38:545]: SOFTWARE RESTRICTION POLICY: C:\Users\bomber\Downloads\elasticsearch-7.1.0.msi has a digital signature
MSI (c) (E0:44) [14:59:39:641]: SOFTWARE RESTRICTION POLICY: C:\Users\bomber\Downloads\elasticsearch-7.1.0.msi is permitted to run at the 'unrestricted' authorization level.
MSI (c) (E0:44) [14:59:39:753]: Cloaking enabled.
MSI (c) (E0:44) [14:59:39:753]: Attempting to enable all disabled privileges before calling Install on Server
[MSI1680c.LOG.txt](https://github.com/elastic/windows-installers/files/3204152/MSI1680c.LOG.txt)

**Comment by thophan92** [comment]
I faced the same issue. Here is the log file.
Environment
windows 10 pro 64-bit OS
No proxy
Japan
[MSIb9a56.LOG](https://github.com/elastic/windows-installers/files/3216029/MSIb9a56.LOG)

**Comment by InKolev** [comment]
Same issue on my local PC.

Windows 10 Pro, 64 bit OS,
Intel Core i7-7820HQ, 32 GB's of RAM.

No Proxy

Bulgaria, Europe

Here's the log file:
[elasticsearch-installer-logs.txt](https://github.com/elastic/windows-installers/files/3220059/elasticsearch-installer-logs.txt)

**Comment by puskyer** [comment]
Same here
Windows 10 Enterprise  - 1809 build 17763.437
HP EliteBook 
16 Gig memory

[MSI8ab04.LOG](https://github.com/elastic/windows-installers/files/3229619/MSI8ab04.LOG)

**Comment by vaibhavsakhare123** [comment]
Same problem here,
Please give any solution

**Comment by InKolev** [comment]
> Same problem here,
> Please give any solution

As I stated in my comment above, you can work around this by:

**1. Downloading the ZIP file from here**:
https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.1.1-windows-x86_64.zip

**2. Unzip the downloaded file wherever you want.**

3. Navigate to **"....\elasticsearch-7.1.1\bin"**

4. Run the **"elasticsearch.bat"** file.

![image](https://user-images.githubusercontent.com/6628205/59345687-4ef6b280-8d19-11e9-9156-f046229b41b3.png)

![image](https://user-images.githubusercontent.com/6628205/59345817-a2690080-8d19-11e9-95fa-eddbe632b9c8.png)

Voila.

To kill the ES node, you just stop the bat file.

**Comment by superern** [comment]
> > Same problem here,
> > Please give any solution
> 
> As I stated in my comment above, you can work around this by:
> 
> **1. Downloading the ZIP file from here:**
> https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.1.1-windows-x86_64.zip
> 
> **2. Unzip the downloaded file wherever you want.**
> 
> **3. Navigate to _"....\elasticsearch-7.1.1\bin"_**
> 
> ![image](https://user-images.githubusercontent.com/6628205/59345687-4ef6b280-8d19-11e9-9156-f046229b41b3.png)
> 
> **4. Run the _"elasticsearch.bat"_ file.**
> 
> ![image](https://user-images.githubusercontent.com/6628205/59345817-a2690080-8d19-11e9-95fa-eddbe632b9c8.png)
> 
> Voila.
> 
> To kill the ES node, you just stop the bat file.

experiencing error with this. could not find java in JAVA_HOME or bundled at C:\ProgramData\Elastic\Elasticsearch\7.1.1\jdk

**Comment by InKolev** [comment]
> > > Same problem here,
> > > Please give any solution
> > 
> > 
> > As I stated in my comment above, you can work around this by:
> > **1. Downloading the ZIP file from here:**
> > https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.1.1-windows-x86_64.zip
> > **2. Unzip the downloaded file wherever you want.**
> > **3. Navigate to _"....\elasticsearch-7.1.1\bin"_**
> > ![image](https://user-images.githubusercontent.com/6628205/59345687-4ef6b280-8d19-11e9-9156-f046229b41b3.png)
> > **4. Run the _"elasticsearch.bat"_ file.**
> > ![image](https://user-images.githubusercontent.com/6628205/59345817-a2690080-8d19-11e9-95fa-eddbe632b9c8.png)
> > Voila.
> > To kill the ES node, you just stop the bat file.
> 
> experiencing error with this.
> 
> > could not find java in JAVA_HOME or bundled at C:\ProgramData\Elastic\Elasticsearch\7.1.1\jdk

@superern, You need to install Java and add it to your system's environment variables:

**1. Install Java:**
https://www.youtube.com/watch?v=f7rT0h1Q5Wo

**2. Add java to env variables:** 
https://javatutorial.net/set-java-home-windows-10
