### ISSUE TITLE
http://localhost:5601/api/status returns Not Found

### ISSUE THREAD

**Issue by Mhamed1** [elastic/windows-installers#302]
Hello! 
So I've installed the Bitnami pack of The Elastic Stack. 
Both Kibana and Elasticsearch are running. Yet when installing Filebeat i receive this message (after passing the  .\filebeat.exe setup command) :
<Exiting: error connecting to kibana: fail to get the kibana version: HTTP GET request to http://localhost:5601/api/status fails: parsing kibana response: invalid character 'N' looking for beginning of value. Response: Not Found.>
I searched for http://localhost:5601/api/status in the browser and the page only displayed a Not Found message. 
Thanks for your help !

**Comment by russcam** [comment]
@Mhamed1 This is not the correct GitHub repository for the Bitnami installation of the Elastic Stack. I would recommend [getting in contact with Bitnami through their website](https://bitnami.com/) for help with their deployment.
