### ISSUE TITLE
Unable to select "basis" license type

### ISSUE THREAD

**Issue by Paulomart** [elastic/windows-installers#307]
### Environment

Does not apply here.

### Expected Behaviour

Currently there are [4 different types of subscriptions](https://www.elastic.co/de/subscriptions):

1. OpenSource
2. Basis (**Includes security [[1]]**)
3. Gold
4. Platinum

I would expect that you can choose from the (at least) 3 types:

1. None aka OpenSource
2. Basis
3. Gold / Platinum

### Actual Behaviour

When installing only the following license types are available:

1. Basic
2. Trail

It might seem like "basic" is the same as "basis", but if "basic" is selected its **not possible to configure security**.

Even more strangely the info about "basic" says:

> Access to all free X-Pack Basic features without an expiry date on the license. 

This seems to fit the blog post description, but as stated above its not possible to configure security features.

### Steps to reproduce the behaviour

1. Download the latest version of the installer, currently [7.1.1](https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.1.1.msi).
2. Start it
3. Goto the "X-Pack" tab.
4. See the situation as described above.

[1]: https://www.elastic.co/blog/security-for-elasticsearch-is-now-free

**Comment by russcam** [comment]
@Paulomart I believe you are looking for the Basic license, which is _Basis_ on the German translation of the subscriptions page:

![image](https://user-images.githubusercontent.com/208231/60861321-61530600-a25d-11e9-9dfb-4ab7ee8650f1.png)

_(English version, for reference)_:

![image](https://user-images.githubusercontent.com/208231/60861338-74fe6c80-a25d-11e9-8f6c-f77fb0c97952.png)

The installer installs the default distribution of Elasticsearch, so for 6.3.0 and above, this is the basic license level.

> It might seem like "basic" is the same as "basis", but if "basic" is selected its not possible to configure security.

We are in the process of evaluating the future roadmap of installers at the moment, and this is not implemented as an installation feature of current Elasticsearch installer. It is however possible to configure security after installation for version 7.2.0 and above with the basic license, by going through [the configuring security docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/configuring-security.html).

**Comment by Paulomart** [comment]
@russcam Thanks for your reply.

> I believe you are looking for the Basic license, which is Basis on the German translation of the subscriptions page

Okay that makes sense now.

> It is however possible to configure security after installation for version 7.2.0 and above with the basic license, by going through the configuring security docs.

This is the resolution for me.

Out of curiosity is there any timeframe on this plan?

**Comment by russcam** [comment]
I don't have a timeline that I can share for this, I'm afraid. I'd recommend subscribing to notifications on the repository if you're interested in tracking the development activity.
