### ISSUE TITLE
Error during installation , when the setup try to start the elasticsearch service 

### ISSUE THREAD

**Issue by cosminPintea** [elastic/windows-installers#312]
![image](https://user-images.githubusercontent.com/52402506/60493711-1c0b6300-9cb6-11e9-8003-fa27f8fd4f93.png)

Log from windows:
Service cannot be started. Elastic.ProcessHosts.Process.StartupException: Could not evaluate jvm.options file: C:\ProgramData\Elastic\Elasticsearch\config\jvm.options result: Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
[0.003s][error][logging] Error opening log file 'logs/gc.log': No such file or directory
[0.003s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
error:
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(J...

My JAVA_HOME in System variables: C:\Program Files\Java\jdk-12.0.1

[MSI2bfeb.LOG](https://github.com/elastic/windows-installers/files/3348829/MSI2bfeb.LOG)

**Comment by jwagon** [comment]
Is there a workaround for this?

**Comment by cosminPintea** [comment]
I was unable to start the service, At the end i have start the elastic search from command line. For my dev env for the moment is OK.

**Comment by russcam** [comment]
@jwagon the workaround for the moment is to run the installation, but not install as a service. Then, once installation completes, edit the `jvm.options` file located in the config directory to replace the following line 114

```sh
9-:-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m
```

to replace `logs/gc.log` with an escaped absolute path to an existing logs directory. For example, assuming an installation with the default locations, we can replace with

```sh
9-:-9-:-Xlog:gc*,gc+age=trace,safepoint:file=\"C:\ProgramData\Elastic\Elasticsearch\logs\gc.log\":utctime,pid,tags:filecount=32,filesize=64m
```

Save the file. 

Now, if wishing to install as a Windows service, we can use [`sc.exe create`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sc-create) to install. Again assuming the default install location for 7.2.0,

```bat
sc.exe create Elasticsearch type= own start= auto binpath= "C:\Program Files\Elastic\Elasticsearch\7.2.0\bin\elasticsearch.exe" displayname= Elasticsearch
```

which will return `[SC] CreateService SUCCESS`. Then the service can be started from the Service Control panel, cmd or PowerShell. An example of the latter

```powershell
Start-Service Elasticsearch
```

**Comment by ygel** [comment]
#303 #305

**Comment by csharpsi** [comment]
The work around suggested by @russcam allowed me to start the ES service
