### ISSUE TITLE
An error occurred during installtion

### ISSUE THREAD

**Issue by Venkateshjsoft** [elastic/windows-installers#314]
Steps to reproduce the behaviour
1.This is a fresh install.
2.
3.

Screenshot attached

**Comment by russcam** [comment]
Hi @Venkateshjsoft, 

Please attach the MSI log file for the failed installation; a log file for the installation process can be found within the `%TEMP%` directory, with a randomly generated name adhering to the format `MSI<random>.LOG`. Without this log file, it's not possible to determine why the installation failed.

**Comment by UkrZilla** [comment]
During installation pleased uncheck option: Start service after installer done
then open jvm.options and comment this line:

`9-:-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m`

and service will successfully start

**Comment by Venkateshjsoft** [comment]
> During installation please uncheck option: Start service after installer done
> then open jvm.options and comment this line:
> 
> `9-:-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m`
> 
> and service will successfully start

It is working now. Thanks for your assistance.

**Comment by Venkateshjsoft** [comment]
> Hi @Venkateshjsoft,
> 
> Please attach the MSI log file for the failed installation; a log file for the installation process can be found within the `%TEMP%` directory, with a randomly generated name adhering to the format `MSI<random>.LOG`. Without this log file, it's not possible to determine why the installation failed.

I tried the installation without the option "Start service after installer done" and is working now. Thanks for your advice.

**Comment by Venkateshjsoft** [comment]
> Hi @Venkateshjsoft,
> 
> Please attach the MSI log file for the failed installation; a log file for the installation process can be found within the `%TEMP%` directory, with a randomly generated name adhering to the format `MSI<random>.LOG`. Without this log file, it's not possible to determine why the installation failed.

It is working now. Thanks for your assistance.
