### ISSUE TITLE
An error occurred during installation 7.2.0

### ISSUE THREAD

**Issue by srashok** [elastic/windows-installers#318]
### Steps to reproduce the behaviour

1.
2.
3.

**Comment by russcam** [comment]
Hi @srashok , 

Please attach the MSI log file for the failed installation; a log file for the installation process can be found within the `%TEMP%` directory, with a randomly generated name adhering to the format `MSI<random>.LOG`. Without this log file, it's not possible to determine why the installation failed.

**Comment by srashok** [comment]
[MSId6fda.LOG](https://github.com/elastic/windows-installers/files/3426254/MSId6fda.LOG)
Attached the logs

**Comment by srashok** [comment]
I am not able to find the logs in %TEMP%. I will try to reproduce the issue and upload the logs

**Comment by russcam** [comment]
Before you do, you may be running into the same issue as #312, whereby the installation is installing as a Windows Service, but the Windows Service does not start correctly. If this is the case, please see the workaround in https://github.com/elastic/windows-installers/issues/312#issuecomment-509489684.

If it's a different issue, please see if you can reproduce and provide the log file. A link to the log file is provided in the UI, if the installation fails.

**Comment by russcam** [comment]
Any update @srashok ?

**Comment by ygel** [comment]
Closing as stale.
