### ISSUE TITLE
Cannot install ES 7.2 on Win 10.

### ISSUE THREAD

**Issue by IamIC** [elastic/windows-installers#319]
Cannot get ES 7.2 to install. Fresh installation of Windows (today). Log attached.
[MSIc052.LOG](https://github.com/elastic/windows-installers/files/3413698/MSIc052.LOG)

**Comment by ygel** [comment]
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG
    (file:/C:/Program%20Files/Elastic/Elasticsearch/7.2.0/lib/tools/plugin-cli/bcprov-jdk15on-1.61.jar) to
    .constructor sun.security.provider.Sun()

See #315 and #316. Please check your Java version and workaround for `javaoptions`

**Comment by ygel** [comment]
Closing as stale.
