### ISSUE TITLE
Windows server2008 安装elasticsearch7.2.0.msi失败

### ISSUE THREAD

**Issue by lanbaba666** [elastic/windows-installers#320]
Windows server2008 安装elasticsearch7.2.0.msi失败,错误日志如下
[MSI37498.LOG](https://github.com/elastic/windows-installers/files/3420396/MSI37498.LOG)

**Comment by russcam** [comment]
This looks like the same issue as #312 and #322

> Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.
> MSI (s) (9C:4C) [13:41:11:766]: Note: 1: 2205 2:  3: Error 
> MSI (s) (9C:4C) [13:41:11:766]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
> MSI (s) (9C:4C) [13:41:11:766]: Product: Elasticsearch 7.2.0 -- Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.

This has been fixed for the next release. In the meantime, you can workaround the issue with https://github.com/elastic/windows-installers/issues/312#issuecomment-509489684
