### ISSUE TITLE
Installation 7.2.0 via MSI fails

### ISSUE THREAD

**Issue by roelveldhuizen** [elastic/windows-installers#322]
Installing 7.2.0 via MSI fails on Windows 10 with a fresh install. 

Log file: [MSI10450.LOG](https://github.com/elastic/windows-installers/files/3421487/MSI10450.LOG)

**Comment by russcam** [comment]
This looks like the same issue as #312 

> Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.
> MSI (s) (C4:A4) [12:03:25:467]: Note: 1: 2205 2:  3: Error 
> MSI (s) (C4:A4) [12:03:25:467]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
> MSI (s) (C4:A4) [12:03:25:467]: Product: Elasticsearch 7.2.0 -- Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.

This has been fixed for the next release. In the meantime, you can workaround the issue with https://github.com/elastic/windows-installers/issues/312#issuecomment-509489684
