### ISSUE TITLE
Remove special java installation detection

### ISSUE THREAD

**Issue by rjernst** [elastic/windows-installers#330]
Since 7.0.0, Elasticsearch has included a bundled jdk. The intention is to use this jdk unless a user explicitly sets JAVA_HOME. However, the windows installer has complex logic to try to find installed jdks through the system registry, which effectively ignores the bundled jdk. We should remove all this complicated registry lookup logic and let Elasticsearch handle the jdk.

**Comment by russcam** [comment]
Thanks for raising @rjernst. This is addressed in #325 and has been ported to 7.3, so will be in the next release. 

Closing this issue as resolved.
