### ISSUE TITLE
An error occured when installing version 6.3.1 on Windows 7

### ISSUE THREAD

**Issue by evasann** [elastic/windows-installers#332]
[MSI52223.LOG](https://github.com/elastic/windows-installers/files/3637645/MSI52223.LOG)

### Environment

 No
 Malmö, Sweden

### Steps to reproduce the behaviour

 
Fresh Install

**Comment by ygel** [comment]
Thank you @evasann for submitting this, I'll investigate.

**Comment by ygel** [comment]
@evasann You might be experiencing this issue, #303. Please try the workaround(s), or better yet, use the latest installer! :)

**Comment by ygel** [comment]
Closing as stale.
