### ISSUE TITLE
Issue in installing ElasticSearch 6.5.4 

### ISSUE THREAD

**Issue by ShreyaSharma-git** [elastic/windows-installers#333]
Environment

No
India

### Steps to reproduce the behaviour

Fresh install

1. Download [ES6.5.4] [https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.5.4.msi](url)
2. Execute the msi and click on next and choose trial Xpack feature
3. Installation of ES Service starts
![ESFailure](https://user-images.githubusercontent.com/55779119/65572750-afd38f00-df86-11e9-95af-d6b173f75a65.
[MSI2d279.LOG](https://github.com/elastic/windows-installers/files/3650734/MSI2d279.LOG)
JPG)

[](url)

**Comment by russcam** [comment]
The issue is that Java is not found when attempting to create the elasticsearch-keystore into which the bootstrap password will be added:

```
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Install.ElasticsearchBootstrapPasswordAction.ElasticsearchBootstrapPassword
could not find java; set JAVA_HOME or ensure java is in PATH 
elasticsearch-keystore process returned non-zero exit code: 1
```

A update to Java may have changed environment variables, so be sure that either `JAVA_HOME` environment variable is set, or that the directory in which java.exe resides is in the `PATH` environment variable.

**Comment by ShreyaSharma-git** [comment]
[MSI78a37.LOG](https://github.com/elastic/windows-installers/files/3650999/MSI78a37.LOG)
Issue is still the same even after updating Java package and the Environment variables being set

**Comment by russcam** [comment]
@ShreyaSharma-git how are you setting `JAVA_HOME`, or adding the directory containing java.exe to the `PATH` variable?

**Comment by ShreyaSharma-git** [comment]
@russcam I didn't have to as it was already set correctly. I just installed the Java package again

**Comment by ShreyaSharma-git** [comment]
[MSI6792a.LOG](https://github.com/elastic/windows-installers/files/3654677/MSI6792a.LOG)
Issue comes when I am installing Trial version of xpack alongside ES. I have upgraded my Java package from 8 to 13
