### ISSUE TITLE
Issue in installing ES6.5.4

### ISSUE THREAD

**Issue by ShreyaSharma-git** [elastic/windows-installers#334]
### Environment
Are you running behind a corporate proxy?-No 
Geography-India 
Expected Behaviour- Should have installed as I followed same steps last month for installation and it worked fine
Actual Behaviour- Service is not getting installed
Steps to reproduce the behaviour
Fresh install 
Download [ES6.5.4] https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.5.4.msi
Execute the msi and click on next and choose trial Xpack feature
Installation of ES Service starts
![ESFailure](https://user-images.githubusercontent.com/55779119/65572750-afd38f00-df86-11e9-95af-d6b173f75a65.

[MSI78a37.LOG](https://github.com/elastic/windows-installers/files/3651013/MSI78a37.LOG)

![ESFailure](https://user-images.githubusercontent.com/55779119/65577687-ecf14e80-df91-11e9-8a86-88ed4de8a49a.JPG)

**Comment by russcam** [comment]
This is the same issue as #333. 

```
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Install.ElasticsearchBootstrapPasswordAction.ElasticsearchBootstrapPassword
could not find java; set JAVA_HOME or ensure java is in PATH 
elasticsearch-keystore process returned non-zero exit code: 1
CustomAction ElasticsearchBootstrapPasswordAction returned actual error code 1626 (note this may not be 100% accurate if translation happened inside sandbox)
```

Either `JAVA_HOME` environment variable needs to be set e.g. to set with PowerShell

```powershell
[Environment]::SetEnvironmentVariable("JAVA_HOME",  "C:\Program Files\Java\jdk1.8.0_221\", "Machine")
```

or that the directory in which java.exe resides needs to be `PATH` environment variable.
