### ISSUE TITLE
Error installing 5.6.16 on Windows 10

### ISSUE THREAD

**Issue by marcing** [elastic/windows-installers#337]
[MSI32744.LOG](https://github.com/elastic/windows-installers/files/3709374/MSI32744.LOG)

Cheers

**Comment by ygel** [comment]
Hi @marcing, logs tell me `MSI (s) (34:C8) [22:50:20:715]: Product: Elasticsearch 5.6.16 -- Newer version already installed`. Seems like you're installing the same version again?

Is it possible for you to use latest installer version from https://www.elastic.co/downloads/elasticsearch, currently 7.4.0?

**Comment by marcing** [comment]
Dear ygel,

Yes I have also latest installed. I need both 5 and 7 for different projects - of course not at the same time, but rather stopping/starting services of 7 and 5.
It looks like from ZIP it worked.

Thank you,
Marcin

**Comment by ygel** [comment]
@marcing I'm glad you worked it out. We don't officially support side-by-side installs with the msi installer though.
