### ISSUE TITLE
An error occurred during the installation of MSI file on WIN 2012 R2 

### ISSUE THREAD

**Issue by amwlq** [elastic/windows-installers#338]
pls help.
[MSI8ebb5.LOG](https://github.com/elastic/windows-installers/files/3710470/MSI8ebb5.LOG)

**Comment by ygel** [comment]
Hello @amwlq, something is strange with the JAVA version you have installed, it reports v51.0: 
`java.lang.UnsupportedClassVersionError: org/elasticsearch/tools/java_version_checker/JavaVersionChecker : Unsupported major.minor version 51.0`

What JAVA version do you have in stalled?

**Comment by amwlq** [comment]
@ygel  thank you for reply.
I check the java version is 1.8 , I don not know why show 51.0?

C:\Users\Administrator>java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

C:\Users\Administrator>

**Comment by ygel** [comment]
Please try latest ES installer, it includes OpenJDK. If you remove JAVA_HOME variable, it should use bundled JDK.
