### ISSUE TITLE
Elastic.ProcessHosts.Process.StartupException: Could not evaluate jvm.options file: C:\Elastic\Elasticsearch\config\jvm.options

### ISSUE THREAD

**Issue by thrishod** [elastic/windows-installers#340]
Installed the Elastic search not as a service because starting a service is failing with below errors
MSI (c) (D4:70) [17:49:18:547]: Machine policy value 'DisableUserInstalls' is 0
MSI (c) (D4:70) [17:49:18:630]: SOFTWARE RESTRICTION POLICY: Verifying package --> 'C:\elasticsearch-7.4.0-windows-x86_64\elasticsearch-7.4.0.msi' against software restriction policy
MSI (c) (D4:70) [17:49:18:641]: SOFTWARE RESTRICTION POLICY: C:\elasticsearch-7.4.0-windows-x86_64\elasticsearch-7.4.0.msi has a digital signature
MSI (c) (D4:70) [17:49:21:624]: SOFTWARE RESTRICTION POLICY: C:\elasticsearch-7.4.0-windows-x86_64\elasticsearch-7.4.0.msi is permitted to run at the 'unrestricted' authorization level.
MSI (s) (F8:28) [17:57:52:063]: Product: Elasticsearch 7.4.0 -- Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start. Verify that you have sufficient privileges to start system services.

Post installing not as as a service and when tried to start manually starting the service fails with below error.
Please note i have changed the jvm.options file also with changes as suggested but still it fails
9-:-9-:-Xlog:gc*,gc+age=trace,safepoint:file="C:\Elastic\Elasticsearch\logs\gc.log":utctime,pid,tags:filecount=32,filesize=64m

Elastic.ProcessHosts.Process.StartupException: Could not evaluate jvm.options file: C:\Elastic\Elasticsearch\config\jvm.options result: Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
error:
at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)

at Elastic.ProcessHosts.Elasticsearch.Process.ElasticsearchProcess.CreateObservableProcessArguments(IEnumerable1 args) at Elastic.ProcessHosts.Elasticsearch.Process.ElasticsearchProcess..ctor(IObservableProcess process, IConsoleOutHandler consoleOutHandler, IFileSystem fileSystem, ElasticsearchEnvironmentConfiguration env, JavaConfiguration java, IElasticsearchTool jvmOptionsParser, IElasticsearchTool javaVersionChecker, ManualResetEvent completedHandle, IEnumerable1 args)
at Elastic.ProcessHosts.Elasticsearch.Process.ElasticsearchProcess..ctor(ManualResetEvent completedHandle, IEnumerable`1 args)
at Elastic.ProcessHosts.Elasticsearch.Service.ElasticsearchService.StartInteractive(ManualResetEvent handle)
at Elastic.ProcessHosts.Service.Service.Run()
at Elastic.ProcessHosts.Elasticsearch.Program.Main(String[] args)

**Comment by russcam** [comment]
> Please note i have changed the jvm.options file also with changes as suggested

Which suggested changes? It looks like an issue with assigning ~2GB heap. Can you post the whole jvm.options file?

**Comment by thrishod** [comment]
Ruscam, yes that's correct i have changed the jvm.options and reduced the heap size to 1GB.
3 lines i modified 
1. Gave correct path of gc.log with escape sequence and absolute path as shown below and
2. changed the Xmx and Xms value from 2048m to 1024m

Please let me know if i have done correctly or anything else need to be taken care in jvm.options

9-:-Xlog:gc*,gc+age=trace,safepoint:file=C:\\Elastic\\Elasticsearch\\logs\\gc.log:utctime,pid,tags:filecount=32,filesize=64m
-Xmx1024m
-Xms1024m

## JVM configuration

################################################################
## IMPORTANT: JVM heap size
################################################################
##
## You should always set the min and max JVM heap
## size to the same value. For example, to set
## the heap to 4 GB, set:
##
## -Xms4g
## -Xmx4g
##
## See https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html
## for more information
##
################################################################

# Xms represents the initial size of total heap space
# Xmx represents the maximum size of total heap space


################################################################
## Expert settings
################################################################
##
## All settings below this section are considered
## expert settings. Don't tamper with them unless
## you understand what you are doing
##
################################################################

## GC configuration
-XX:+UseConcMarkSweepGC
-XX:CMSInitiatingOccupancyFraction=75
-XX:+UseCMSInitiatingOccupancyOnly

## G1GC Configuration
# NOTE: G1GC is only supported on JDK version 10 or later.
# To use G1GC uncomment the lines below.
# 10-:-XX:-UseConcMarkSweepGC
# 10-:-XX:-UseCMSInitiatingOccupancyOnly
# 10-:-XX:+UseG1GC
# 10-:-XX:G1ReservePercent=25
# 10-:-XX:InitiatingHeapOccupancyPercent=30

## DNS cache policy
# cache ttl in seconds for positive DNS lookups noting that this overrides the
# JDK security property networkaddress.cache.ttl; set to -1 to cache forever
-Des.networkaddress.cache.ttl=60
# cache ttl in seconds for negative DNS lookups noting that this overrides the
# JDK security property networkaddress.cache.negative ttl; set to -1 to cache
# forever
-Des.networkaddress.cache.negative.ttl=10

## optimizations

# pre-touch memory pages used by the JVM during initialization
-XX:+AlwaysPreTouch

## basic

# explicitly set the stack size
-Xss1m

# set to headless, just in case
-Djava.awt.headless=true

# ensure UTF-8 encoding by default (e.g. filenames)
-Dfile.encoding=UTF-8

# use our provided JNA always versus the system one
-Djna.nosys=true

# turn off a JDK optimization that throws away stack traces for common
# exceptions because stack traces are important for debugging
-XX:-OmitStackTraceInFastThrow

# flags to configure Netty
-Dio.netty.noUnsafe=true
-Dio.netty.noKeySetOptimization=true
-Dio.netty.recycler.maxCapacityPerThread=0
-Dio.netty.allocator.numDirectArenas=0

# log4j 2
-Dlog4j.shutdownHookEnabled=false
-Dlog4j2.disable.jmx=true

-Djava.io.tmpdir=${ES_TMPDIR}

## heap dumps

# generate a heap dump when an allocation from the Java heap fails
# heap dumps are created in the working directory of the JVM
-XX:+HeapDumpOnOutOfMemoryError

# specify an alternative path for heap dumps; ensure the directory exists and
# has sufficient space
-XX:HeapDumpPath=data

# specify an alternative path for JVM fatal error logs
-XX:ErrorFile=logs/hs_err_pid%p.log

## JDK 8 GC logging

8:-XX:+PrintGCDetails
8:-XX:+PrintGCDateStamps
8:-XX:+PrintTenuringDistribution
8:-XX:+PrintGCApplicationStoppedTime
8:-Xloggc:logs/gc.log
8:-XX:+UseGCLogFileRotation
8:-XX:NumberOfGCLogFiles=32
8:-XX:GCLogFileSize=64m

# JDK 9+ GC logging
#9-:-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m
#9-:-9-:-Xlog:gc*,gc+age=trace,safepoint:file=\"C:\Elastic\Elasticsearch\logs\gc.log\":utctime,pid,tags:filecount=32,filesize=64m
#9-:-Xlog:gc*,gc+age=trace,safepoint:file="C:/Elastic/Elasticsearch/logs/gc.log":utctime,pid,tags:filecount=32,filesize=64m

9-:-Xlog:gc*,gc+age=trace,safepoint:file=C:\\Elastic\\Elasticsearch\\logs\\gc.log:utctime,pid,tags:filecount=32,filesize=64m
# due to internationalization enhancements in JDK 9 Elasticsearch need to set the provider to COMPAT otherwise
# time/date parsing will break in an incompatible way for some date patterns and locals
9-:-Djava.locale.providers=COMPAT
#-Xmx2048m
#-Xms2048m
-Xmx1024m
-Xms1024m

**Comment by russcam** [comment]
Please can you format the contents of any files displayed by surrounding in three backticks e.g.

\`\`\`
contents here
\`\`\`

This will help in making the content readable, especially if it contains characters that will be interpreted as markdown syntax.

Where have you seen these _suggested changes_? You shouldn't need to change either of these settings manually in jvm.options, since the installation takes care of them.

**Comment by ygel** [comment]
This one is related IMO, https://github.com/elastic/windows-installers/issues/315
