### ISSUE TITLE
An error occurred during the installation elastic serach 7.4.0

### ISSUE THREAD

**Issue by thrishod** [elastic/windows-installers#341]
I am an admin and i do have complete access on my windows 10 system but still getting the below error.

MSI (c) (D4:70) [17:49:18:547]: Machine policy value 'DisableUserInstalls' is 0
MSI (c) (D4:70) [17:49:18:630]: SOFTWARE RESTRICTION POLICY: Verifying package --> 'C:\elasticsearch-7.4.0-windows-x86_64\elasticsearch-7.4.0.msi' against software restriction policy
MSI (c) (D4:70) [17:49:18:641]: SOFTWARE RESTRICTION POLICY: C:\elasticsearch-7.4.0-windows-x86_64\elasticsearch-7.4.0.msi has a digital signature
MSI (c) (D4:70) [17:49:21:624]: SOFTWARE RESTRICTION POLICY: C:\elasticsearch-7.4.0-windows-x86_64\elasticsearch-7.4.0.msi is permitted to run at the 'unrestricted' authorization level.

**Comment by russcam** [comment]
These aren't errors, but MSI log messages. Can you post the whole MSI log? Is the underlying issue the same as https://github.com/elastic/windows-installers/issues/340?

**Comment by thrishod** [comment]
Hello Ruscam,
Sorry i don't have the log saved 
I have solved this issue by not installing as a service and manually starting the elastic search service.

Regards,
Thrishod
