### ISSUE TITLE
how to install filebeat and how to pipeline with the logstash

### ISSUE THREAD

**Issue by ripun9** [elastic/windows-installers#342]

**Comment by russcam** [comment]
Hi @ripun9 , 

We reserve GitHub Issues for bug reports and feature requests. It looks like you're asking a question about how to set up filebeat and logstash that is not related to the Elasticsearch Windows installer.

In order for your question to get the attention it deserves, the best place to ask it would be the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence it is more likely to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.

Thanks!
