### ISSUE TITLE
Plugin logstash-input-jms Installation Error  message: Net::OpenTimeout

### ISSUE THREAD

**Issue by thrishod** [elastic/windows-installers#343]
Hi All,
I am very newbie to ELK and my requirement is to read the messages from IBM WMQ.

I have setup the queue manager, Queue, JMS queue, Binding etc.. as needed.
In order to read messages from IBM WMQ, I believe  logstash needs a JMS Input plugin.

Honestly i am not sure which plugin should be used from the below 2 options
1. plugin : logstash_jms_ibm_mq
2. plugin :  logstash-input-jms-master
Request you to kindly suggest me which one should be used and how it can be installed and reading messages from JMS administered objects on IBM WMQ can be done.

Following options i have tried and it's throwing some error.
Downloaded the logstash-input-jms.zip and logstash-input-jms-master.zip  from  links below
https://github.com/saudurehman/logstash_jms_ibm_mq
https://codeload.github.com/logstash-plugins/logstash-input-jms/zip/master

- Installing plugin : logstash_jms_ibm_mq
Following is the command i am running and Getting the below Error
**option 1.  Command run without .zip extension logstash_jms_ibm_mq**
C:\logstash-7.4.0\logstash-7.4.0\bin>logstash-plugin install logstash_jms_ibm_mq
ERROR: Something went wrong when installing logstash_jms_ibm_mq, message: Net::OpenTimeout

**option 2 Command run with .zip extension logstash_jms_ibm_mq**
C:\logstash-7.4.0\logstash-7.4.0\bin>logstash-plugin install logstash_jms_ibm_mq.zip
ERROR: Something went wrong when installing logstash_jms_ibm_mq.zip, message: Net::OpenTimeout

- Installing plugin :  logstash-input-jms-master
C:\logstash-7.4.0\logstash-7.4.0\bin>logstash-plugin install logstash-input-jms-master
ERROR: Something went wrong when installing logstash-input-jms-master, message: Net::OpenTimeout

C:\logstash-7.4.0\logstash-7.4.0\bin>logstash-plugin install logstash-input-jms-master.zip
ERROR: Something went wrong when installing logstash-input-jms-master.zip, message: Net::OpenTimeout
For more details i have attached the plugins what is downloaded and the error screen shot from windows command console
![logstash-plugin install error](https://user-images.githubusercontent.com/56824386/67359869-1902ee00-f597-11e9-86c7-0966140c6bab.PNG)

![logstash-plugins Downloaded](https://user-images.githubusercontent.com/56824386/67359984-5a939900-f597-11e9-807d-2b04deacdec2.PNG)

![JMS](https://user-images.githubusercontent.com/56824386/67360554-dcd08d00-f598-11e9-94f0-18f00f7e082c.PNG)

**Comment by russcam** [comment]
Hi @thrishod , 

We reserve GitHub Issues for bug reports and feature requests. It looks like you're asking a question about setup related to Logstash that isn't related to the Elasticearch Windows installer.

In order for your question to get the attention it deserves, the best place to ask it would be the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence it is more likely to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.

Thanks!
