### ISSUE TITLE
Not able to Install Elastic search in Windows 7. 

### ISSUE THREAD

**Issue by Baburamandxb** [elastic/windows-installers#345]
### Steps to reproduce the behaviour

1.
2.
3.

**Comment by ygel** [comment]
Hello @Baburamandxb, thank you for reporting this, however we'd need a bit more info about what is happening.

**Comment by Baburamandxb** [comment]
[MSIe8656.LOG](https://github.com/elastic/windows-installers/files/3836493/MSIe8656.LOG)
![Untitled](https://user-images.githubusercontent.com/57672091/68678646-c3a77480-0577-11ea-9253-59ad40340b0a.png)

[MSI2b1e8.LOG](https://github.com/elastic/windows-installers/files/3836498/MSI2b1e8.LOG)


please find the screenshot and logs.

**Comment by ygel** [comment]
Logs show that ES service failed to start. What do ES logs say?

**Comment by Baburamandxb** [comment]
I don't have ES logs. when i click on ESlog file it doesn't redirect

**Comment by ygel** [comment]
@Baburamandxb, 
Please try latest ES version, also please take a look at the issues below and ones liked in the comments: https://github.com/elastic/windows-installers/issues/349#issuecomment-578141233, https://github.com/elastic/windows-installers/issues/315.
There might be other related closed issues please search those as well.
