### ISSUE TITLE
Error when installing Elastic 5.5.1 to Windows Server 2019 with OpenJDK 13. Reports issue with Elastic API

### ISSUE THREAD

**Issue by eschullek** [elastic/windows-installers#346]
Installed elastic on windows server 2019. Reported error with one of the Elastic API's see log attached. 
[Elastic installer log 11_15.txt](https://github.com/elastic/windows-installers/files/3853178/Elastic.installer.log.11_15.txt)

**Comment by ygel** [comment]
Hello @eschullek, thank you for reporting this. I took a quick look at the logs and saw this: 

    The account name is invalid or does not exist, or the password is invalid for the account name specified

Please check account name and password you're using.
Please consider using a current version of Elasticsearch as well: https://www.elastic.co/downloads/

**Comment by ygel** [comment]
Closing as stale.
