### ISSUE TITLE
Error when installing Elastic 7.2.1 to Windows Server 2008 with OpenJDK 11

### ISSUE THREAD

**Issue by Wanghengfeng** [elastic/windows-installers#349]
An error occurred during the installation of MSI file
please help

[MSI90170.LOG](https://github.com/elastic/windows-installers/files/3994583/MSI90170.LOG)

**Comment by AlexanderAnatolich** [comment]
Вы можете посмотреть на то, как я решил похожую проблему.
#348 
Попробуйте задать такую-же конфигурацию.
В процессе установки: если конфигурация будет перезаписана, измените её опять и вручную перезапустите службу Elasticsearch. Это может сработать, так как во время установки происходит несколько попыток установления соедения и вы можете попробовать успеть сделать эти действия.

**Comment by AlexanderAnatolich** [comment]
It is also clear from your logs that you probably do not have access to manage system services.

**Comment by AlexanderAnatolich** [comment]
It is also clear from your logs that you probably do not have access to manage system services.

**Comment by ygel** [comment]
Looking at the logs, these two closed issued might be related:
https://github.com/elastic/windows-installers/issues/238
https://github.com/elastic/windows-installers/issues/215
