### ISSUE TITLE
This is very unfortunate and not something we'd hope to repeat.  Please let us know by filing an issue on our GitHub issues page.

### ISSUE THREAD

**Issue by idanelbaz** [elastic/windows-installers#350]
### Steps to reproduce the behaviour

1.
2.
3.

**Comment by russcam** [comment]
Hi, 

Please attach the MSI log file for the failed installation; a log file for the installation process can be found within the `%TEMP%` directory, with a randomly generated name adhering to the format `MSI<random>.LOG`. Without this log file, it's not possible to determine why the installation failed.

**Comment by ygel** [comment]
This seems to be a machine-generated issue.
