### ISSUE TITLE
An error occurred during installation! This is very unfortunate and not something we'd hope to repeat.  Please let us know by filing an issue on our GitHub issues page.

### ISSUE THREAD

**Issue by theparagsinha** [elastic/windows-installers#352]
Are you running behind a corporate proxy? 
No
Where are you based geographically? 
Gurgaon, India

### Expected Behaviour
Expected a successful installation

### Actual Behaviour
Fails during installation, while trying to start service

### Steps to reproduce the behaviour
Every time I try to install, it's the same issue. 

Is this a fresh install or an upgrade?
Fresh install
[MSI2da71.LOG](https://github.com/elastic/windows-installers/files/4090187/MSI2da71.LOG)
![elasticSearch](https://user-images.githubusercontent.com/51442749/72791614-9fde6a00-3c5d-11ea-8199-641cdd9322d4.PNG)

**Comment by ygel** [comment]
Hello @theparagsinha, looking at the logs, I see this error message: 

```log
could not find java in JAVA_HOME at "C:\Program Files (x86)\Java\jre1.8.0_211\bin\java.exe
```

You might have a leftover `JAVA_HOME` from a previous Java install.

**Comment by theparagsinha** [comment]
Hi @ygel 
Thanks for that. 
I've fixed the JAVA_HOME path now but it still seems to fail during installation. Log file attached.
Can you please it a look?
[MSI149d.LOG](https://github.com/elastic/windows-installers/files/4096054/MSI149d.LOG)

**Comment by ygel** [comment]
@theparagsinha, have you specified a custom Windows account for ES service to run under? Log now shows that one of the password related steps failed. If you did, Windows account must have "logon as service" right assigned.

```
ElasticsearchBootstrapPasswordAction returned actual error code 1626 
```

and then service failed to start:

```
Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.
```

**Comment by prince90617** [comment]
![elasticInstallError](https://user-images.githubusercontent.com/15924634/75243218-7f22aa80-57ef-11ea-9efa-d0118bfb6d77.PNG)

I am also facing the same issue.
