### ISSUE TITLE
Error: Could not create the Java Virtual Machine in Windows 10

### ISSUE THREAD

**Issue by fernandovictor013** [elastic/windows-installers#355]
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized option: -
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by ygel** [comment]
Hello @fernandovictor013 there is not enough information to diagnose. Please attach MSI and ES logs.

**Comment by ygel** [comment]
Closing as stale
