### ISSUE TITLE
ERROR: The Elasticsearch service on local computer started and then stopped.

### ISSUE THREAD

**Issue by vrnshrm850** [elastic/windows-installers#356]
![image](https://user-images.githubusercontent.com/20091561/77029822-cf41f680-69c2-11ea-83d0-9aba3b020daa.png)
![image](https://user-images.githubusercontent.com/20091561/77029929-2051ea80-69c3-11ea-955f-a6d4ab44545c.png)

**Comment by ygel** [comment]
Hello @vrnshrm850, thank you for reporting his. Without the log files it is impossible to tell what is wrong. Please attach `elasticsearch.log` file and we'll take a look.
