### ISSUE TITLE
Elastic Search installation KO !

### ISSUE THREAD

**Issue by LearnElasticSearch** [elastic/windows-installers#357]
Hi 

I try to install ElasticSearch on my laptop (Windows 10) , and i obtain this :

![image](https://user-images.githubusercontent.com/62663707/77563723-efd9e700-6ec1-11ea-8569-e1a5867cf9e4.png)

The elastic search log can't be open , and i join you the installation log.

The service start and immediately stop..
[MSlfe7f2.txt](https://github.com/elastic/windows-installers/files/4382313/MSlfe7f2.txt)

How can i fix it ?

Thanks

Regards

**Comment by ygel** [comment]
Hello @LearnElasticSearch , thank you for reporting this. Looking at the logs, it appears your `LocalSystem` account lacks sufficient permissions to start services.

```
MSI (s) (50:A4) [09:02:13:131]: Executing op: 
ServiceInstall(Name=Elasticsearch, DisplayName=Elasticsearch,
ImagePath="C:\Program Files\Elastic\Elasticsearch\7.6.2\bin\elasticsearch.exe",
ServiceType=16,StartType=2,ErrorControl=32769,,Dependencies=[~],,StartName=.\LocalSystem,
Password=**********,Description=You know, for Search.,,)

Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  
Verify that you have sufficient privileges to start system services.

```
