### ISSUE TITLE
An error occurred during installation

### ISSUE THREAD

**Issue by JavierBermejo** [elastic/windows-installers#358]
### Environment

No Proxy

Location: Seville, Spain

### Expected Behaviour
Successfully installation
### Actual Behaviour
Fails during installation
### Steps to reproduce the behaviour
When i try to install always apear the same error

Fresh install

[MSI2da71.LOG](https://github.com/elastic/windows-installers/files/4467281/MSI2da71.LOG)
![image](https://user-images.githubusercontent.com/33762505/79081348-e4d5e200-7d1c-11ea-9d9a-f43d6eee24a1.png)

**Comment by tdsrhh** [comment]
[MSIdd72b.LOG](https://github.com/elastic/windows-installers/files/4473996/MSIdd72b.LOG)

I experience exacly the same

**Comment by ygel** [comment]
Hello @JavierBermejo, thank you for reporting this. Error message in your logs [1] lead me to believe that at one point you had Java 8 installed and then removed it. JAVA_HOME variable was left behind though. Try removing this variable and running the installer again.

[1] "could not find java in JAVA_HOME at "C:\Program Files (x86)\Java\jre1.8.0_211\bin\java.exe""

**Comment by ygel** [comment]
Hello @tdsrhh, your issue is different. Seems like you either changed the account and/or password for the account you'd like Elasticsearch to run under [2][3]. Please verify that or try running the installer with default settings.

[2] CustomAction ElasticsearchBootstrapPasswordAction returned actual error code 1626 
[3] Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.

**Comment by tdsrhh** [comment]
Hi

I tried with default settings an reducing the heap size to 512. Then it works… Great.

**Comment by chao20150911** [comment]
Hi, 
I got the same error. I used msi file to install Elasticsearch on Windows 2016. 
Please help to check the log.
[MSIbbd6c.LOG](https://github.com/elastic/windows-installers/files/4529227/MSIbbd6c.LOG)

**Comment by ygel** [comment]
Hello @chao20150911 your log indicates lack of  permissions as well:
```Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.```

**Comment by ygel** [comment]
I am going to close this issue, as it notifies other people, please open a new one if you still experience problems.
