### ISSUE TITLE
7.6.2-installation failed on Windows2016

### ISSUE THREAD

**Issue by chao20150911** [elastic/windows-installers#359]
Hi, 

I tried to fresh install the latest version on Windows2016, chose my local admin account, and passed the validation. I think permission should be ok. 
Attaching the error capture and installation log, please help to check.

[MSId33f5.LOG](https://github.com/elastic/windows-installers/files/4529429/MSId33f5.LOG)

![image](https://user-images.githubusercontent.com/64266466/80222486-e3dc7300-8681-11ea-871f-02a25d1bb052.png)

**Comment by ygel** [comment]
Hello @chao20150911 Error message in this log file is the same `Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.`

Do you install with default settings or customize paths and/or password?
I see this in the log as well `E:\Program Files (x86)\ProgramData\Elastic\Elasticsearch\config.`
Configuration should not be in Program Files.

**Comment by chao20150911** [comment]
My C driver has no enough space, so I changed to E driver.
I changed to E:\Elastic\Elasticsearch\config, validated the administrator account and password.
re-try the installation but I got the same result.

![1](https://user-images.githubusercontent.com/64266466/80226770-c4484900-8687-11ea-8a60-27af0215aaf6.PNG)
![2](https://user-images.githubusercontent.com/64266466/80226773-c4e0df80-8687-11ea-975f-687212003183.PNG)
![3](https://user-images.githubusercontent.com/64266466/80226776-c5797600-8687-11ea-9076-b637d62bdc94.PNG)
[MSI2b7b8.LOG](https://github.com/elastic/windows-installers/files/4529691/MSI2b7b8.LOG)

**Comment by ygel** [comment]
I see the same error `Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.`

Is there any specific reason you're using "administrator" and not "Local System" account to run the service

**Comment by chao20150911** [comment]
Referring to your advice, I re-tried to use Local System to install, but no change to the result.

**Comment by ygel** [comment]
What happens if you use Network Service and *uncheck*  the "start service after this installation is complete"? Try starting service manually and collecting `elasticsearch.log`.

**Comment by chao20150911** [comment]
It worked now!
