### ISSUE TITLE
Neither ZIP installation nor the MSI work on my windows 10 Home P.C

### ISSUE THREAD

**Issue by Shropshire** [elastic/windows-installers#361]
### Environment

no
U.K

### Actual Behaviour
Failed
### Steps to reproduce the behaviour
Install 7.6.2
yes

1.
2.
3.

![image](https://user-images.githubusercontent.com/6126202/80815115-f5afa000-8bc4-11ea-9182-203dd36c8584.png)

**Comment by ygel** [comment]
Hello @Shropshire, thank you reporting this. Without the logs I'm afraid it's impossible to tell what's going on. Your screenshot shows "Open the xxx log file", please attach logs that these links lead to.

**Comment by npfernandeztheillet** [comment]
Hi @Shropshire, how are you? I hope you are doing wel.

Do you have the last version of Java SE? After install the last version, check the JAVA_HOME env variable and if it is not updated, update it with the folder of the last version.

After that try to reinstall ES using the .msi installer

**Comment by ygel** [comment]
I'll close this issue due to lack of response. Once 7.8.1 and/or 7.9.0 released, please upgrade and open a new issue if you're still experiencing the problem. This is most likely fixed with in #368.
