### ISSUE TITLE
(Re-) Installation with msi-package failed

### ISSUE THREAD

**Issue by kempea** [elastic/windows-installers#362]
### Environment

 yes
 Europe, Germany

### Expected Behaviour
Successful re-installation with changed parameters after a first successful install with standard parameters

### Actual Behaviour
I failed to re-install Elasticsearch 7.6.2 on Windows 10.

One step before I've managed to finish an installation and start it without any problems. In this case I haven't done any modifications on the standard install provided in the msi installer. "curl -X GET http://localhost:9200/" and Kibana access worked fine.

Afterwards I tried to change the host address from localhost to xx.xx.xx.xx. That didn't work:
[...]
[1] bootstrap checks failed
[1]: the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured
[...]

So I re-installed the msi package again with default values and a little more memory again (Install as a service, use local system account, role Data, memory 4GB, no network host, no plugins, basic licence)

### Steps to reproduce the behaviour

 2nd try of a fresh install

1. Installation Elasticsearch 7.6.2 on Windows 10 / msi-package
2. Remove installation using the msi-installer
3. Re-install the same msi-package after removing original elasticsearch directory, remaining elastic stuff in C:\Temp, and checking the repository (no editing)
[elasticsearch.log](https://github.com/elastic/windows-installers/files/4581056/elasticsearch.log)
[MSIb18d9.LOG](https://github.com/elastic/windows-installers/files/4581059/MSIb18d9.LOG)

**Comment by ygel** [comment]
Hello @kempea, my suggestion is to make sure you have valid values for mentioned `discovery.-` and `cluster.-` variables and ES indeed loads the files you assume it does from `C:\ProgramData\Elastic\Elasticsearch\config` (per log)

I'll close this issue, once 7.8.1 and/or 7.9.0 released, please upgrade and open a new issue if you're still experiencing the problem.
