### ISSUE TITLE
Installation error 7.7.0 on Windows

### ISSUE THREAD

**Issue by fmdelvalle** [elastic/windows-installers#369]
It seems an error starting the service.

### Steps to reproduce the behaviour

1.Fresh
[MSIc9a41.LOG](https://github.com/elastic/windows-installers/files/4649776/MSIc9a41.LOG)

2.
3.

**Comment by reighnman** [comment]
Likely duplicate of #368

**Comment by russcam** [comment]
Closing this as duplicate of #363. Please see workaround: https://github.com/elastic/windows-installers/issues/363#issuecomment-631158455
