### ISSUE TITLE
Error to install version 7.7.0 on windows 8.1 v7.7.0

### ISSUE THREAD

**Issue by IMaksone** [elastic/windows-installers#374]
![image](https://user-images.githubusercontent.com/55435592/83524722-a96dbd80-a4ec-11ea-930d-0aaae43e671c.png)

I tried to install Elasticsearch 7.7.0 msi on my computer. I am in Belarus.
I tried to install twice. The first time with custom settings, the second with all the default installer settings. The result is the same.

[MSId2081.LOG](https://github.com/elastic/windows-installers/files/4717355/MSId2081.LOG)

**Comment by ygel** [comment]
Please take a look at https://github.com/elastic/windows-installers/pull/368, There's a workaround for `jvm.options.d` until the next release where this is fixed
