### ISSUE TITLE
Cannot run ElasticSearch on WIN10 laptop

### ISSUE THREAD

**Issue by Hochberger** [elastic/windows-installers#375]
### Environment

Win 10 home 64bit laptop, JAVA JDK 14.0.1

### Expected Behaviour

Run Elastic Search as WIN service

### Actual Behaviour

Installation failed when installing with the msi file. When using admin prompt and zip package, service just doesn't launch without any error message. 

### Steps to reproduce the behaviour

First time installing ElasticSearch. Windows installation is fresh as well. 

Install log included attached.

[MSI15f36.LOG](https://github.com/elastic/windows-installers/files/4718378/MSI15f36.LOG)

**Comment by ygel** [comment]
This is most likely fixed with in #368. Once 7.8.1 and/or 7.9.0 released, please upgrade and open a new issue if you're still experiencing the problem.
