### ISSUE TITLE
windows server 2012 setup Elasticsearch7.7.0.msi But cannot start service.

### ISSUE THREAD

**Issue by jinyefeng** [elastic/windows-installers#376]
### Environment
Windows Server 2012

[MSIa7e97.LOG](https://github.com/elastic/windows-installers/files/4722391/MSIa7e97.LOG)

### Steps to reproduce the behaviour

1. setup according to https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html
2. At last, show me "An error occured during installation"

I found that Error in rollback skipped. 

[Uploading MSIa7e97.LOG…]()

**Comment by ygel** [comment]
Hello @jinyefeng, this might be the same issue as #363, `elasticsearch.log` file would provide better context.

**Comment by ygel** [comment]
This is most likely fixed with in #368. Once 7.8.1 and/or 7.9.0 released, please upgrade and open a new issue if you're still experiencing the problem.
