### ISSUE TITLE
An error occured during Installation using msi package (W10)

### ISSUE THREAD

**Issue by kmlan** [elastic/windows-installers#382]
### Environment

No proxy
Location: AU

### Expected Behaviour
Install

### Actual Behaviour
fail

### Steps to reproduce the behaviour
Easy.
Make new data, log, conf folders.
Installer does not set write access to the local users group but adding and re-running installer does not help.

1. Fresh install re-run over itself
2. Completed install using default folder locations and uninstalled with reboot
3. Install again with moved data, conf, log folders location set with write perms - failed
[MSI54c70.LOG](https://github.com/elastic/windows-installers/files/4883785/MSI54c70.LOG)

**Comment by ygel** [comment]
fixed in https://github.com/elastic/windows-installers/pull/379
