### ISSUE TITLE
Installation fails - windows 

### ISSUE THREAD

**Issue by hardikpancholi** [elastic/windows-installers#387]
I downloaded elasticsearch-7.8.1 msi and going to all the steps. it start installation and I got the error.

### Environment
Windows 10 Pro

India

### Actual Behaviour
Installation fail
### Steps to reproduce the behaviour
Downloaded msi from here
https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.8.1-windows-x86_64.zip
followed the steps and get error

1. Fresh installation
2. Attached log file.
3.

![image](https://user-images.githubusercontent.com/15901887/89415396-68db2c00-d749-11ea-8879-c2bb9ec09ea9.png)
[MSI8d68f.LOG](https://github.com/elastic/windows-installers/files/5028521/MSI8d68f.LOG)

**Comment by gbk1811** [comment]
Receiving the same error while installing. Please help. Thanks

**Comment by ravi-burugu-rhym** [comment]
Same problem for me too.

**Comment by ygel** [comment]
Hello, thank you for reporting this, we'll look at this as soon as possible.

**Comment by yirmio** [comment]
same problem for me too

**Comment by yirmio** [comment]
> same problem for me too

also failed for 7.8.0 msi
windows server 2012R2

**Comment by MGAbbasi123** [comment]
getting same error

**Comment by ygel** [comment]
> [MSI8d68f.LOG](https://github.com/elastic/windows-installers/files/5028521/MSI8d68f.LOG)

For this log file the error is: 
```
"could not find java in JAVA_HOME at "C:\Program Files\Java\jre1.8.0_241\bin\bin\java.exe"" 
```

For v7.8.1, JDK is bundled with the installation, please do one of the following:
- make sure that you indeed have JAVA installed in `JAVA_HOME` above
- remove `JAVA_HOME` variable and let bundled JDK take over

**Comment by ygel** [comment]
@MGAbbasi123 @yirmio @ravi-burugu-rhym @gbk1811 
Please open separate issues and attach log files for MSI *and* ideally Elasticsearch itself , without log files it's impossible to tell what went wrong in your specific cases.
