### ISSUE TITLE
To add to the description requirement for a software environment to build the project

### ISSUE THREAD

**Issue by eugenesavenko** [elastic/windows-installers#39]
I would like to know a software developer's environment, because now when you build the project in their own surroundings constantly run into incompatibilities of the platforms or libraries.

**Comment by russcam** [comment]
@eugenesavenko A developer set up guide would be useful. To get you started, you'll need an IDE for C# - I'd recommend either JetBrains Rider or Visual Studio 2017. 

You'll also need the build tools to build C#6, which you'll get if you install Visual Studio 2017.

The `build.bat` script in the root can be used to build the project. For a list of targets and their options, you can run

```sh
build.bat help
```

To build just the Elasticsearch installer for a specific version without running unit tests

```sh
build.bat buildinstallers es 5.4.1 skiptests
```

**Comment by codebrain** [comment]
Closing.
