### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by barran01** [elastic/windows-installers#392]
Hi, I tried an installation for elasticsearch 7.92 in windows 10 using the msi. installer and it returned an error.

log files are attached
[MSI34a7.LOG](https://github.com/elastic/windows-installers/files/5311206/MSI34a7.LOG)
[elasticsearch.log](https://github.com/elastic/windows-installers/files/5311210/elasticsearch.log)

**Comment by ygel** [comment]
Hello @barran01, your MSI log contains error below (it thinks it failed to start service), yet your ES log has no errors and looks like service has started. Can you confirm you still experience this issue?

```
MSI (s) (40:DC) [12:13:30:007]: Product: Elasticsearch 7.9.2 -- Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.
```
