### ISSUE TITLE
Installation failed (msi)

### ISSUE THREAD

**Issue by jm-castadere** [elastic/windows-installers#393]
Tried installing it on windows 10 and failed, attached installation log file.

[MSIf0c13.LOG](https://github.com/elastic/windows-installers/files/5319383/MSIf0c13.LOG)
![2020-10-02 18_43_08-Elasticsearch 7 9 2 Installation](https://user-images.githubusercontent.com/55451448/94950574-203eb580-04e3-11eb-9e5b-46a9b4433a28.png)

**Comment by elrosi** [comment]
Hi, 
I have the same error.
[MSI6b67.LOG](https://github.com/elastic/windows-installers/files/5400517/MSI6b67.LOG)

**Comment by ygel** [comment]
Hello @jm-castadere, your MSI log says this: 
```
"could not find java in JAVA_HOME at "K:\AzureDevOpsData\Java\jre\bin\java.exe""
```

I think MSI tries to bootstrap ES password and fails because `JAVA_HOME`  is invalid

**Comment by ygel** [comment]
Hello @elrosi, your MSI log has a generic error: 
```
MSI (s) (54:7C) [11:05:54:214]: Product: Elasticsearch 7.9.2 -- Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.
```

Try installing without the plugins, because I see a warning in the output:
```
-> Downloading ingest-attachment from elastic
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
-> Installed ingest-attachment
* java.lang.RuntimePermission accessClassInPackage.sun.java2d.cmm.kcms
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.security.SecurityPermission createAccessControlContext
* java.security.SecurityPermission insertProvider
* java.security.SecurityPermission putProviderProperty.BC
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
```

**Comment by elrosi** [comment]
Hi @ygel 

After deleting the flood directory C:\ProgramData\Elastic\Elasticsearch\ the installation was successful.
I also changed the main installation directory to C:\elastic

**Comment by ygel** [comment]
Sounds good @elrosi, thank you for following up.
