### ISSUE TITLE
Add pre-requisite validation for installed Java version

### ISSUE THREAD

**Issue by gmarz** [elastic/windows-installers#4]
When detecting whether Java is installed and setting `JAVA_HOME` we should also make sure it's a version supported by Elasticsearch, and fail preflight validation if it's not.

I hit this when I installed scala via chocolately, which installed an old JRE version of Java and covertly overwrote my JAVA_HOME variable.

**Comment by gmarz** [comment]
Correction: JAVA_HOME wasn't overwritten.  Our Java selection logic chose 1.7 over 1.8 -- so we should also always choose the latest version.

**Comment by Mpdreamz** [comment]
Closing this, we look at `CurrentVersion` in the registry, i don't think we should overrule the Java installers logic here. 

Parking maintaining a JVM compatibilty list untill we see it becoming an issue in the wild
