### ISSUE TITLE
JvmOptionsParser needs to be invoked with the plugins directory

### ISSUE THREAD

**Issue by pugnascotia** [elastic/windows-installers#402]
As of Elasticsearch 7.11.0, the `JvmOptionsParser` class needs to be passed both the config directory and the plugins directory as command line arguments. This was missed from the work that added this requirement - https://github.com/elastic/elasticsearch/pull/63620.

**Comment by ygel** [comment]
Thank you!

**Comment by UkrZilla** [comment]
What is temporary fix or workaround to install/update 7.11 on Windows?
