### ISSUE TITLE
Issue while installing ElasticSearch version 7.10.2

### ISSUE THREAD

**Issue by Sherine1** [elastic/windows-installers#406]
### Environment

Local Windows environment

**Fresh Install** 

1.Unzipped elasticsearch-7.10.2-windows-x86_64

2. ran cd elasticsearch-7.10.2\bin   then .\elasticsearch.bat

3.Error Occurred 

Error: Could not find or load main class org.elasticsearch.common.settings.KeyStoreCli
Caused by: java.lang.NoClassDefFoundError: org/elasticsearch/cli/LoggingAwareMultiCommand
Error: Could not find or load main class org.elasticsearch.bootstrap.Elasticsearch
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.bootstrap.Elasticsearch

![elastic](https://user-images.githubusercontent.com/79335422/108556496-c0b13d00-72ff-11eb-9b22-7e190e31f5c6.png)

my java version
![java](https://user-images.githubusercontent.com/79335422/108556406-a11a1480-72ff-11eb-9df7-28b2c5641429.png)

**Comment by Sherine1** [comment]
any help??

**Comment by ygel** [comment]
Hello @Sherine1, does it happen on the latest v7.11.1  or you have to use v7.10.2 specifically?

**Comment by Sherine1** [comment]
no it also happens in 7.11.1 @ygel  also i tried downloading from the .msi it also throw an error.

**Comment by ygel** [comment]
> no it also happens in 7.11.1 @ygel also i tried downloading from the .msi it also throw an error.

Can you attach the logs please? `elasticsearch.log`, MSI log created as described here: https://github.com/elastic/elastic-stack-installers#capturing-logs

**Comment by Sherine1** [comment]
[MSI85d8c.LOG](https://github.com/elastic/windows-installers/files/6037350/MSI85d8c.LOG)

here you go @ygel

**Comment by ygel** [comment]
Relevant lines from the log file:
```
The cabinet file 'Elasticsearch_7.10.2_.cab' required for this installation is corrupt and cannot be used. This could indicate a network error, an error reading from the CD-ROM, or a problem with this package.
```
Seems like MSI got corrupted during download. Could .zip have been too? Is your internet connection stable? Do you have any software that is overzealous to examine the contents of files you download?

**Comment by Sherine1** [comment]
@ygel  you were right ,something was wrong with my internet connection, i tried my 4G and it worked!
thanks for your help.
