### ISSUE TITLE
Elasticsearch 7.15.0 installer throwing Exception during custom action ElasticsearchSetBootstrapPassword

### ISSUE THREAD

**Issue by coderjoe** [elastic/windows-installers#427]
### Environment

Windows 10 based in the US both on corporate VPN and not.
Fresh install of 7.15.0.

### Expected Behaviour

Elasticsearch should install without failing due to unexpected exceptions.

### Actual Behaviour

Installer log file: 
[MSI1a543.LOG](https://github.com/elastic/windows-installers/files/7221046/MSI1a543.LOG)

Elasticsearch begins to install but appears to fail with the following stack trace:

```
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Immediate.ElasticsearchSetBootstrapPasswordAction.ElasticsearchSetBootstrapPassword
Exception thrown by custom action:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'Elastic.InstallerHosts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Access is denied.
   at Elastic.Installer.Msi.Elasticsearch.CustomActions.Immediate.ElasticsearchSetBootstrapPasswordAction.ElasticsearchSetBootstrapPassword(Session session)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object parameters, Object arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object parameters, CultureInfo culture)
   at Microsoft.Deployment.WindowsInstaller.CustomActionProxy.InvokeCustomAction(Int32 sessionHandle, String entryPoint, IntPtr remotingDelegatePtr)
CustomAction ElasticsearchSetBootstrapPasswordAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 18:00:26: ElasticsearchSetBootstrapPasswordAction. Return value 3.
```

### Steps to reproduce the behaviour

Fresh install of 7.15.0

1. Download the Elasticsearch 7.15.0 install MSI
2. Run the installer user interface
3. Choose all default options and begin the install
4. Installer hangs at the verification stage and eventually fails

**Comment by ygel** [comment]
Hello @coderjoe, unfortunately I was not able to repro the issue. To give you some background on what happens at this step: MSI starts ES process and tries to ping an endpoint to bootstrap passwords. This might be a network issue.

**Comment by coderjoe** [comment]
From the exception I was presuming it was just an assembly binding issue. If there's anything I can help to do to triage the problem please do let me know. My co-workers and I are all having the issue so it may very well be based on our corporate setup.

**Comment by coderjoe** [comment]
We've migrated our environment and are no longer facing this issue. We've also long since migrated to later versions.
Any objections to just closing this since it is not reproduceable?

**Comment by coderjoe** [comment]
Closing as there was no objection for a few months.
