### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/windows-installers#45]
* [x] Add a note about uninstalling removing the data/log/and config folder
* [x] New gif for the help fly outs 
* [x] Make a gif for the installation done image (show off that animation 🌈 ⭐️ 🌠 🦄 magic)

**Comment by russcam** [comment]
I had a gif for the installation; I didn't add it as it was ~5MB IIRC 😄

**Comment by russcam** [comment]
[Note about installation is in the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/windows.html#uninstall-msi-gui)

**Comment by russcam** [comment]
Added a new gif to the README page in https://github.com/elastic/windows-installers/commit/c4ba9fb4c8fd684980eea8e3f5140b90d327e4ea
