### ISSUE TITLE
Support configuration file as a PROPERTY

### ISSUE THREAD

**Issue by russcam** [elastic/windows-installers#46]
From https://github.com/elastic/windows-installers/issues/12#issuecomment-304460377

Support a config file that can hold all the parameters and pass it to the installer, instead of individually passing them to MSIEXEC as parameters. For example 

```bat
start /wait msiexec.exe /i elasticsearch-5.5.0.msi /qn CONFIGPATH="C:\Temp\Myconfig.ini"
```

**Comment by ygel** [comment]
I noted this to be looked at.
