### ISSUE TITLE
Allow other choices for STARTWHENWINDOWSTARTS as well

### ISSUE THREAD

**Issue by saudurehman** [elastic/windows-installers#50]
Allow other choices for STARTWHENWINDOWSTARTS as well e.g Automatic (Delayed start)

**Comment by codebrain** [comment]
The list of service start types:

Disabled
Manual
Automatic
Automatic (Delayed Start)
Manual (Trigger Start)
Automatic (Trigger Start)

It seems reasonable to add the Automatic (Delayed Start) to the MSI (@russcam ?) but for the triggered starts it could be argued that this is best left to the administrator.

**Comment by codebrain** [comment]
Perhaps consider calling the sc.exe post-installation to set this parameter:

sc config SVCNAME start= delayed-auto

(Note the space before delayed-auto)

**Comment by russcam** [comment]
the starting state of the service maps to [`ServiceStartMode`](https://msdn.microsoft.com/en-us/library/system.serviceprocess.servicestartmode(v=vs.110).aspx), with the three applicable options being:

- `Automatic`
- `Disabled`
- `Manual`

the `Start the service when Windows starts` maps to `Automatic` when checked and `Manual` when unchecked. The only other `start` parameter that applies is [`delayed-auto`](https://technet.microsoft.com/en-us/library/cc990290(v=ws.11).aspx#Anchor_1) which would need to be applied with `sc config` as you've suggested, if the installer were to do it. 

My personal opinion on this is that it's quite an additional bit of complexity to the installer for something that can be easily changed after installation with 

```
sc config Elasticsearch start= delayed-auto
```

throughts @Mpdreamz @eskibars?

**Comment by eskibars** [comment]
I can't think of a great reason to make `delayed-auto` the default behavior: people running Elasticsearch on a production server probably want it up ASAP, and `delayed-auto` would lengthen the time (by default, 2 minutes) to get it up and running.  I've heard of [reasons why it's more secure to start as delayed-auto](https://blogs.technet.microsoft.com/askperf/2008/02/02/ws2008-startup-processes-and-delayed-automatic-start/), which is the only reason I can think of to incur the delay, though the cost/benefit is a bit difficult to justify IMO.

@saudurehman is there a particular reason you want other options?  Any particular option you're looking for?

**Comment by codebrain** [comment]
Labelling as a `discussion` for potential `enhancement`

**Comment by russcam** [comment]
Closing this as it is not something that is likely to be implemented.
