### ISSUE TITLE
An error occured during installation!

### ISSUE THREAD

**Issue by ElasticSearchLearner** [elastic/windows-installers#53]
Here is the error: This is very unfortunate and not something we'd hope to repeat.  Please let us know by filing an issue on our GitHub issues page.
However when I tried to install without plugins, I was able to install it. I uninstalled and tried to install with plugins. How can I resolve this error?
[MSIc0e39.txt](https://github.com/elastic/windows-installers/files/1129052/MSIc0e39.txt)

**Comment by codebrain** [comment]
Looking at the log file, it would appear that this is causing the problem with the installation:

```
[0] installing x-pack installing x-pack
Exception in thread "main" java.net.UnknownHostException: artifacts.elastic.co
```
Is that host (artifacts.elastic.co) resolvable and reachable from the machine you are trying to install on?

**Comment by Mpdreamz** [comment]
We tried to catch cases where artifacts.elastic.co can not resolved early on with: https://github.com/elastic/windows-installers/pull/34

But thats never going to be 100% accurate, perhaps we can somehow surface this particular error and provide a diagnosis on the error result screen.

**Comment by tclancy** [comment]
Not much of a "fix" but I tried uninstalling (after stopping the service I'd hand-started) and reinstalling and that worked. The only thing I did differently the second time was to change the `Node name:` value from the default of MACHINENAME to something else. This was on Windows 7.

**Comment by russcam** [comment]
@tclancy that doesn't sound like the same issue - did you also see 
```
[0] installing x-pack installing x-pack
Exception in thread "main" java.net.UnknownHostException: artifacts.elastic.co
```

in the MSI log?

**Comment by tclancy** [comment]
@russcam Any idea where I would find that log now? I don't see an obvious candidate in `C:\Users\<username>\AppData\Local\Temp` and am not sure where to check in Event Viewer.

**Comment by russcam** [comment]
@tclancy You can find event logs under `Event Viewer` > `Windows Logs` > `Application`. MSI related logs will have source of `MsiInstaller` and `ElasticsearchMsiInstaller` (specifically for the Elasticsearch Installer):

![image](https://user-images.githubusercontent.com/208231/30007704-3e56cf96-9158-11e7-99d9-758c5c133932.png)

**Comment by russcam** [comment]
@ElasticSearchLearner, I suspect you may have encountered this issue when running the installer behind a proxy that blocked access to `artifacts.elastic.co`. 5.6.4 and 6.0.0-rc2 onwards have the ability to specify a proxy to use through which to download plugins. Would you like to give either a try, supplying proxy credentials?

**Comment by codebrain** [comment]
Closing as OP hasn't responded for 6+ months.
