### ISSUE TITLE
MSI installation requires administrator rights

### ISSUE THREAD

**Issue by fbaligand** [elastic/windows-installers#54]
**Elasticsearch version**: 
5.5.0

**OS version** :
Windows 7

**Description of the problem including expected versus actual behavior**:
When launching MSI installation, when I click on "INSTALL" button, a windows popup is launched which requires an Administrator authentication.
Despite I don't ask to start elasticsearch as a service.
That's a problem for people who has not Administrator rights on their windows hosts (like me).

=> Could you please not require Administrator rights when "start as a service" is not checked ?

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. launch MSI
 2. define locations where I have write access
 3. disable "start as a windows service"
4. do not check any plugin
5. click on INSTALL button
6. I get administrator authentication windows popup
7. I click "Cancel"
8. elasticsearch installation is cancelled

**Comment by eskibars** [comment]
@fbaligand it sounds like you don't actually want to use an MSI in your case and that your desired behavior is what the zip package provides.  Is there a reason why the .zip wouldn't suffice for you?

**Comment by fbaligand** [comment]
Yes, I could use zip package. 
But MSI is quite convenient with its wizard, including several steps. 

The point in my issue is : there is no reason to require admin rights for a simple installation when  no Windows service is asked.

**Comment by Mpdreamz** [comment]
Point taken @fbaligand :) in the early days we actively tested that no admin rights were needed but gave up on that requirement to ship. 

Would be good to get a handle on this again, thanks for opening this issue :+1:

**Comment by fbaligand** [comment]
Nice to see you take the point !

**Comment by russcam** [comment]
@fbaligand Administrator privileges are required for a number of reasons currently, not just to install as a service

1. The installation currently runs with [`ALLUSERS=1`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa367559(v=vs.85).aspx) to install in a per-machine context, meaning only one installation of the MSI is allowed on the machine for all users. An MSI with `ALLUSERS=1` requires elevated privileges to install under UAC.
2. the default installation directory `C:\Program Files\Elastic` requires administrator privileges to install into 
3. Setting machine environment variables requires administrator privileges (to access the registry).
4. Creating an event source in the event log requires administrator privileges

To consider changing this, we would need to 

1. change the default installation directory from `C:\Program Files\Elastic`
2. change `ALLUSERS=2` to allow per user installation context
3. change Environment variables to set `EnvironmentVariableTarget.User` as opposed to `EnvironmentVariableTarget.Machine`
4. not create an event source for the installation and instead use an existing event source e.g `MsiInstaller`.
5. fail gracefully if the user is not an administrator, trying to install as a service.

**Comment by fbaligand** [comment]
Thanks for the detailed explanation @russcam !

Concerning install directory, as it can be changed by wizard, it is not a problem. 
Concerning other points, I understand that there are several things to do and it changes install goal :
One install per machine vs. one install per user.

**Comment by codebrain** [comment]
Closing as decision was made to require admin rights.
