### ISSUE TITLE
Install Failure - Could not find any executable java binary

### ISSUE THREAD

**Issue by baramustafa** [elastic/windows-installers#56]
Windows 10
Java is installed but the JAVA_HOME environment variable was set to a non-existent folder of older version of jre (not sure why); When I corrected this is installed successfully.

The blog article indicates I shouldn't have needed to fix this (https://www.elastic.co/blog/elasticsearch-windows-msi-installer-release) so am registering it as a bug. :-)

Thanks

```
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Install.ElasticsearchPluginsAction.ElasticsearchPlugins
Elastic.InstallerHosts.Elasticsearch.Tasks.InstallPluginsTask: Installing Elasticsearch plugins
[0] installing x-pack installing x-pack
Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME 
[0] installing x-pack installing x-pack
System.Exception: Execution failed (d:\Program Files\Elastic\Elasticsearch\bin\elasticsearch-plugin.bat install x-pack ). ExitCode: 1 ErrorCheck: True ErrorOut:Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME 

   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 22:52:10: InstallFinalize. Return value 3.
```

**Comment by russcam** [comment]
Thanks for reporting @baramustafa. I think the installer is correct to fail if `JAVA_HOME` points to a non-existent java installation, but I think the error message should be more clear that this is the reason it failed.

**Comment by Mpdreamz** [comment]
It should be one of the the perquisites validations though. The .exe protects against a bad JAVA_HOME with a good error message.

**Comment by russcam** [comment]
`JAVA_HOME` needs to be set only to satisfy installing plugins as part of the installation. If no plugins are installed, then the java detection within the process will kick in to find a suitable java installation.

In the case that `JAVA_HOME` is not set but plugins are selected for installation, I think the error message in the log is good. I don't think we'd want to have it as a prerequisite validation step as it's not necessary for those not installing plugins. @Mpdreamz Am I misunderstanding?

**Comment by russcam** [comment]
Can we close this @Mpdreamz?

**Comment by Sysa** [comment]
Just my two cents:
This is not trivial to remove already existing JAVA_HOME variable if you have correct values in path.
I was done with it only after reading this one - https://stackoverflow.com/questions/42290963/windows7-run-elasticsearch-bat-could-not-find-any-executable-java-binary-please

**Comment by codebrain** [comment]
OP appears to have resolved issue using Stackoverflow, so closing issue.
