### ISSUE TITLE
Remove implicit support for 32-bit

### ISSUE THREAD

**Issue by jasontedor** [elastic/windows-installers#57]
Upstream Elasticsearch does not explicitly support 32-bit JVMs (our CI does not even test it) starting in 6.0.0. This support should be removed from the installer too.

Relates elastic/elasticsearch#25435

**Comment by russcam** [comment]
The installer only supports 64-Bit Windows currently, but will try to use a 32-bit JVM if installed and no 64-bit JVM is installed.

We'll remove this for 6.0.0

**Comment by jasontedor** [comment]
> will try to use a 32-bit JVM if installed and no 64-bit JVM is installed

Yeah, that's exactly what I'm suggesting to remove, thanks a lot for picking this up! 😄

**Comment by codebrain** [comment]
@russcam - can this be closed or a PR opened?

**Comment by codebrain** [comment]
Requires merge into `master` and `6.x`

**Comment by russcam** [comment]
Closing this as remaining pieces have been removed in #325
