### ISSUE TITLE
Error in installing elasticsearch-5.5.0.msi in wndows 8.1

### ISSUE THREAD

**Issue by viveklc** [elastic/windows-installers#59]
Trying to install Elastic search 5.5 in windows 8.1 (64 bit operating system, x64-based processor and 4 GB RAM).

It installs everything perfectly but at the end it says error in installing elastic search.

I look on log file but I am able to recognize the issue. Please see my elastic search log file https://pastebin.com/DaCWPzpr

Please guide, what should be my next step for installing elastic search.

**Comment by russcam** [comment]
Hey @viveklc 

Looking through the log, 

> [0] waiting to start waiting to start
> [0] waiting to start waiting to start
> System.ServiceProcess.TimeoutException: Timeout has expired and the operation has not been completed in 00:01:00.
>    at Elastic.Installer.Domain.Configuration.Service.ServiceStateProvider.StartAndWaitForRunning(TimeSpan timeToWait, Int32 totalTicks)
>    at Elastic.InstallerHosts.Elasticsearch.Tasks.StartServiceTask.ExecuteTask()
>    at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
> CustomAction ElasticsearchServiceStartAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

There could be a number of different reasons why this has happened

1. An exception thrown when Elasticsearch starts which causes the service to not respond as started
2. An intermittent service start issue

Would you be able to try the installation again, or try to install without installing as a service and manually starting the elasticsearch.exe process, to see if it starts successfully?

**Comment by viveklc** [comment]
Thanks for replying @russcam 

Once the installer finished installing, at the final screen of installation; it says that "Elasticsearch not installed successfully" and it also removes the installed directory from the device.

I tried it many times but every time I got the same error on the last screen.

**Comment by russcam** [comment]
@viveklc have you tried not installing as a service and running elasticsearch.exe process manually? Trying to narrow down if it's an installation issue or an issue with Elasticsearch not starting properly.

**Comment by viveklc** [comment]
I manually install by running elasticsearch.exe. I did not try to install as a service.

What details I can share with you so we can find out the reason.

**Comment by timdooling** [comment]
I have had pretty much the same problem.  I solved it by installing Elasticsearch as a service, but not starting it on install.

I later started it manually with the Task Manager, and it worked.

The issue has always been a timeout one.

I also have problems with the plugins installing, but that may also be related to the service start timeout.

**Comment by Mpdreamz** [comment]
@viveklc @timdooling are you able to share your elasticsearch log files from the day you tried installing?

privately is possible too `mailto://microsoft => elastic => co`

**Comment by russcam** [comment]
Closing in favour of #135, so all timeout issues can be consolidated there
