### ISSUE TITLE
Problem installing Elasticsearch on windows 10 x64

### ISSUE THREAD

**Issue by sqlandfriends** [elastic/windows-installers#60]
Hi I have a problem when installing Elasticsearch on my laptop with Win10 64 bit and don't know what is going on. I have admin right which I'm using all time.Memory limit set to 512mb during install. have 4 core cpu, 1TB HDD and 8GB of ram(less then half of it avaible due to system and few other things working in background).

Install log:
http://wklejto.pl/290225

elasticsearch log:
http://wklejto.pl/290226

Please Help.

**Comment by eskibars** [comment]
Looks like the user you are running the service as doesn't have permissions to all the files in C:\ProgramData\Elastic\Elasticsearch\ (specifically, it's getting an access denied exception for C:\ProgramData\Elastic\Elasticsearch\data\nodes\0\node.lock).  I think you need to change the service user to have permissions there.

@Mpdreamz @russcam to we attempt any checks to make sure the service user has write access to that directory?

**Comment by sqlandfriends** [comment]
Hi now i try as NTUSER/Netwrok Service will see if works.

**Comment by russcam** [comment]
@eskibars the installer doesn't attempt to check that a given account has access to `%ALLUSERSPROFILE%` (defaults to `C:\ProgramData`); by default

1. all Administrators (including the default [Local System account](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684190(v=vs.85).aspx)) have read/write access
2. all Users have read access 

to this location.

The Local System account (the default) will have read/write access.

@sqlandfriends which account did you use to run the Windows Service under?

**Comment by Mpdreamz** [comment]
This appears to be the same issue as #68 closing this one as duplicate. 

Many thanks for taking the time to report the issue @sqlandfriends much appreciated.
