### ISSUE TITLE
Configure service name to be able to create multiple services

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/windows-installers#62]
As for today, there is no way to install more than 1 service with the installer since the service name is not configurable. For cases where you run multiple nodes in a single box, it should be useful to have a configurable service name.

**Comment by Mpdreamz** [comment]
@SergeyBarskiy do you want the change the service name only or do you expect the installer to be able to install side by side?

**Comment by SergeyBarskiy** [comment]
Both, change the name and install side-by-side with another instance.
Thanks.

**Comment by codebrain** [comment]
In situations like this it is probably better to use the zip distribution.

Installing multiple services or side-by-side installs with the single MSI will dramatically increase the complexity of the installer. We also have to consider upgrades, rollbacks and uninstalls with each scenario.

@eskibars - can we close this issue and recommend that users with complex install situations like this manage it through the zip distribution?

**Comment by sophiec20** [comment]
+1 to not increasing complexity - we should add to docs as a non-supported scenario.

**Comment by eskibars** [comment]
> @eskibars - can we close this issue and recommend that users with complex install situations like this manage it through the zip distribution?

+1
