### ISSUE TITLE
Offline installation with plugins

### ISSUE THREAD

**Issue by askids** [elastic/windows-installers#67]
hi,

Currently, when we select the required plugin, it will try to download from internet. Instead, can we have an additional parameter which can be used to point to the folder location that has the plugin already downloaded like PLUGINLOCALPATH=C:\Temp\ElasticPlugins ? Installer can then use the plugin from this location rather than trying to download it. 

Other option is give a parameter like PLUGINDOWNLOAD=false in which case, the installer can look for the plugin in the same folder location from where the MSI is being run. 

Either of these options will allow the installation to be run completely offline without needing an internet connection on the server.

Thanks!

**Comment by russcam** [comment]
Hey @askids, an already downloaded plugin can be installed in Elasticsearch after the MSI installation, using the same mechanism as you're used to with the zip package

```sh
bin/elasticsearch-plugin.bat install file:///path/to/plugin.zip
```

This is also the way that you can install _any_ plugin that is not listed in the MSI GUI

I think there's a risk of making the installation experience overly complicated by introducing additional command line parameters to handle this at _MSI installation time_

**Comment by askids** [comment]
@russcam if we have to install the plugin separately, then it defeats the purpose of giving the option of selecting the plugin in the installer. The whole point of suggesting the above feature was to support the existing feature of being able to select and install the plugins along with the main Elasticsearch service, but at the same time, without having the need to have an internet connection.

Currently, just for plugin, we are forced to have internet connection which might not be allowed on most intranet servers as an enterprise policy. 

If we don't want to introduce additional parameters, I am fine with it as long as we can change the default behaviour of the installer to look for the plugin locally and only when the files are not found, then try to download it from internet. Ideally, I would have suggested to include the plugin within the MSI itself. But since that would make the MSI size bigger, I would understand if its not included by default within the MSI. But then with the installer by default looking for the plugins in the same location, we can avoid the internet requirement for installation.

At basic minimum, i would expect everyone planning to use Elasticsearch in real world applications to be at least running the monitoring plugin, if not others. Why on earth would Elastic consider monitor as a plugin and not package it along with the core Elasticsearch product is beyond my understanding. I would pose the same question for security as well. But that's a totally different conversation to have :)

**Comment by askids** [comment]
@russcam are you planning to change the default behavior to look for plugin file locally before attempting to download from internet? It would simplify offline installation to great extent.

**Comment by russcam** [comment]
@askids it's something that still needs to be looked into, to better understand the scope and implications. Not ruling it out at this stage, I think it would be useful.

**Comment by askids** [comment]
@russcam I was looking at the install log for silent install. In the input, I had give `PLUGINS="x-pack"`. Since I had not set JAVA_HOME yet, the install failed as expected. 
```
Elastic.InstallerHosts.Elasticsearch.Tasks.InstallPluginsTask: Installing Elasticsearch plugins
[0] installing x-pack installing x-pack
Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME 
[0] installing x-pack installing x-pack
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\bin\elasticsearch-plugin.bat install x-pack ). ExitCode: 1 ErrorCheck: True ErrorOut:Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME 
```
But what I found surprising was that installers is also internally using `elasticsearch-plugin.bat install` command for installing the plugin. So instead of providing `PLUGINS="x-pack"`, what if users can provide the input like `PLUGINS="file:///c:/temp/x-pack-5.5.2.zip"`? Since we are already providing the plugin file path directly, will you be able use that path directly instead of trying to download? 

Once you add this generic file path support for plugins, I think that it can be easily extended for other plugins as well and not just the official plugins from Elastic. Then silent install will be much more useful.

**Comment by russcam** [comment]
That _should_ work from the command line, but it's not been tested. It won't help installation with the GUI though as there's no way to specify a path for each plugin. I think in this case, being able to pass a parameter for a directory from which to install plugin zips would be simpler.

**Comment by askids** [comment]
Yes. Passing folder path of local plugins will also do and that was the original suggestion ..LOL.

**Comment by askids** [comment]
Just wanted to add the issue that we are now facing with not having offline plugin install capability in the windows installers. We used the msi with command line silent install on 5.5.1, but had to install plugin manually as internet connection is not allowed on our servers. Now when we have upgrade to higher version of ES, we have to again do the uninstall manually of the plug-in and then do upgrade using MSI silent install and then again do the plug-in install manually. Hopefully you are beginning to understand why offline plugin install is a necessary feature for us and not a nice to have feature as this would reduce lot of manual work. I would sincerely request that this feature be given some priority.

**Comment by russcam** [comment]
hey @askids, our priority is getting the installer ready for GA release. I agree that having the ability to perform offline installation would be useful and it is something we'd like to look at after the installer is ready for GA.

**Comment by codebrain** [comment]
The situation (for x-pack) at least has now changed with the release of 6.3.0 - I wonder if this has a bearing on the feature request? Will mark as for discussion and as enhancement.

**Comment by codebrain** [comment]
Addressed in https://github.com/elastic/windows-installers/pull/185

**Comment by codebrain** [comment]
This feature should make it into 6.4.0+

There are no intentions to re-release the already-released installers, will discuss with the team about back-porting into the `5.x` branch for future versions.

**Comment by askids** [comment]
@codebrain Is this now available with standard installer?

**Comment by askids** [comment]
@codebrain following up? Is this feature now available?

**Comment by codebrain** [comment]
@askids - yes, this was merged in on #185 

It is possible to provide a list of local zip files using the PLUGINS parameter on the command line: https://www.elastic.co/guide/en/elasticsearch/reference/current/windows.html#msi-command-line-options

For installing from local files, use the file protocol prefix, e.g. `file:///C:\ingest-attachment.zip`

Closing this issue as no resolved.

**Comment by askids** [comment]
> For installing from local files, use the file protocol prefix, e.g. `file:///C:\ingest-attachment.zip`

@codebrain thanks for the update. Couple of questions.
1. Does this only support ES supported plugins or will this support community plugins as well?
2. If we have to include multiple plugins from local files, how will the PLUGINS parameter look like? Can you please provide example?

**Comment by codebrain** [comment]
Hi @askids 

1. The MSI plugin installation is instrumented through the underlying `elasticsearch-plugin.bat` batch file: https://github.com/elastic/windows-installers/blob/0e9a9338f28a505a27cefec32aaaf8af9eab2bd2/src/Installer/Elastic.Installer.Domain/Configuration/Plugin/PluginStateProviderBase.cs#L29 so you will be able to install any compatible plugin, either official or community.

2. The documentation for the plugins argument is:

> **PLUGINS**: A comma separated list of the plugins to download and install as part of the installation. Defaults to ""

An example invocation would be:

`start /wait msiexec.exe /i elasticsearch-7.6.0.msi /qn PLUGINS="file:///C:\ingest-attachment.zip,file:///C:\ingest-user-agent.zip"`

**Comment by russcam** [comment]
Note that **the MSI will only install plugins as part of the installer installation process that are listed in** 

https://github.com/elastic/windows-installers/blob/421ea616464acf0641b203509b705b5c9d4e2978/src/Installer/Elastic.Installer.Domain/Model/Elasticsearch/Plugins/PluginsModel.cs#L164-L293

Any other plugins can be installed using the `elasticsearch-plugin.bat` file in the `${HOME}\bin` directory, after the MSI installation has completed.

**Comment by codebrain** [comment]
Thank you for the clarification @russcam

**Comment by askids** [comment]
Thanks for the clarification. One more question. When we upgrade using MSI, do we need to remove other existing community plugins upfront using elasticsearch-plugin.bat or does the upgrade process takes care of removing all external plugins or do we not care at all, about existing plugins?

**Comment by xuboke** [comment]
>docker-compose exec elasticsearch elasticsearch-plugin install file:///D:\elasticsearch-analysis-ik-7.1.0.zip
-> Downloading file:///D:\elasticsearch-analysis-ik-7.1.0.zip
Exception in thread "main" java.io.FileNotFoundException: /D:\elasticsearch-analysis-ik-7.1.0.zip (No such file or directory)
