### ISSUE TITLE
an error occurred during installation

### ISSUE THREAD

**Issue by Biswajitmn** [elastic/windows-installers#69]
an error occurred during installation 
![image](https://user-images.githubusercontent.com/30856790/29108924-98e29648-7cfe-11e7-880b-a9d6a0a5e612.png)

**Comment by russcam** [comment]
@Biswajitmn could you please attach the installation log and Elasticsearch log?

**Comment by Biswajitmn** [comment]
solve it.

**Comment by russcam** [comment]
@Biswajitmn what was the issue? Could you add details here for how you solved it, it may help someone else in the future with the same issue.

**Comment by Biswajitmn** [comment]
not checked x-pack
![image](https://user-images.githubusercontent.com/30856790/29110838-af85d840-7d05-11e7-90de-1701ba037794.png)

**Comment by russcam** [comment]
Thanks for reporting back, glad you got it sorted 👍
