### ISSUE TITLE
Test fails on computers with a Y-drive

### ISSUE THREAD

**Issue by mikkelbu** [elastic/windows-installers#7]
The test `MustBeOnKnownDrive` fails on one of my computers, since the computer has a Y-drive. Ideally, `LocationsModelValidator` should accept an abstraction instead of directly accessing the filesystem of the computer. Then we can supply `DriveInfo.GetDrives()` in production code and some mock in tests.

This is a very minor problem for me, as I can just disconnect the drive while building the solution.

> 
    Elastic.Installer.Domain.Tests.Elasticsearch.Models.Location.LocationModelTests.MustBeOnKnownDrive [FAIL]
      Expected False because LocationsModel should be invalid, but found True.
      Stack Trace:
        C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs(35,0): at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
        C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs(197,0): at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
        C:\projects\fluentassertions-vf06b\Src\Core\Primitives\BooleanAssertions.cs(40,0): at FluentAssertions.Primitives.BooleanAssertions.BeFalse(String because, Object[] becauseArgs)
        src\Tests\Elastic.Installer.Domain.Tests\Elasticsearch\Models\InstallationModelTester.cs(104,0): at Elastic.Installer.Domain.Tests.Elasticsearch.Models.InstallationModelTester.IsInvalidOnStep(Action`1 validateErrors, IValidatableReactiveObject step)
        src\Tests\Elastic.Installer.Domain.Tests\Elasticsearch\Models\Location\LocationModelTests.cs(44,0): at Elastic.Installer.Domain.Tests.Elasticsearch.Models.Location.LocationModelTests.MustBeOnKnownDrive()

**Comment by codebrain** [comment]
Perhaps consider calling the sc.exe post-installation to set this parameter:

sc config SVCNAME start= delayed-auto

(Note the space before delayed-auto)

**Comment by russcam** [comment]
An alternative approach which I think is sufficient to satisfy this test is for the test to supply a drive that does not exist for the environment in which it's executed
