### ISSUE TITLE
Not installing on Elastic search 0n windows 8.1

### ISSUE THREAD

**Issue by mhraza95** [elastic/windows-installers#73]
I have tried all the option mentioned below but unfortunately not able to install in windows 8.1
and Elasticsearch version is 5.5.1

**Comment by russcam** [comment]
@mhraza95 could you attach the MSI installer log and Elasticsearch log (if there is one)?

**Comment by russcam** [comment]
Any update on this @mhraza95?

**Comment by russcam** [comment]
Closing this issue as no response received. Feel free to open again @mhraza95 with an update 👍
