### ISSUE TITLE
Calling elasticsearch-plugin.bat on windows 7 reports its not called correctly

### ISSUE THREAD

**Issue by yanwei2508** [elastic/windows-installers#75]
I try to install it ,but it failed, my computer is windows 7 professional, don't know the reason

[MSIba93aLOG.txt](https://github.com/elastic/windows-installers/files/1225180/MSIba93aLOG.txt)

**Comment by Mpdreamz** [comment]
Thanks for reporting @yanwei2508 

> [0] installing x-pack installing x-pack
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\bin\elasticsearch-plugin.bat install x-pack ). ExitCode: 255 ErrorCheck: True ErrorOut:The syntax of the command is incorrect.

>   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.Tasks.InstallationTaskBase.Execute()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 actio

The x-pack installation fails:

> ExitCode: 255 ErrorCheck: True ErrorOut:The syntax of the command is incorrect.

This might be related to windows 7 but would need to confirm

**Comment by codebrain** [comment]
Closing as OP resolved issue with install of JDK9 and creation of environment variable.
