### ISSUE TITLE
MSI 5.5.1 installer and Java version < 1.8

### ISSUE THREAD

**Issue by bosinm** [elastic/windows-installers#76]
The MSI installer should show a warning when the Java version does not meet the minimum requirements.

I found it by chance. Steps I followed:

**Environment**

- OS: Windows 2012 R2 x64
- Java JDK: 1.7_079
- ES 5.5.1 MSI installer

1. VM machine where JAVA_HOME was set and using Java JDK 1.7_079 (there was an old ES install)
2. Run the ES 5.5.1 MSI installer and select the option of installing as windows service
3. The installer runs successfully and installs ES as service
4. Start the ES Service under Windows 'Services'
5. The service starts initially and it stops suddenly. It does not always show a warning or error message. 
6. I then downloaded the zip build and when starting ES there was a warning about the Java version. 
7. By checking Windows Event Viewer you could see:

![screen shot 2017-08-17 at 12 54 05](https://user-images.githubusercontent.com/13623747/29428133-6c608d98-838c-11e7-8a2c-4ac85e69509b.png)
![screen shot 2017-08-17 at 12 54 16](https://user-images.githubusercontent.com/13623747/29428142-73c59d76-838c-11e7-9acd-0dfe823793e3.png)

I am attaching also:

- the report.wer (uploaded as .txt, you might want to change the extension to .wer)file that is indicated in the second screenshot
- In the second screenshot, on the 'details' tab, I took the info on a xml format

[details view.txt](https://github.com/elastic/windows-installers/files/1232308/details.view.txt)

[Report.txt](https://github.com/elastic/windows-installers/files/1232366/Report.txt)

**Comment by russcam** [comment]
Thanks for the info @bosinm. 

1. Do you also have the MSI log for the failed installation? 
2. Did you install using the UI, or perform a silent installation via the command line?

The installer has checks for whether Java is installed or misconfigured but doesn't currently check the version. It seems prudent to also check the version.

**Comment by russcam** [comment]
@Mpdreamz can we close this?
