### ISSUE TITLE
Plugin installation fails on win7 can't find: lib\i386\jvm.cfg

### ISSUE THREAD

**Issue by moazam1** [elastic/windows-installers#80]
I am getting following error when I try to install ElasticSearch on Win 7 64bit. 

![2017-08-22_0236](https://user-images.githubusercontent.com/5168122/29544870-f49ad8ea-86e2-11e7-9331-80a2a9ad1277.png)

Error log: https://www.dropbox.com/s/ia0mgxll7de8mx8/MSIbede8.LOG?dl=0

**Comment by Mpdreamz** [comment]
Thanks for opening this issue the reason for this is that the `elasticsearch-plugin.bat` fails to run java on your system

> System.Exception: Execution failed (D:\ElasticSearch\bin\elasticsearch-plugin.bat install lang-javascript ). ExitCode: 0 ErrorCheck: True ErrorOut:Error: could not open `C:\Program Files (x86)\Java\jre1.8.0_60\lib\i386\jvm.cfg'

This is something we have not seen before will have to try and replicate on a windows 7 machine.

**Comment by moazam1** [comment]
Thanks
