### ISSUE TITLE
Add ability to specify X-Pack credentials at install time

### ISSUE THREAD

**Issue by russcam** [elastic/windows-installers#95]
Current preleases of the MSI for 6.0.0 do not provide a way to specify credentials at installation time. [With the change in removing default credentials for the `elastic` account](https://www.elastic.co/guide/en/x-pack/6.0/setting-up-authentication.html), a password should be specified at installation time when installing X-Pack.

**Comment by Mpdreamz** [comment]
We can only do this from the installer if we install as service AND the service is set to start automatically. 

The server needs to be up and running for the tool to run.

**Comment by russcam** [comment]
Can we start the node, apply credentials, then stop it?

**Comment by Mpdreamz** [comment]
We can but if you explicitly say do not start after install we should not start at all IMO. There are many valid reasons why you would want to defer the start. I opened two internal tickets the improve the experience in our tooling here.

**Comment by russcam** [comment]
Agree that not starting at all would be best

**Comment by russcam** [comment]
If the user opts to not install as a service, we can still set the `bootstrap.password` property in the elasticsearch keystore, which won't require the service to be running.

**Comment by russcam** [comment]
Closed via https://github.com/elastic/windows-installers/pull/122
