### ISSUE TITLE
Cancelling X-Pack download on 5.5.1 -> 5.5.2 upgrade causes problem

### ISSUE THREAD

**Issue by codebrain** [elastic/windows-installers#97]
To reproduce:

1) Install 5.5.1 MSI - default directories, NOT as a service, with X-Pack installed
2) Run 5.5.1 exe
3) Begin the 5.5.2 MSI upgrade, including X-Pack.
4) Cancel X-Pack before it has chance to download
5) Installer exits with 'goodbye message' (as expected)
6) Try to run old 5.5.1 exe, watch failure.

Failure message is:

```
"C:\Program Files\Elastic\Elasticsearch\bin\elasticsearch.exe"
Expected a 'lib' directory inside: C:\elasticsearch-5.5.2
```

Attached is MSI Log file
[MSI6b0f8.LOG.txt](https://github.com/elastic/windows-installers/files/1273800/MSI6b0f8.LOG.txt)

**Comment by russcam** [comment]
This is on branch: https://github.com/elastic/windows-installers/tree/fix/92

**Comment by russcam** [comment]
I haven't been able to reproduce this issue so I'm closing. We'll reopen if it occurs again 👍
